import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { YadlGeneratedModule, YadlGeneratedSharedModule } from './generated/module.js';
import { YadlValidator, registerValidationChecks } from './yadl-validator.js';
import { YadlFormatter } from './yadl-formatter.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type YadlAddedServices = {
    validation: {
        YadlValidator: YadlValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type YadlServices = LangiumServices & YadlAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const YadlModule: Module<YadlServices, PartialLangiumServices & YadlAddedServices> = {
    validation: {
        YadlValidator: () => new YadlValidator()
    },
    lsp: {
        Formatter: () => new YadlFormatter(),
    },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createYadlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Yadl: YadlServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        YadlGeneratedSharedModule
    );
    const Yadl = inject(
        createDefaultModule({ shared }),
        YadlGeneratedModule,
        YadlModule
    );
    shared.ServiceRegistry.register(Yadl);
    registerValidationChecks(Yadl);
    return { shared, Yadl };
}
