
export * from "./Backup";
export * from "./EFS";
export * from "./ElasticBlockStore";
export * from "./ElasticDisasterRecovery";
export * from "./FSx";
export * from "./FSxforLustre";
export * from "./FSxforNetAppONTAP";
export * from "./FSxforOpenZFS";
export * from "./FSxforWFS";
export * from "./FileCache";
export * from "./S3onOutposts";
export * from "./SimpleStorageService";
export * from "./SimpleStorageServiceGlacier";
export * from "./Snowball";
export * from "./SnowballEdge";
export * from "./Snowcone";
export * from "./Snowmobile";
export * from "./StorageGateway";