import { IconNames } from "yadl-core-package";

export const GCPIconNames: IconNames = {
  gCPAccessContextManager: {
    name: "Access Context Manager",
    icon: "GCPAccessContextManager",
  },
  gCPAiHub: { name: "Ai Hub", icon: "GCPAiHub" },
  gCPAdvancedAgentModeling: {
    name: "Advanced Agent Modeling",
    icon: "GCPAdvancedAgentModeling",
  },
  gCPAdministration: { name: "Administration", icon: "GCPAdministration" },
  gCPAiPlatformUnified: {
    name: "Ai Platform Unified",
    icon: "GCPAiPlatformUnified",
  },
  gCPAiPlatform: { name: "Ai Platform", icon: "GCPAiPlatform" },
  gCPAgentAssist: { name: "Agent Assist", icon: "GCPAgentAssist" },
  gCPAnalyticsHub: { name: "Analytics Hub", icon: "GCPAnalyticsHub" },
  gCPAdvancedSolutionsLab: {
    name: "Advanced Solutions Lab",
    icon: "GCPAdvancedSolutionsLab",
  },
  gCPAnthos: { name: "Anthos", icon: "GCPAnthos" },
  gCPAnthosConfigManagement: {
    name: "Anthos Config Management",
    icon: "GCPAnthosConfigManagement",
  },
  gCPAppEngine: { name: "App Engine", icon: "GCPAppEngine" },
  gCPAnthosServiceMesh: {
    name: "Anthos Service Mesh",
    icon: "GCPAnthosServiceMesh",
  },
  gCPApi: { name: "Api", icon: "GCPApi" },
  gCPApiMonetization: { name: "Api Monetization", icon: "GCPApiMonetization" },
  gCPApigeeApiPlatform: {
    name: "Apigee Api Platform",
    icon: "GCPApigeeApiPlatform",
  },
  gCPApiAnalytics: { name: "Api Analytics", icon: "GCPApiAnalytics" },
  gCPArtifactRegistry: {
    name: "Artifact Registry",
    icon: "GCPArtifactRegistry",
  },
  gCPApigeeSense: { name: "Apigee Sense", icon: "GCPApigeeSense" },
  gCPAutoml: { name: "Automl", icon: "GCPAutoml" },
  gCPAutomlTables: { name: "Automl Tables", icon: "GCPAutomlTables" },
  gCPAssuredWorkloads: {
    name: "Assured Workloads",
    icon: "GCPAssuredWorkloads",
  },
  gCPAssetInventory: { name: "Asset Inventory", icon: "GCPAssetInventory" },
  gCPAutomlTranslation: {
    name: "Automl Translation",
    icon: "GCPAutomlTranslation",
  },
  gCPAutomlVideoIntelligence: {
    name: "Automl Video Intelligence",
    icon: "GCPAutomlVideoIntelligence",
  },
  gCPAutomlVision: { name: "Automl Vision", icon: "GCPAutomlVision" },
  gCPAutomlNaturalLanguage: {
    name: "Automl Natural Language",
    icon: "GCPAutomlNaturalLanguage",
  },
  gCPBareMetalSolutions: {
    name: "Bare Metal Solutions",
    icon: "GCPBareMetalSolutions",
  },
  gCPBeyondcorp: { name: "Beyondcorp", icon: "GCPBeyondcorp" },
  gCPBigtable: { name: "Bigtable", icon: "GCPBigtable" },
  gCPBatch: { name: "Batch", icon: "GCPBatch" },
  gCPBigquery: { name: "Bigquery", icon: "GCPBigquery" },
  gCPBilling: { name: "Billing", icon: "GCPBilling" },
  gCPCertificateManager: {
    name: "Certificate Manager",
    icon: "GCPCertificateManager",
  },
  gCPCatalog: { name: "Catalog", icon: "GCPCatalog" },
  gCPCertificateAuthorityService: {
    name: "Certificate Authority Service",
    icon: "GCPCertificateAuthorityService",
  },
  gCPCloudApiGateway: { name: "Cloud Api Gateway", icon: "GCPCloudApiGateway" },
  gCPCloudAssetInventory: {
    name: "Cloud Asset Inventory",
    icon: "GCPCloudAssetInventory",
  },
  gCPCloudAuditLogs: { name: "Cloud Audit Logs", icon: "GCPCloudAuditLogs" },
  gCPCloudApis: { name: "Cloud Apis", icon: "GCPCloudApis" },
  gCPCloudCdn: { name: "Cloud Cdn", icon: "GCPCloudCdn" },
  gCPCloudBuild: { name: "Cloud Build", icon: "GCPCloudBuild" },
  gCPBinaryAuthorization: {
    name: "Binary Authorization",
    icon: "GCPBinaryAuthorization",
  },
  gCPCloudComposer: { name: "Cloud Composer", icon: "GCPCloudComposer" },
  gCPCloudArmor: { name: "Cloud Armor", icon: "GCPCloudArmor" },
  gCPCloudCode: { name: "Cloud Code", icon: "GCPCloudCode" },
  gCPCloudDataFusion: { name: "Cloud Data Fusion", icon: "GCPCloudDataFusion" },
  gCPCloudDeploymentManager: {
    name: "Cloud Deployment Manager",
    icon: "GCPCloudDeploymentManager",
  },
  gCPCloudDeploy: { name: "Cloud Deploy", icon: "GCPCloudDeploy" },
  gCPCloudDns: { name: "Cloud Dns", icon: "GCPCloudDns" },
  gCPCloudDomains: { name: "Cloud Domains", icon: "GCPCloudDomains" },
  gCPCloudEkm: { name: "Cloud Ekm", icon: "GCPCloudEkm" },
  gCPCloudEndpoints: { name: "Cloud Endpoints", icon: "GCPCloudEndpoints" },
  gCPCloudExternalIpAddresses: {
    name: "Cloud External Ip Addresses",
    icon: "GCPCloudExternalIpAddresses",
  },
  gCPCloudFirewallRules: {
    name: "Cloud Firewall Rules",
    icon: "GCPCloudFirewallRules",
  },
  gCPCloudGpu: { name: "Cloud Gpu", icon: "GCPCloudGpu" },
  gCPCloudForMarketing: {
    name: "Cloud For Marketing",
    icon: "GCPCloudForMarketing",
  },
  gCPCloudFunctions: { name: "Cloud Functions", icon: "GCPCloudFunctions" },
  gCPCloudGeneric: { name: "Cloud Generic", icon: "GCPCloudGeneric" },
  gCPCloudHealthcareMarketplace: {
    name: "Cloud Healthcare Marketplace",
    icon: "GCPCloudHealthcareMarketplace",
  },
  gCPCloudHealthcareApi: {
    name: "Cloud Healthcare Api",
    icon: "GCPCloudHealthcareApi",
  },
  gCPCloudInterconnect: {
    name: "Cloud Interconnect",
    icon: "GCPCloudInterconnect",
  },
  gCPCloudInferenceApi: {
    name: "Cloud Inference Api",
    icon: "GCPCloudInferenceApi",
  },
  gCPCloudIds: { name: "Cloud Ids", icon: "GCPCloudIds" },
  gCPCloudHsm: { name: "Cloud Hsm", icon: "GCPCloudHsm" },
  gCPCloudLogging: { name: "Cloud Logging", icon: "GCPCloudLogging" },
  gCPCloudJobsApi: { name: "Cloud Jobs Api", icon: "GCPCloudJobsApi" },
  gCPCloudLoadBalancing: {
    name: "Cloud Load Balancing",
    icon: "GCPCloudLoadBalancing",
  },
  gCPCloudMonitoring: { name: "Cloud Monitoring", icon: "GCPCloudMonitoring" },
  gCPCloudMediaEdge: { name: "Cloud Media Edge", icon: "GCPCloudMediaEdge" },
  gCPCloudNetwork: { name: "Cloud Network", icon: "GCPCloudNetwork" },
  gCPCloudNaturalLanguageApi: {
    name: "Cloud Natural Language Api",
    icon: "GCPCloudNaturalLanguageApi",
  },
  gCPCloudOptimizationAi: {
    name: "Cloud Optimization Ai",
    icon: "GCPCloudOptimizationAi",
  },
  gCPCloudOps: { name: "Cloud Ops", icon: "GCPCloudOps" },
  gCPCloudNat: { name: "Cloud Nat", icon: "GCPCloudNat" },
  gCPCloudRouter: { name: "Cloud Router", icon: "GCPCloudRouter" },
  gCPCloudRoutes: { name: "Cloud Routes", icon: "GCPCloudRoutes" },
  gCPCloudRunForAnthos: {
    name: "Cloud Run For Anthos",
    icon: "GCPCloudRunForAnthos",
  },
  gCPCloudRun: { name: "Cloud Run", icon: "GCPCloudRun" },
  gCPCloudScheduler: { name: "Cloud Scheduler", icon: "GCPCloudScheduler" },
  gCPCloudShell: { name: "Cloud Shell", icon: "GCPCloudShell" },
  gCPCloudSpanner: { name: "Cloud Spanner", icon: "GCPCloudSpanner" },
  gCPCloudStorage: { name: "Cloud Storage", icon: "GCPCloudStorage" },
  gCPCloudSecurityScanner: {
    name: "Cloud Security Scanner",
    icon: "GCPCloudSecurityScanner",
  },
  gCPCloudTasks: { name: "Cloud Tasks", icon: "GCPCloudTasks" },
  gCPCloudTranslationApi: {
    name: "Cloud Translation Api",
    icon: "GCPCloudTranslationApi",
  },
  gCPCloudTestLab: { name: "Cloud Test Lab", icon: "GCPCloudTestLab" },
  gCPCloudTpu: { name: "Cloud Tpu", icon: "GCPCloudTpu" },
  gCPCloudSql: { name: "Cloud Sql", icon: "GCPCloudSql" },
  gCPCloudVpn: { name: "Cloud Vpn", icon: "GCPCloudVpn" },
  gCPCloudVisionApi: { name: "Cloud Vision Api", icon: "GCPCloudVisionApi" },
  gCPCloudOptimizationAiFleetRoutingApi: {
    name: "Cloud Optimization Ai Fleet Routing Api",
    icon: "GCPCloudOptimizationAiFleetRoutingApi",
  },
  gCPConnectors: { name: "Connectors", icon: "GCPConnectors" },
  gCPConfigurationManagement: {
    name: "Configuration Management",
    icon: "GCPConfigurationManagement",
  },
  gCPConnectivityTest: {
    name: "Connectivity Test",
    icon: "GCPConnectivityTest",
  },
  gCPContainerOptimizedOs: {
    name: "Container Optimized Os",
    icon: "GCPContainerOptimizedOs",
  },
  gCPComputeEngine: { name: "Compute Engine", icon: "GCPComputeEngine" },
  gCPContainerRegistry: {
    name: "Container Registry",
    icon: "GCPContainerRegistry",
  },
  gCPDataCatalog: { name: "Data Catalog", icon: "GCPDataCatalog" },
  gCPDataLayers: { name: "Data Layers", icon: "GCPDataLayers" },
  gCPDataQna: { name: "Data Qna", icon: "GCPDataQna" },
  gCPDataLabeling: { name: "Data Labeling", icon: "GCPDataLabeling" },
  gCPContactCenterAi: { name: "Contact Center Ai", icon: "GCPContactCenterAi" },
  gCPDataTransfer: { name: "Data Transfer", icon: "GCPDataTransfer" },
  gCPDataStudio: { name: "Data Studio", icon: "GCPDataStudio" },
  gCPDataLossPreventionApi: {
    name: "Data Loss Prevention Api",
    icon: "GCPDataLossPreventionApi",
  },
  gCPDatabaseMigrationService: {
    name: "Database Migration Service",
    icon: "GCPDatabaseMigrationService",
  },
  gCPDataflow: { name: "Dataflow", icon: "GCPDataflow" },
  gCPDatalab: { name: "Datalab", icon: "GCPDatalab" },
  gCPDataplex: { name: "Dataplex", icon: "GCPDataplex" },
  gCPDataproc: { name: "Dataproc", icon: "GCPDataproc" },
  gCPDatapol: { name: "Datapol", icon: "GCPDatapol" },
  gCPDataprocMetastore: {
    name: "Dataproc Metastore",
    icon: "GCPDataprocMetastore",
  },
  gCPDataprep: { name: "Dataprep", icon: "GCPDataprep" },
  gCPDatastore: { name: "Datastore", icon: "GCPDatastore" },
  gCPDatashare: { name: "Datashare", icon: "GCPDatashare" },
  gCPDebugger: { name: "Debugger", icon: "GCPDebugger" },
  gCPDatastream: { name: "Datastream", icon: "GCPDatastream" },
  gCPDialogflow: { name: "Dialogflow", icon: "GCPDialogflow" },
  gCPDeveloperPortal: { name: "Developer Portal", icon: "GCPDeveloperPortal" },
  gCPDialogflowCx: { name: "Dialogflow Cx", icon: "GCPDialogflowCx" },
  gCPDialogflowInsights: {
    name: "Dialogflow Insights",
    icon: "GCPDialogflowInsights",
  },
  gCPDocumentAi: { name: "Document Ai", icon: "GCPDocumentAi" },
  gCPEventarc: { name: "Eventarc", icon: "GCPEventarc" },
  gCPErrorReporting: { name: "Error Reporting", icon: "GCPErrorReporting" },
  gCPEarlyAccessCenter: {
    name: "Early Access Center",
    icon: "GCPEarlyAccessCenter",
  },
  gCPFilestore: { name: "Filestore", icon: "GCPFilestore" },
  gCPFirestore: { name: "Firestore", icon: "GCPFirestore" },
  gCPFinancialServicesMarketplace: {
    name: "Financial Services Marketplace",
    icon: "GCPFinancialServicesMarketplace",
  },
  gCPFleetEngine: { name: "Fleet Engine", icon: "GCPFleetEngine" },
  gCPGkeOnprem: { name: "Gke On Prem", icon: "GCPGkeOnprem" },
  gCPFreeTrial: { name: "Free Trial", icon: "GCPFreeTrial" },
  gCPGameServers: { name: "Game Servers", icon: "GCPGameServers" },
  gCPGenomics: { name: "Genomics", icon: "GCPGenomics" },
  gCPGoogleKubernetesEngine: {
    name: "Google Kubernetes Engine",
    icon: "GCPGoogleKubernetesEngine",
  },
  gCPGoogleCloudMarketplace: {
    name: "Google Cloud Marketplace",
    icon: "GCPGoogleCloudMarketplace",
  },
  gCPGoogleMapsPlatform: {
    name: "Google Maps Platform",
    icon: "GCPGoogleMapsPlatform",
  },
  gCPGceSystemsManagement: {
    name: "Gce Systems Management",
    icon: "GCPGceSystemsManagement",
  },
  gCPHealthcareNlpApi: {
    name: "Healthcare Nlp Api",
    icon: "GCPHealthcareNlpApi",
  },
  gCPIdentityawareProxy: {
    name: "Identity Aware Proxy",
    icon: "GCPIdentityawareProxy",
  },
  gCPIdentityPlatform: {
    name: "Identity Platform",
    icon: "GCPIdentityPlatform",
  },
  gCPHome: { name: "Home", icon: "GCPHome" },
  gCPIotEdge: { name: "Iot Edge", icon: "GCPIotEdge" },
  gCPIotCore: { name: "Iot Core", icon: "GCPIotCore" },
  gCPKeyAccessJustifications: {
    name: "Key Access Justifications",
    icon: "GCPKeyAccessJustifications",
  },
  gCPLauncher: { name: "Launcher", icon: "GCPLauncher" },
  gCPKeyManagementService: {
    name: "Key Management Service",
    icon: "GCPKeyManagementService",
  },
  gCPIdentityAndAccessManagement: {
    name: "Identity And Access Management",
    icon: "GCPIdentityAndAccessManagement",
  },
  gCPLooker: { name: "Looker", icon: "GCPLooker" },
  gCPKuberun: { name: "Kuberun", icon: "GCPKuberun" },
  gCPManagedServiceForMicrosoftActiveDirectory: {
    name: "Managed Service For Microsoft Active Directory",
    icon: "GCPManagedServiceForMicrosoftActiveDirectory",
  },
  gCPMediaTranslationApi: {
    name: "Media Translation Api",
    icon: "GCPMediaTranslationApi",
  },
  gCPLocalSsd: { name: "Local Ssd", icon: "GCPLocalSsd" },
  gCPMigrateForAnthos: {
    name: "Migrate For Anthos",
    icon: "GCPMigrateForAnthos",
  },
  gCPMemorystore: { name: "Memorystore", icon: "GCPMemorystore" },
  gCPMyCloud: { name: "My Cloud", icon: "GCPMyCloud" },
  gCPMigrateForComputeEngine: {
    name: "Migrate For Compute Engine",
    icon: "GCPMigrateForComputeEngine",
  },
  gCPNetworkConnectivityCenter: {
    name: "Network Connectivity Center",
    icon: "GCPNetworkConnectivityCenter",
  },
  gCPNetworkIntelligenceCenter: {
    name: "Network Intelligence Center",
    icon: "GCPNetworkIntelligenceCenter",
  },
  gCPNetworkTopology: { name: "Network Topology", icon: "GCPNetworkTopology" },
  gCPNetworkTiers: { name: "Network Tiers", icon: "GCPNetworkTiers" },
  gCPNetworkSecurity: { name: "Network Security", icon: "GCPNetworkSecurity" },
  gCPOsPatchManagement: {
    name: "Os Patch Management",
    icon: "GCPOsPatchManagement",
  },
  gCPPartnerInterconnect: {
    name: "Partner Interconnect",
    icon: "GCPPartnerInterconnect",
  },
  gCPOsInventoryManagement: {
    name: "Os Inventory Management",
    icon: "GCPOsInventoryManagement",
  },
  gCPPartnerPortal: { name: "Partner Portal", icon: "GCPPartnerPortal" },
  gCPOsConfigurationManagement: {
    name: "Os Configuration Management",
    icon: "GCPOsConfigurationManagement",
  },
  gCPPermissions: { name: "Permissions", icon: "GCPPermissions" },
  gCPPolicyAnalyzer: { name: "Policy Analyzer", icon: "GCPPolicyAnalyzer" },
  gCPPersistentDisk: { name: "Persistent Disk", icon: "GCPPersistentDisk" },
  gCPPerformanceDashboard: {
    name: "Performance Dashboard",
    icon: "GCPPerformanceDashboard",
  },
  gCPPhishingProtection: {
    name: "Phishing Protection",
    icon: "GCPPhishingProtection",
  },
  gCPOnboarding: { name: "Onboarding", icon: "GCPOnboarding" },
  gCPPrivateServiceConnect: {
    name: "Private Service Connect",
    icon: "GCPPrivateServiceConnect",
  },
  gCPPremiumNetworkTier: {
    name: "Premium Network Tier",
    icon: "GCPPremiumNetworkTier",
  },
  gCPProducerPortal: { name: "Producer Portal", icon: "GCPProducerPortal" },
  gCPProfiler: { name: "Profiler", icon: "GCPProfiler" },
  gCPQuantumEngine: { name: "Quantum Engine", icon: "GCPQuantumEngine" },
  gCPPubsub: { name: "Pubsub", icon: "GCPPubsub" },
  gCPRealworldInsights: {
    name: "Real World Insights",
    icon: "GCPRealworldInsights",
  },
  gCPProject: { name: "Project", icon: "GCPProject" },
  gCPRecommendationsAi: {
    name: "Recommendations Ai",
    icon: "GCPRecommendationsAi",
  },
  gCPQuotas: { name: "Quotas", icon: "GCPQuotas" },
  gCPRetailApi: { name: "Retail Api", icon: "GCPRetailApi" },
  gCPRiskManager: { name: "Risk Manager", icon: "GCPRiskManager" },
  gCPReleaseNotes: { name: "Release Notes", icon: "GCPReleaseNotes" },
  gCPSecretManager: { name: "Secret Manager", icon: "GCPSecretManager" },
  gCPRuntimeConfig: { name: "Runtime Config", icon: "GCPRuntimeConfig" },
  gCPSecurityCommandCenter: {
    name: "Security Command Center",
    icon: "GCPSecurityCommandCenter",
  },
  gCPSecurity: { name: "Security", icon: "GCPSecurity" },
  gCPSecurityKeyEnforcement: {
    name: "Security Key Enforcement",
    icon: "GCPSecurityKeyEnforcement",
  },
  gCPSecurityHealthAdvisor: {
    name: "Security Health Advisor",
    icon: "GCPSecurityHealthAdvisor",
  },
  gCPServiceDiscovery: {
    name: "Service Discovery",
    icon: "GCPServiceDiscovery",
  },
  gCPSpeechtotext: { name: "Speech To Text", icon: "GCPSpeechtotext" },
  gCPStackdriver: { name: "Stackdriver", icon: "GCPStackdriver" },
  gCPStandardNetworkTier: {
    name: "Standard Network Tier",
    icon: "GCPStandardNetworkTier",
  },
  gCPSupport: { name: "Support", icon: "GCPSupport" },
  gCPTensorflowEnterprise: {
    name: "Tensorflow Enterprise",
    icon: "GCPTensorflowEnterprise",
  },
  gCPTexttospeech: { name: "Text To Speech", icon: "GCPTexttospeech" },
  gCPPrivateConnectivity: {
    name: "Private Connectivity",
    icon: "GCPPrivateConnectivity",
  },
  gCPToolsForPowershell: {
    name: "Tools For Powershell",
    icon: "GCPToolsForPowershell",
  },
  gCPStreamSuite: { name: "Stream Suite", icon: "GCPStreamSuite" },
  gCPTransfer: { name: "Transfer", icon: "GCPTransfer" },
  gCPTransferAppliance: {
    name: "Transfer Appliance",
    icon: "GCPTransferAppliance",
  },
  gCPVertexai: { name: "Vertexai", icon: "GCPVertexai" },
  gCPVisualInspection: {
    name: "Visual Inspection",
    icon: "GCPVisualInspection",
  },
  gCPVideoIntelligenceApi: {
    name: "Video Intelligence Api",
    icon: "GCPVideoIntelligenceApi",
  },
  gCPTrace: { name: "Trace", icon: "GCPTrace" },
  gCPTrafficDirector: { name: "Traffic Director", icon: "GCPTrafficDirector" },
  gCPUserPreferences: { name: "User Preferences", icon: "GCPUserPreferences" },
  gCPVirtualPrivateCloud: {
    name: "Virtual Private Cloud",
    icon: "GCPVirtualPrivateCloud",
  },
  gCPWebRisk: { name: "Web Risk", icon: "GCPWebRisk" },
  gCPVmwareEngine: { name: "Vmware Engine", icon: "GCPVmwareEngine" },
  gCPWebSecurityScanner: {
    name: "Web Security Scanner",
    icon: "GCPWebSecurityScanner",
  },
  gCPWorkloadIdentityPool: {
    name: "Workload Identity Pool",
    icon: "GCPWorkloadIdentityPool",
  },
  gCPWorkflows: { name: "Workflows", icon: "GCPWorkflows" },
};
