interface IconNames {
  [key: string]: string;
}

export const SkillIconNames: IconNames = {
  skillIconAbleton: "SkillIconAbleton",
  skillIconActivityPub: "SkillIconActivityPub",
  skillIconAWS: "SkillIconAWS",
  skillIconAdonis: "SkillIconAdonis",
  skillIconAfterEffects: "SkillIconAfterEffects",
  skillIconAlpineJS: "SkillIconAlpineJS",
  skillIconAndroidStudio: "SkillIconAndroidStudio",
  skillIconAngular: "SkillIconAngular",
  skillIconAnsible: "SkillIconAnsible",
  skillIconApollo: "SkillIconApollo",
  skillIconAppwrite: "SkillIconAppwrite",
  skillIconAnaconda: "SkillIconAnaconda",
  skillIconAiScript: "SkillIconAiScript",
  skillIconActix: "SkillIconActix",
  skillIconArch: "SkillIconArch",
  skillIconArduino: "SkillIconArduino",
  skillIconApple: "SkillIconApple",
  skillIconAtom: "SkillIconAtom",
  skillIconAudition: "SkillIconAudition",
  skillIconAstro: "SkillIconAstro",
  skillIconAutoCAD: "SkillIconAutoCAD",
  skillIconAzul: "SkillIconAzul",
  skillIconAzure: "SkillIconAzure",
  skillIconBitBucket: "SkillIconBitBucket",
  skillIconBash: "SkillIconBash",
  skillIconBSD: "SkillIconBSD",
  skillIconC: "SkillIconC",
  skillIconBevy: "SkillIconBevy",
  skillIconCPP: "SkillIconCPP",
  skillIconCMake: "SkillIconCMake",
  skillIconCLion: "SkillIconCLion",
  skillIconBun: "SkillIconBun",
  skillIconBabel: "SkillIconBabel",
  skillIconBlender: "SkillIconBlender",
  skillIconCSS: "SkillIconCSS",
  skillIconCloudflare: "SkillIconCloudflare",
  skillIconClojure: "SkillIconClojure",
  skillIconCoffeeScript: "SkillIconCoffeeScript",
  skillIconCodePen: "SkillIconCodePen",
  skillIconCrystal: "SkillIconCrystal",
  skillIconD3: "SkillIconD3",
  skillIconBootstrap: "SkillIconBootstrap",
  skillIconCS: "SkillIconCS",
  skillIconCypress: "SkillIconCypress",
  skillIconDiscord: "SkillIconDiscord",
  skillIconDevTo: "SkillIconDevTo",
  skillIconCassandra: "SkillIconCassandra",
  skillIconDiscordBots: "SkillIconDiscordBots",
  skillIconDENO: "SkillIconDENO",
  skillIconDart: "SkillIconDart",
  skillIconDebian: "SkillIconDebian",
  skillIconDjango: "SkillIconDjango",
  skillIconDiscordJS: "SkillIconDiscordJS",
  skillIconDotNet: "SkillIconDotNet",
  skillIconDocker: "SkillIconDocker",
  skillIconEclipse: "SkillIconEclipse",
  skillIconElectron: "SkillIconElectron",
  skillIconElixir: "SkillIconElixir",
  skillIconEmacs: "SkillIconEmacs",
  skillIconElysia: "SkillIconElysia",
  skillIconEmber: "SkillIconEmber",
  skillIconExpressJS: "SkillIconExpressJS",
  skillIconElasticsearch: "SkillIconElasticsearch",
  skillIconFediverse: "SkillIconFediverse",
  skillIconDynamoDB: "SkillIconDynamoDB",
  skillIconFlutter: "SkillIconFlutter",
  skillIconFigma: "SkillIconFigma",
  skillIconGTK: "SkillIconGTK",
  skillIconFortran: "SkillIconFortran",
  skillIconEmotion: "SkillIconEmotion",
  skillIconForth: "SkillIconForth",
  skillIconFirebase: "SkillIconFirebase",
  skillIconFlask: "SkillIconFlask",
  skillIconGCP: "SkillIconGCP",
  skillIconFastAPI: "SkillIconFastAPI",
  skillIconGherkin: "SkillIconGherkin",
  skillIconGit: "SkillIconGit",
  skillIconGameMakerStudio: "SkillIconGameMakerStudio",
  skillIconGatsby: "SkillIconGatsby",
  skillIconGoLang: "SkillIconGoLang",
  skillIconGithub: "SkillIconGithub",
  skillIconGitLab: "SkillIconGitLab",
  skillIconGmail: "SkillIconGmail",
  skillIconHTML: "SkillIconHTML",
  skillIconGodot: "SkillIconGodot",
  skillIconGraphQL: "SkillIconGraphQL",
  skillIconHaskell: "SkillIconHaskell",
  skillIconHaxe: "SkillIconHaxe",
  skillIconGithubActions: "SkillIconGithubActions",
  skillIconGulp: "SkillIconGulp",
  skillIconHeroku: "SkillIconHeroku",
  skillIconGradle: "SkillIconGradle",
  skillIconHibernate: "SkillIconHibernate",
  skillIconHtmx: "SkillIconHtmx",
  skillIconIPFS: "SkillIconIPFS",
  skillIconIdea: "SkillIconIdea",
  skillIconIllustrator: "SkillIconIllustrator",
  skillIconHaxeFlixel: "SkillIconHaxeFlixel",
  skillIconJava: "SkillIconJava",
  skillIconGrafana: "SkillIconGrafana",
  skillIconInstagram: "SkillIconInstagram",
  skillIconJenkins: "SkillIconJenkins",
  skillIconJavaScript: "SkillIconJavaScript",
  skillIconJest: "SkillIconJest",
  skillIconKtor: "SkillIconKtor",
  skillIconJQuery: "SkillIconJQuery",
  skillIconKafka: "SkillIconKafka",
  skillIconKubernetes: "SkillIconKubernetes",
  skillIconKali: "SkillIconKali",
  skillIconKotlin: "SkillIconKotlin",
  skillIconJulia: "SkillIconJulia",
  skillIconLaravel: "SkillIconLaravel",
  skillIconLinkedIn: "SkillIconLinkedIn",
  skillIconLit: "SkillIconLit",
  skillIconMatlab: "SkillIconMatlab",
  skillIconMarkdown: "SkillIconMarkdown",
  skillIconLaTeX: "SkillIconLaTeX",
  skillIconMaterialUI: "SkillIconMaterialUI",
  skillIconMastodon: "SkillIconMastodon",
  skillIconMisskey: "SkillIconMisskey",
  skillIconLinux: "SkillIconLinux",
  skillIconMongoDB: "SkillIconMongoDB",
  skillIconLess: "SkillIconLess",
  skillIconMySQL: "SkillIconMySQL",
  skillIconNeoVim: "SkillIconNeoVim",
  skillIconMint: "SkillIconMint",
  skillIconLua: "SkillIconLua",
  skillIconNginx: "SkillIconNginx",
  skillIconNim: "SkillIconNim",
  skillIconNix: "SkillIconNix",
  skillIconNotion: "SkillIconNotion",
  skillIconNetlify: "SkillIconNetlify",
  skillIconMaven: "SkillIconMaven",
  skillIconNuxtJS: "SkillIconNuxtJS",
  skillIconOCaml: "SkillIconOCaml",
  skillIconNestJS: "SkillIconNestJS",
  skillIconOpenCV: "SkillIconOpenCV",
  skillIconOctave: "SkillIconOctave",
  skillIconObsidian: "SkillIconObsidian",
  skillIconNodeJS: "SkillIconNodeJS",
  skillIconOpenShift: "SkillIconOpenShift",
  skillIconOpenStack: "SkillIconOpenStack",
  skillIconNpm: "SkillIconNpm",
  skillIconPHP: "SkillIconPHP",
  skillIconPkl: "SkillIconPkl",
  skillIconPnpm: "SkillIconPnpm",
  skillIconPinia: "SkillIconPinia",
  skillIconPhpStorm: "SkillIconPhpStorm",
  skillIconPostgreSQL: "SkillIconPostgreSQL",
  skillIconPlanetScale: "SkillIconPlanetScale",
  skillIconPhotoshop: "SkillIconPhotoshop",
  skillIconPrisma: "SkillIconPrisma",
  skillIconPowershell: "SkillIconPowershell",
  skillIconPerl: "SkillIconPerl",
  skillIconPrometheus: "SkillIconPrometheus",
  skillIconPyCharm: "SkillIconPyCharm",
  skillIconPyTorch: "SkillIconPyTorch",
  skillIconPug: "SkillIconPug",
  skillIconPostman: "SkillIconPostman",
  skillIconNextJS: "SkillIconNextJS",
  skillIconPremiere: "SkillIconPremiere",
  skillIconPlan9: "SkillIconPlan9",
  skillIconProcessing: "SkillIconProcessing",
  skillIconQT: "SkillIconQT",
  skillIconROS: "SkillIconROS",
  skillIconRails: "SkillIconRails",
  skillIconR: "SkillIconR",
  skillIconRaspberryPi: "SkillIconRaspberryPi",
  skillIconRabbitMQ: "SkillIconRabbitMQ",
  skillIconPython: "SkillIconPython",
  skillIconReactiveX: "SkillIconReactiveX",
  skillIconReact: "SkillIconReact",
  skillIconRedis: "SkillIconRedis",
  skillIconRedHat: "SkillIconRedHat",
  skillIconRemix: "SkillIconRemix",
  skillIconRegex: "SkillIconRegex",
  skillIconReplit: "SkillIconReplit",
  skillIconRider: "SkillIconRider",
  skillIconRocket: "SkillIconRocket",
  skillIconSVG: "SkillIconSVG",
  skillIconSass: "SkillIconSass",
  skillIconRobloxStudio: "SkillIconRobloxStudio",
  skillIconRuby: "SkillIconRuby",
  skillIconScala: "SkillIconScala",
  skillIconRust: "SkillIconRust",
  skillIconRollupJS: "SkillIconRollupJS",
  skillIconSentry: "SkillIconSentry",
  skillIconSequelize: "SkillIconSequelize",
  skillIconSciKitLearn: "SkillIconSciKitLearn",
  skillIconSolidity: "SkillIconSolidity",
  skillIconSelenium: "SkillIconSelenium",
  skillIconStackOverflow: "SkillIconStackOverflow",
  skillIconStyledComponents: "SkillIconStyledComponents",
  skillIconSpring: "SkillIconSpring",
  skillIconSublime: "SkillIconSublime",
  skillIconSQLite: "SkillIconSQLite",
  skillIconSwift: "SkillIconSwift",
  skillIconSvelte: "SkillIconSvelte",
  skillIconSupabase: "SkillIconSupabase",
  skillIconSketchup: "SkillIconSketchup",
  skillIconRedux: "SkillIconRedux",
  skillIconTailwindCSS: "SkillIconTailwindCSS",
  skillIconSolidJS: "SkillIconSolidJS",
  skillIconTerraform: "SkillIconTerraform",
  skillIconSymfony: "SkillIconSymfony",
  skillIconTauri: "SkillIconTauri",
  skillIconUnrealEngine: "SkillIconUnrealEngine",
  skillIconTwitter: "SkillIconTwitter",
  skillIconUnity: "SkillIconUnity",
  skillIconTensorFlow: "SkillIconTensorFlow",
  skillIconVIM: "SkillIconVIM",
  skillIconVSCodium: "SkillIconVSCodium",
  skillIconUbuntu: "SkillIconUbuntu",
  skillIconVSCode: "SkillIconVSCode",
  skillIconVercel: "SkillIconVercel",
  skillIconThreeJS: "SkillIconThreeJS",
  skillIconVite: "SkillIconVite",
  skillIconTypeScript: "SkillIconTypeScript",
  skillIconVala: "SkillIconVala",
  skillIconV: "SkillIconV",
  skillIconVitest: "SkillIconVitest",
  skillIconWebAssembly: "SkillIconWebAssembly",
  skillIconVisualStudio: "SkillIconVisualStudio",
  skillIconVueJS: "SkillIconVueJS",
  skillIconWebflow: "SkillIconWebflow",
  skillIconWindiCSS: "SkillIconWindiCSS",
  skillIconWindows: "SkillIconWindows",
  skillIconWebpack: "SkillIconWebpack",
  skillIconVuetify: "SkillIconVuetify",
  skillIconXD: "SkillIconXD",
  skillIconWordpress: "SkillIconWordpress",
  skillIconWorkers: "SkillIconWorkers",
  skillIconYarn: "SkillIconYarn",
  skillIconWebStorm: "SkillIconWebStorm",
  skillIconYew: "SkillIconYew",
  skillIconZig: "SkillIconZig",
  skillIconp5js: "SkillIconp5js",
};

export const AWSIconNames: IconNames = {
  aWSAnalyticsCleanRooms: "AWSAnalyticsCleanRooms",
  aWSAnalyticsDataExchange: "AWSAnalyticsDataExchange",
  aWSAnalyticsAthena: "AWSAnalyticsAthena",
  aWSAnalyticsCloudSearch: "AWSAnalyticsCloudSearch",
  aWSAnalyticsDataZone: "AWSAnalyticsDataZone",
  aWSAnalyticsEMR: "AWSAnalyticsEMR",
  aWSAnalyticsGlueDataBrew: "AWSAnalyticsGlueDataBrew",
  aWSAnalyticsFinSpace: "AWSAnalyticsFinSpace",
  aWSAnalyticsGlueElasticViews: "AWSAnalyticsGlueElasticViews",
  aWSAnalyticsKinesisDataStreams: "AWSAnalyticsKinesisDataStreams",
  aWSAnalyticsGlue: "AWSAnalyticsGlue",
  aWSAnalyticsKinesisDataAnalytics: "AWSAnalyticsKinesisDataAnalytics",
  aWSAnalyticsDataPipeline: "AWSAnalyticsDataPipeline",
  aWSAnalyticsKinesisVideoStreams: "AWSAnalyticsKinesisVideoStreams",
  aWSAnalyticsKinesisFirehose: "AWSAnalyticsKinesisFirehose",
  aWSAnalyticsKinesis: "AWSAnalyticsKinesis",
  aWSAnalyticsLakeFormation: "AWSAnalyticsLakeFormation",
  aWSAnalyticsManagedStreamingforApacheKafka:
    "AWSAnalyticsManagedStreamingforApacheKafka",
  aWSAnalyticsQuickSight: "AWSAnalyticsQuickSight",
  aWSAnalyticsOpenSearchService: "AWSAnalyticsOpenSearchService",
  aWSAnalyticsRedshift: "AWSAnalyticsRedshift",
  aWSAppIntegrationAPIGateway: "AWSAppIntegrationAPIGateway",
  aWSAppIntegrationAppFlow: "AWSAppIntegrationAppFlow",
  aWSAppIntegrationEventBridge: "AWSAppIntegrationEventBridge",
  aWSBlockchainQuantumLedgerDatabase: "AWSBlockchainQuantumLedgerDatabase",
  aWSBlockchainManagedBlockchain: "AWSBlockchainManagedBlockchain",
  aWSAppIntegrationAppSync: "AWSAppIntegrationAppSync",
  aWSAppIntegrationSimpleNotificationService:
    "AWSAppIntegrationSimpleNotificationService",
  aWSAppIntegrationStepFunctions: "AWSAppIntegrationStepFunctions",
  aWSAppIntegrationManagedWorkflowsforApacheAirflow:
    "AWSAppIntegrationManagedWorkflowsforApacheAirflow",
  aWSBusinessApplicationsAlexaForBusiness:
    "AWSBusinessApplicationsAlexaForBusiness",
  aWSBusinessApplicationsChimeSDK: "AWSBusinessApplicationsChimeSDK",
  aWSAppIntegrationExpressWorkflows: "AWSAppIntegrationExpressWorkflows",
  aWSAppIntegrationConsoleMobileApplication:
    "AWSAppIntegrationConsoleMobileApplication",
  aWSAppIntegrationSimpleQueueService: "AWSAppIntegrationSimpleQueueService",
  aWSBusinessApplicationsChime: "AWSBusinessApplicationsChime",
  aWSBusinessApplicationsHoneycode: "AWSBusinessApplicationsHoneycode",
  aWSAppIntegrationMQ: "AWSAppIntegrationMQ",
  aWSBusinessApplicationsConnect: "AWSBusinessApplicationsConnect",
  aWSBusinessApplicationsPinpoint: "AWSBusinessApplicationsPinpoint",
  aWSBusinessApplicationsChimeVoiceConnector:
    "AWSBusinessApplicationsChimeVoiceConnector",
  aWSBusinessApplicationsSimpleEmailService:
    "AWSBusinessApplicationsSimpleEmailService",
  aWSBusinessApplicationsWickr: "AWSBusinessApplicationsWickr",
  aWSBusinessApplicationsWorkDocsSDK: "AWSBusinessApplicationsWorkDocsSDK",
  aWSCloudFinancialManagementApplicationCostProfiler:
    "AWSCloudFinancialManagementApplicationCostProfiler",
  aWSCloudFinancialManagementBillingConductor:
    "AWSCloudFinancialManagementBillingConductor",
  aWSBusinessApplicationsWorkMail: "AWSBusinessApplicationsWorkMail",
  aWSBusinessApplicationsWorkDocs: "AWSBusinessApplicationsWorkDocs",
  aWSBusinessApplicationsSupplyChain: "AWSBusinessApplicationsSupplyChain",
  aWSBusinessApplicationsPinpointAPIs: "AWSBusinessApplicationsPinpointAPIs",
  aWSCloudFinancialManagementBudgets: "AWSCloudFinancialManagementBudgets",
  aWSCloudFinancialManagementCostandUsageReport:
    "AWSCloudFinancialManagementCostandUsageReport",
  aWSCloudFinancialManagementCostExplorer:
    "AWSCloudFinancialManagementCostExplorer",
  aWSCloudFinancialManagementReservedInstanceReporting:
    "AWSCloudFinancialManagementReservedInstanceReporting",
  aWSCloudFinancialManagementSavingsPlans:
    "AWSCloudFinancialManagementSavingsPlans",
  aWSCustomerEnablementTrainingCertification:
    "AWSCustomerEnablementTrainingCertification",
  aWSCustomerEnablementActivate: "AWSCustomerEnablementActivate",
  aWSCustomerEnablementIQ: "AWSCustomerEnablementIQ",
  aWSCustomerEnablementManagedServices: "AWSCustomerEnablementManagedServices",
  aWSComputeApplicationAutoScaling: "AWSComputeApplicationAutoScaling",
  aWSCustomerEnablementRePost: "AWSCustomerEnablementRePost",
  aWSComputeEC2AutoScaling: "AWSComputeEC2AutoScaling",
  aWSCustomerEnablementSupport: "AWSCustomerEnablementSupport",
  aWSComputeBottlerocket: "AWSComputeBottlerocket",
  aWSCustomerEnablementProfessionalServices:
    "AWSCustomerEnablementProfessionalServices",
  aWSComputeEC2ImageBuilder: "AWSComputeEC2ImageBuilder",
  aWSComputeComputeOptimizer: "AWSComputeComputeOptimizer",
  aWSComputeEC2: "AWSComputeEC2",
  aWSComputeElasticFabricAdapter: "AWSComputeElasticFabricAdapter",
  aWSComputeAppRunner: "AWSComputeAppRunner",
  aWSComputeBatch: "AWSComputeBatch",
  aWSComputeElasticBeanstalk: "AWSComputeElasticBeanstalk",
  aWSComputeLambda: "AWSComputeLambda",
  aWSComputeNICEDCV: "AWSComputeNICEDCV",
  aWSComputeNICEEnginFrame: "AWSComputeNICEEnginFrame",
  aWSComputeLocalZones: "AWSComputeLocalZones",
  aWSComputeNitroEnclaves: "AWSComputeNitroEnclaves",
  aWSComputeGenomicsCLI: "AWSComputeGenomicsCLI",
  aWSComputeFargate: "AWSComputeFargate",
  aWSComputeOutpostsfamily: "AWSComputeOutpostsfamily",
  aWSComputeSail: "AWSComputeSail",
  aWSComputeOutpostsrack: "AWSComputeOutpostsrack",
  aWSComputeOutpostsservers: "AWSComputeOutpostsservers",
  aWSComputeServerlessApplicationRepository:
    "AWSComputeServerlessApplicationRepository",
  aWSComputeThinkboxKrakatoa: "AWSComputeThinkboxKrakatoa",
  aWSComputeThinkboxDeadline: "AWSComputeThinkboxDeadline",
  aWSComputeSimSpaceWeaver: "AWSComputeSimSpaceWeaver",
  aWSComputeThinkboxStoke: "AWSComputeThinkboxStoke",
  aWSComputeThinkboxXMesh: "AWSComputeThinkboxXMesh",
  aWSComputeThinkboxSequoia: "AWSComputeThinkboxSequoia",
  aWSComputeThinkboxFrost: "AWSComputeThinkboxFrost",
  aWSComputeParallelCluster: "AWSComputeParallelCluster",
  aWSContainersEKSAnywhere: "AWSContainersEKSAnywhere",
  aWSComputeWavelength: "AWSComputeWavelength",
  aWSContainersEKSDistro: "AWSContainersEKSDistro",
  aWSContainersElasticKubernetesService:
    "AWSContainersElasticKubernetesService",
  aWSContainersFargate: "AWSContainersFargate",
  aWSComputeVMwareCloudonAWS: "AWSComputeVMwareCloudonAWS",
  aWSContainersElasticContainerRegistry:
    "AWSContainersElasticContainerRegistry",
  aWSContainersECSAnywhere: "AWSContainersECSAnywhere",
  aWSContainersEKSCloud: "AWSContainersEKSCloud",
  aWSDatabaseAurora: "AWSDatabaseAurora",
  aWSContainersRedHatOpenShiftServiceonAWS:
    "AWSContainersRedHatOpenShiftServiceonAWS",
  aWSDatabaseElastiCache: "AWSDatabaseElastiCache",
  aWSDatabaseNeptune: "AWSDatabaseNeptune",
  aWSDatabaseKeyspaces: "AWSDatabaseKeyspaces",
  aWSDatabaseDynamoDB: "AWSDatabaseDynamoDB",
  aWSDatabaseMemoryDBforRedis: "AWSDatabaseMemoryDBforRedis",
  aWSDatabaseDatabaseMigrationService: "AWSDatabaseDatabaseMigrationService",
  aWSDatabaseDocumentDB: "AWSDatabaseDocumentDB",
  aWSDatabaseRDSonVMware: "AWSDatabaseRDSonVMware",
  aWSDatabaseRDS: "AWSDatabaseRDS",
  aWSContainersElasticContainerService: "AWSContainersElasticContainerService",
  aWSFrontEndWebMobileDeviceFarm: "AWSFrontEndWebMobileDeviceFarm",
  aWSEndUserComputingAppStream: "AWSEndUserComputingAppStream",
  aWSFrontEndWebMobileAmplify: "AWSFrontEndWebMobileAmplify",
  aWSEndUserComputingWorkLink: "AWSEndUserComputingWorkLink",
  aWSDeveloperToolsApplicationComposer: "AWSDeveloperToolsApplicationComposer",
  aWSFrontEndWebMobileLocationService: "AWSFrontEndWebMobileLocationService",
  aWSDeveloperToolsCloudControlAPI: "AWSDeveloperToolsCloudControlAPI",
  aWSEndUserComputingWorkSpacesFamily: "AWSEndUserComputingWorkSpacesFamily",
  aWSDeveloperToolsCloudDevelopmentKit: "AWSDeveloperToolsCloudDevelopmentKit",
  aWSDeveloperToolsCodeArtifact: "AWSDeveloperToolsCodeArtifact",
  aWSDeveloperToolsCodeDeploy: "AWSDeveloperToolsCodeDeploy",
  aWSDeveloperToolsCloud9: "AWSDeveloperToolsCloud9",
  aWSDatabaseTimestream: "AWSDatabaseTimestream",
  aWSDeveloperToolsCodePipeline: "AWSDeveloperToolsCodePipeline",
  aWSDeveloperToolsCommandLineInterface:
    "AWSDeveloperToolsCommandLineInterface",
  aWSDeveloperToolsCodeCatalyst: "AWSDeveloperToolsCodeCatalyst",
  aWSDeveloperToolsCodeStar: "AWSDeveloperToolsCodeStar",
  aWSDeveloperToolsCloudShell: "AWSDeveloperToolsCloudShell",
  aWSDeveloperToolsCodeCommit: "AWSDeveloperToolsCodeCommit",
  aWSDeveloperToolsCorretto: "AWSDeveloperToolsCorretto",
  aWSDeveloperToolsCodeBuild: "AWSDeveloperToolsCodeBuild",
  aWSGamesGameSparks: "AWSGamesGameSparks",
  aWSGamesGameKit: "AWSGamesGameKit",
  aWSGamesGameLift: "AWSGamesGameLift",
  aWSDeveloperToolsToolsandSDKs: "AWSDeveloperToolsToolsandSDKs",
  aWSGamesOpen3DEngine: "AWSGamesOpen3DEngine",
  aWSGeneralIconsMarketplace_Dark: "AWSGeneralIconsMarketplace_Dark",
  aWSDeveloperToolsXRay: "AWSDeveloperToolsXRay",
  aWSGeneralIconsMarketplace_: "AWSGeneralIconsMarketplace_",
  aWSGamesLumberyard: "AWSGamesLumberyard",
  aWSInternetofThingsFreeRTOS: "AWSInternetofThingsFreeRTOS",
  aWSInternetofThingsIoT1Click: "AWSInternetofThingsIoT1Click",
  aWSInternetofThingsIoTEduKit: "AWSInternetofThingsIoTEduKit",
  aWSInternetofThingsIoTCore: "AWSInternetofThingsIoTCore",
  aWSInternetofThingsIoTEvents: "AWSInternetofThingsIoTEvents",
  aWSInternetofThingsIoTDeviceDefender: "AWSInternetofThingsIoTDeviceDefender",
  aWSInternetofThingsIoTFleetWise: "AWSInternetofThingsIoTFleetWise",
  aWSInternetofThingsIoTGreengrass: "AWSInternetofThingsIoTGreengrass",
  aWSInternetofThingsIoTExpressLink: "AWSInternetofThingsIoTExpressLink",
  aWSInternetofThingsIoTDeviceManagement:
    "AWSInternetofThingsIoTDeviceManagement",
  aWSInternetofThingsIoTAnalytics: "AWSInternetofThingsIoTAnalytics",
  aWSInternetofThingsIoTSiteWise: "AWSInternetofThingsIoTSiteWise",
  aWSInternetofThingsIoTButton: "AWSInternetofThingsIoTButton",
  aWSInternetofThingsIoTTwinMaker: "AWSInternetofThingsIoTTwinMaker",
  aWSMachineLearningAugmentedAIA2I: "AWSMachineLearningAugmentedAIA2I",
  aWSInternetofThingsIoTRoboRunner: "AWSInternetofThingsIoTRoboRunner",
  aWSInternetofThingsIoTThingsGraph: "AWSInternetofThingsIoTThingsGraph",
  aWSMachineLearningCodeGuru: "AWSMachineLearningCodeGuru",
  aWSMachineLearningDeepLearningAMIs: "AWSMachineLearningDeepLearningAMIs",
  aWSMachineLearningDeepLearningContainers:
    "AWSMachineLearningDeepLearningContainers",
  aWSMachineLearningComprehend: "AWSMachineLearningComprehend",
  aWSMachineLearningDeepLens: "AWSMachineLearningDeepLens",
  aWSMachineLearningDeepComposer: "AWSMachineLearningDeepComposer",
  aWSMachineLearningComprehendMedical: "AWSMachineLearningComprehendMedical",
  aWSMachineLearningCodeWhisperer: "AWSMachineLearningCodeWhisperer",
  aWSMachineLearningApacheMXNetonAWS: "AWSMachineLearningApacheMXNetonAWS",
  aWSMachineLearningDevOpsGuru: "AWSMachineLearningDevOpsGuru",
  aWSMachineLearningHealthLake: "AWSMachineLearningHealthLake",
  aWSMachineLearningLex: "AWSMachineLearningLex",
  aWSMachineLearningElasticInference: "AWSMachineLearningElasticInference",
  aWSMachineLearningLookoutforEquipment:
    "AWSMachineLearningLookoutforEquipment",
  aWSMachineLearningKendra: "AWSMachineLearningKendra",
  aWSMachineLearningLookoutforMetrics: "AWSMachineLearningLookoutforMetrics",
  aWSMachineLearningDeepRacer: "AWSMachineLearningDeepRacer",
  aWSMachineLearningFraudDetector: "AWSMachineLearningFraudDetector",
  aWSMachineLearningNeuron: "AWSMachineLearningNeuron",
  aWSMachineLearningPanorama: "AWSMachineLearningPanorama",
  aWSMachineLearningLookoutforVision: "AWSMachineLearningLookoutforVision",
  aWSMachineLearningOmics: "AWSMachineLearningOmics",
  aWSMachineLearningMonitron: "AWSMachineLearningMonitron",
  aWSMachineLearningSageMaker: "AWSMachineLearningSageMaker",
  aWSMachineLearningForecast: "AWSMachineLearningForecast",
  aWSMachineLearningPersonalize: "AWSMachineLearningPersonalize",
  aWSMachineLearningSageMakerGroundTruth:
    "AWSMachineLearningSageMakerGroundTruth",
  aWSMachineLearningTensorFlowonAWS: "AWSMachineLearningTensorFlowonAWS",
  aWSMachineLearningTranscribe: "AWSMachineLearningTranscribe",
  aWSMachineLearningTextract: "AWSMachineLearningTextract",
  aWSMachineLearningTranslate: "AWSMachineLearningTranslate",
  aWSMachineLearningPolly: "AWSMachineLearningPolly",
  aWSMachineLearningTorchServe: "AWSMachineLearningTorchServe",
  aWSMachineLearningSageMakerStudioLab: "AWSMachineLearningSageMakerStudioLab",
  aWSMigrationTransferApplicationDiscoveryService:
    "AWSMigrationTransferApplicationDiscoveryService",
  aWSMigrationTransferMigrationEvaluator:
    "AWSMigrationTransferMigrationEvaluator",
  aWSMigrationTransferDataSync: "AWSMigrationTransferDataSync",
  aWSMachineLearningRekognition: "AWSMachineLearningRekognition",
  aWSMigrationTransferMigrationHub: "AWSMigrationTransferMigrationHub",
  aWSMigrationTransferTransferFamily: "AWSMigrationTransferTransferFamily",
  aWSMigrationTransferMainframeModernization:
    "AWSMigrationTransferMainframeModernization",
  aWSMediaServicesElasticTranscoder: "AWSMediaServicesElasticTranscoder",
  aWSMediaServicesElementalAppliancesSoftware:
    "AWSMediaServicesElementalAppliancesSoftware",
  aWSMigrationTransferServerMigrationService:
    "AWSMigrationTransferServerMigrationService",
  aWSMediaServicesElementalLink: "AWSMediaServicesElementalLink",
  aWSMigrationTransferApplicationMigrationService:
    "AWSMigrationTransferApplicationMigrationService",
  aWSMediaServicesElementalDelta: "AWSMediaServicesElementalDelta",
  aWSMediaServicesElementalLive: "AWSMediaServicesElementalLive",
  aWSMediaServicesElementalMediaLive: "AWSMediaServicesElementalMediaLive",
  aWSMediaServicesElementalMediaConnect:
    "AWSMediaServicesElementalMediaConnect",
  aWSMediaServicesElementalMediaPackage:
    "AWSMediaServicesElementalMediaPackage",
  aWSMediaServicesElementalMediaTailor: "AWSMediaServicesElementalMediaTailor",
  aWSMediaServicesElementalServer: "AWSMediaServicesElementalServer",
  aWSMediaServicesElementalMediaStore: "AWSMediaServicesElementalMediaStore",
  aWSMediaServicesElementalConductor: "AWSMediaServicesElementalConductor",
  aWSMediaServicesInteractiveVideoService:
    "AWSMediaServicesInteractiveVideoService",
  aWSMediaServicesKinesisVideoStreams: "AWSMediaServicesKinesisVideoStreams",
  aWSMediaServicesElementalMediaConvert:
    "AWSMediaServicesElementalMediaConvert",
  aWSMediaServicesNimbleStudio: "AWSMediaServicesNimbleStudio",
  aWSNetworkingContentDeliveryClientVPN:
    "AWSNetworkingContentDeliveryClientVPN",
  aWSNetworkingContentDeliveryCloudDirectory:
    "AWSNetworkingContentDeliveryCloudDirectory",
  aWSQuantumTechnologiesBraket: "AWSQuantumTechnologiesBraket",
  aWSRoboticsRoboMaker: "AWSRoboticsRoboMaker",
  aWSNetworkingContentDeliveryElasticLoadBalancing:
    "AWSNetworkingContentDeliveryElasticLoadBalancing",
  aWSNetworkingContentDeliveryCloudMap: "AWSNetworkingContentDeliveryCloudMap",
  aWSNetworkingContentDeliveryCloudFront:
    "AWSNetworkingContentDeliveryCloudFront",
  aWSNetworkingContentDeliveryGlobalAccelerator:
    "AWSNetworkingContentDeliveryGlobalAccelerator",
  aWSNetworkingContentDeliveryDirectConnect:
    "AWSNetworkingContentDeliveryDirectConnect",
  aWSSatelliteGroundStation: "AWSSatelliteGroundStation",
  aWSNetworkingContentDeliveryAppMesh: "AWSNetworkingContentDeliveryAppMesh",
  aWSNetworkingContentDeliveryPrivateLink:
    "AWSNetworkingContentDeliveryPrivateLink",
  aWSNetworkingContentDeliverySitetoSiteVPN:
    "AWSNetworkingContentDeliverySitetoSiteVPN",
  aWSNetworkingContentDeliveryCloudWAN: "AWSNetworkingContentDeliveryCloudWAN",
  aWSNetworkingContentDeliveryRoute53: "AWSNetworkingContentDeliveryRoute53",
  aWSNetworkingContentDeliveryVPCLattice:
    "AWSNetworkingContentDeliveryVPCLattice",
  aWSNetworkingContentDeliveryPrivate5G:
    "AWSNetworkingContentDeliveryPrivate5G",
  aWSNetworkingContentDeliveryVerifiedAccess:
    "AWSNetworkingContentDeliveryVerifiedAccess",
  aWSNetworkingContentDeliveryTransitGateway:
    "AWSNetworkingContentDeliveryTransitGateway",
  aWSNetworkingContentDeliveryVirtualPrivateCloud:
    "AWSNetworkingContentDeliveryVirtualPrivateCloud",
  aWSManagementGovernanceAutoScaling: "AWSManagementGovernanceAutoScaling",
  aWSManagementGovernanceAppConfig: "AWSManagementGovernanceAppConfig",
  aWSManagementGovernanceBackintAgent: "AWSManagementGovernanceBackintAgent",
  aWSManagementGovernanceCloudWatch: "AWSManagementGovernanceCloudWatch",
  aWSManagementGovernanceControlTower: "AWSManagementGovernanceControlTower",
  aWSManagementGovernanceCloudFormation:
    "AWSManagementGovernanceCloudFormation",
  aWSManagementGovernanceCloudTrail: "AWSManagementGovernanceCloudTrail",
  aWSManagementGovernanceApplicationAutoScaling:
    "AWSManagementGovernanceApplicationAutoScaling",
  aWSManagementGovernanceChatbot: "AWSManagementGovernanceChatbot",
  aWSManagementGovernanceDistroforOpenTelemetry:
    "AWSManagementGovernanceDistroforOpenTelemetry",
  aWSManagementGovernanceManagedGrafana:
    "AWSManagementGovernanceManagedGrafana",
  aWSManagementGovernanceLicenseManager:
    "AWSManagementGovernanceLicenseManager",
  aWSManagementGovernanceFaultInjectionSimulator:
    "AWSManagementGovernanceFaultInjectionSimulator",
  aWSManagementGovernanceLaunchWizard: "AWSManagementGovernanceLaunchWizard",
  aWSManagementGovernanceManagedServiceforPrometheus:
    "AWSManagementGovernanceManagedServiceforPrometheus",
  aWSManagementGovernanceProton: "AWSManagementGovernanceProton",
  aWSManagementGovernanceOrganizations: "AWSManagementGovernanceOrganizations",
  aWSManagementGovernanceOpsWorks: "AWSManagementGovernanceOpsWorks",
  aWSManagementGovernanceResilienceHub: "AWSManagementGovernanceResilienceHub",
  aWSManagementGovernanceConfig: "AWSManagementGovernanceConfig",
  aWSManagementGovernanceSystemsManager:
    "AWSManagementGovernanceSystemsManager",
  aWSManagementGovernancePersonalHealthDashboard:
    "AWSManagementGovernancePersonalHealthDashboard",
  aWSManagementGovernanceServiceCatalog:
    "AWSManagementGovernanceServiceCatalog",
  aWSManagementGovernanceResourceExplorer:
    "AWSManagementGovernanceResourceExplorer",
  aWSManagementGovernanceServiceManagementConnector:
    "AWSManagementGovernanceServiceManagementConnector",
  aWSManagementGovernanceWellArchitectedTool:
    "AWSManagementGovernanceWellArchitectedTool",
  aWSManagementGovernanceTrustedAdvisor:
    "AWSManagementGovernanceTrustedAdvisor",
  aWSStorageBackup: "AWSStorageBackup",
  aWSVRARSumerian: "AWSVRARSumerian",
  aWSManagementGovernanceManagementConsole:
    "AWSManagementGovernanceManagementConsole",
  aWSStorageEFS: "AWSStorageEFS",
  aWSStorageElasticDisasterRecovery: "AWSStorageElasticDisasterRecovery",
  aWSStorageFSxforLustre: "AWSStorageFSxforLustre",
  aWSStorageFSxforNetAppONTAP: "AWSStorageFSxforNetAppONTAP",
  aWSStorageElasticBlockStore: "AWSStorageElasticBlockStore",
  aWSStorageFSxforOpenZFS: "AWSStorageFSxforOpenZFS",
  aWSStorageFileCache: "AWSStorageFileCache",
  aWSStorageS3onOutposts: "AWSStorageS3onOutposts",
  aWSStorageFSxforWFS: "AWSStorageFSxforWFS",
  aWSStorageFSx: "AWSStorageFSx",
  aWSStorageSnowballEdge: "AWSStorageSnowballEdge",
  aWSStorageStorageGateway: "AWSStorageStorageGateway",
  aWSStorageSnowmobile: "AWSStorageSnowmobile",
  aWSStorageSnowcone: "AWSStorageSnowcone",
  aWSSecurityIdentityComplianceCloudDirectory:
    "AWSSecurityIdentityComplianceCloudDirectory",
  aWSStorageSnowball: "AWSStorageSnowball",
  aWSSecurityIdentityComplianceCertificateManager:
    "AWSSecurityIdentityComplianceCertificateManager",
  aWSSecurityIdentityComplianceCognito: "AWSSecurityIdentityComplianceCognito",
  aWSStorageSimpleStorageService: "AWSStorageSimpleStorageService",
  aWSSecurityIdentityComplianceAuditManager:
    "AWSSecurityIdentityComplianceAuditManager",
  aWSStorageSimpleStorageServiceGlacier:
    "AWSStorageSimpleStorageServiceGlacier",
  aWSSecurityIdentityComplianceDetective:
    "AWSSecurityIdentityComplianceDetective",
  aWSSecurityIdentityComplianceArtifact:
    "AWSSecurityIdentityComplianceArtifact",
  aWSSecurityIdentityComplianceDirectoryService:
    "AWSSecurityIdentityComplianceDirectoryService",
  aWSSecurityIdentityComplianceIAMIdentityCenter:
    "AWSSecurityIdentityComplianceIAMIdentityCenter",
  aWSSecurityIdentityComplianceFirewallManager:
    "AWSSecurityIdentityComplianceFirewallManager",
  aWSSecurityIdentityComplianceIdentityandAccessManagement:
    "AWSSecurityIdentityComplianceIdentityandAccessManagement",
  aWSSecurityIdentityComplianceGuardDuty:
    "AWSSecurityIdentityComplianceGuardDuty",
  aWSSecurityIdentityComplianceInspector:
    "AWSSecurityIdentityComplianceInspector",
  aWSSecurityIdentityComplianceCloudHSM:
    "AWSSecurityIdentityComplianceCloudHSM",
  aWSSecurityIdentityComplianceResourceAccessManager:
    "AWSSecurityIdentityComplianceResourceAccessManager",
  aWSSecurityIdentityComplianceNetworkFirewall:
    "AWSSecurityIdentityComplianceNetworkFirewall",
  aWSSecurityIdentityComplianceSecretsManager:
    "AWSSecurityIdentityComplianceSecretsManager",
  aWSSecurityIdentityComplianceKeyManagementService:
    "AWSSecurityIdentityComplianceKeyManagementService",
  aWSSecurityIdentityComplianceMacie: "AWSSecurityIdentityComplianceMacie",
  aWSSecurityIdentityComplianceSecurityHub:
    "AWSSecurityIdentityComplianceSecurityHub",
  aWSSecurityIdentityComplianceShield: "AWSSecurityIdentityComplianceShield",
  aWSSecurityIdentityCompliancePrivateCertificateAuthority:
    "AWSSecurityIdentityCompliancePrivateCertificateAuthority",
  aWSSecurityIdentityComplianceSecurityLake:
    "AWSSecurityIdentityComplianceSecurityLake",
  aWSSecurityIdentityComplianceSigner: "AWSSecurityIdentityComplianceSigner",
  aWSSecurityIdentityComplianceVerifiedPermissions:
    "AWSSecurityIdentityComplianceVerifiedPermissions",
  aWSSecurityIdentityComplianceWAF: "AWSSecurityIdentityComplianceWAF",
};

export const SkillIcons = {
  skillIconActivityPub: {
    name: "Activity Pub",
    icon: "SkillIconActivityPub",
  },
  skillIconAbleton: { name: "Ableton", icon: "SkillIconAbleton" },
  skillIconAWS: { name: "AWS", icon: "SkillIconAWS" },
  skillIconAfterEffects: {
    name: "After Effects",
    icon: "SkillIconAfterEffects",
  },
  skillIconAndroidStudio: {
    name: "Android Studio",
    icon: "SkillIconAndroidStudio",
  },
  skillIconAlpineJS: { name: "Alpine JS", icon: "SkillIconAlpineJS" },
  skillIconAngular: { name: "Angular", icon: "SkillIconAngular" },
  skillIconAnaconda: { name: "Anaconda", icon: "SkillIconAnaconda" },
  skillIconAiScript: { name: "Ai Script", icon: "SkillIconAiScript" },
  skillIconAnsible: { name: "Ansible", icon: "SkillIconAnsible" },
  skillIconAppwrite: { name: "Appwrite", icon: "SkillIconAppwrite" },
  skillIconActix: { name: "Actix", icon: "SkillIconActix" },
  skillIconAstro: { name: "Astro", icon: "SkillIconAstro" },
  skillIconApple: { name: "Apple", icon: "SkillIconApple" },
  skillIconArduino: { name: "Arduino", icon: "SkillIconArduino" },
  skillIconApollo: { name: "Apollo", icon: "SkillIconApollo" },
  skillIconAzul: { name: "Azul", icon: "SkillIconAzul" },
  skillIconAudition: { name: "Audition", icon: "SkillIconAudition" },
  skillIconAdonis: { name: "Adonis", icon: "SkillIconAdonis" },
  skillIconAzure: { name: "Azure", icon: "SkillIconAzure" },
  skillIconAutoCAD: { name: "Auto CAD", icon: "SkillIconAutoCAD" },
  skillIconBlender: { name: "Blender", icon: "SkillIconBlender" },
  skillIconArch: { name: "Arch", icon: "SkillIconArch" },
  skillIconBash: { name: "Bash", icon: "SkillIconBash" },
  skillIconBevy: { name: "Bevy", icon: "SkillIconBevy" },
  skillIconBootstrap: { name: "Bootstrap", icon: "SkillIconBootstrap" },
  skillIconBSD: { name: "BSD", icon: "SkillIconBSD" },
  skillIconCLion: { name: "CLion", icon: "SkillIconCLion" },
  skillIconBun: { name: "Bun", icon: "SkillIconBun" },
  skillIconC: { name: "C", icon: "SkillIconC" },
  skillIconBitBucket: { name: "Bit Bucket", icon: "SkillIconBitBucket" },
  skillIconCMake: { name: "CMake", icon: "SkillIconCMake" },
  skillIconAtom: { name: "Atom", icon: "SkillIconAtom" },
  skillIconCSS: { name: "CSS", icon: "SkillIconCSS" },
  skillIconCPP: { name: "CPP", icon: "SkillIconCPP" },
  skillIconCS: { name: "CS", icon: "SkillIconCS" },
  skillIconCloudflare: {
    name: "Cloudflare",
    icon: "SkillIconCloudflare",
  },
  skillIconClojure: { name: "Clojure", icon: "SkillIconClojure" },
  skillIconCodePen: { name: "Code Pen", icon: "SkillIconCodePen" },
  skillIconCassandra: { name: "Cassandra", icon: "SkillIconCassandra" },
  skillIconCrystal: { name: "Crystal", icon: "SkillIconCrystal" },
  skillIconDart: { name: "Dart", icon: "SkillIconDart" },
  skillIconCypress: { name: "Cypress", icon: "SkillIconCypress" },
  skillIconDENO: { name: "DENO", icon: "SkillIconDENO" },
  skillIconCoffeeScript: {
    name: "Coffee Script",
    icon: "SkillIconCoffeeScript",
  },
  skillIconD3: { name: "D3", icon: "SkillIconD3" },
  skillIconDevTo: { name: "Dev To", icon: "SkillIconDevTo" },
  skillIconDiscord: { name: "Discord", icon: "SkillIconDiscord" },
  skillIconDiscordJS: { name: "Discord JS", icon: "SkillIconDiscordJS" },
  skillIconDjango: { name: "Django", icon: "SkillIconDjango" },
  skillIconBabel: { name: "Babel", icon: "SkillIconBabel" },
  skillIconDiscordBots: {
    name: "Discord Bots",
    icon: "SkillIconDiscordBots",
  },
  skillIconDotNet: { name: "Dot Net", icon: "SkillIconDotNet" },
  skillIconDynamoDB: { name: "Dynamo DB", icon: "SkillIconDynamoDB" },
  skillIconDocker: { name: "Docker", icon: "SkillIconDocker" },
  skillIconElixir: { name: "Elixir", icon: "SkillIconElixir" },
  skillIconDebian: { name: "Debian", icon: "SkillIconDebian" },
  skillIconElasticsearch: {
    name: "Elasticsearch",
    icon: "SkillIconElasticsearch",
  },
  skillIconEmacs: { name: "Emacs", icon: "SkillIconEmacs" },
  skillIconElysia: { name: "Elysia", icon: "SkillIconElysia" },
  skillIconFastAPI: { name: "Fast API", icon: "SkillIconFastAPI" },
  skillIconElectron: { name: "Electron", icon: "SkillIconElectron" },
  skillIconEclipse: { name: "Eclipse", icon: "SkillIconEclipse" },
  skillIconEmber: { name: "Ember", icon: "SkillIconEmber" },
  skillIconFlutter: { name: "Flutter", icon: "SkillIconFlutter" },
  skillIconFediverse: { name: "Fediverse", icon: "SkillIconFediverse" },
  skillIconFortran: { name: "Fortran", icon: "SkillIconFortran" },
  skillIconExpressJS: { name: "Express JS", icon: "SkillIconExpressJS" },
  skillIconEmotion: { name: "Emotion", icon: "SkillIconEmotion" },
  skillIconGTK: { name: "GTK", icon: "SkillIconGTK" },
  skillIconFirebase: { name: "Firebase", icon: "SkillIconFirebase" },
  skillIconFigma: { name: "Figma", icon: "SkillIconFigma" },
  skillIconGCP: { name: "GCP", icon: "SkillIconGCP" },
  skillIconGherkin: { name: "Gherkin", icon: "SkillIconGherkin" },
  skillIconGit: { name: "Git", icon: "SkillIconGit" },
  skillIconGameMakerStudio: {
    name: "Game Maker Studio",
    icon: "SkillIconGameMakerStudio",
  },
  skillIconGithub: { name: "Github", icon: "SkillIconGithub" },
  skillIconGithubActions: {
    name: "Github Actions",
    icon: "SkillIconGithubActions",
  },
  skillIconFlask: { name: "Flask", icon: "SkillIconFlask" },
  skillIconGoLang: { name: "Go Lang", icon: "SkillIconGoLang" },
  skillIconGmail: { name: "Gmail", icon: "SkillIconGmail" },
  skillIconForth: { name: "Forth", icon: "SkillIconForth" },
  skillIconGraphQL: { name: "Graph QL", icon: "SkillIconGraphQL" },
  skillIconGitLab: { name: "Git Lab", icon: "SkillIconGitLab" },
  skillIconGatsby: { name: "Gatsby", icon: "SkillIconGatsby" },
  skillIconGulp: { name: "Gulp", icon: "SkillIconGulp" },
  skillIconHaxe: { name: "Haxe", icon: "SkillIconHaxe" },
  skillIconHaskell: { name: "Haskell", icon: "SkillIconHaskell" },
  skillIconHTML: { name: "HTML", icon: "SkillIconHTML" },
  skillIconGrafana: { name: "Grafana", icon: "SkillIconGrafana" },
  skillIconHeroku: { name: "Heroku", icon: "SkillIconHeroku" },
  skillIconHaxeFlixel: {
    name: "Haxe Flixel",
    icon: "SkillIconHaxeFlixel",
  },
  skillIconHibernate: { name: "Hibernate", icon: "SkillIconHibernate" },
  skillIconGradle: { name: "Gradle", icon: "SkillIconGradle" },
  skillIconHtmx: { name: "Htmx", icon: "SkillIconHtmx" },
  skillIconGodot: { name: "Godot", icon: "SkillIconGodot" },
  skillIconIPFS: { name: "IPFS", icon: "SkillIconIPFS" },
  skillIconIdea: { name: "Idea", icon: "SkillIconIdea" },
  skillIconInstagram: { name: "Instagram", icon: "SkillIconInstagram" },
  skillIconJava: { name: "Java", icon: "SkillIconJava" },
  skillIconIllustrator: {
    name: "Illustrator",
    icon: "SkillIconIllustrator",
  },
  skillIconJenkins: { name: "Jenkins", icon: "SkillIconJenkins" },
  skillIconJest: { name: "Jest", icon: "SkillIconJest" },
  skillIconJQuery: { name: "JQuery", icon: "SkillIconJQuery" },
  skillIconJavaScript: {
    name: "Java Script",
    icon: "SkillIconJavaScript",
  },
  skillIconKubernetes: {
    name: "Kubernetes",
    icon: "SkillIconKubernetes",
  },
  skillIconKotlin: { name: "Kotlin", icon: "SkillIconKotlin" },
  skillIconLaravel: { name: "Laravel", icon: "SkillIconLaravel" },
  skillIconLinkedIn: { name: "Linked In", icon: "SkillIconLinkedIn" },
  skillIconKali: { name: "Kali", icon: "SkillIconKali" },
  skillIconKafka: { name: "Kafka", icon: "SkillIconKafka" },
  skillIconLit: { name: "Lit", icon: "SkillIconLit" },
  skillIconMarkdown: { name: "Markdown", icon: "SkillIconMarkdown" },
  skillIconJulia: { name: "Julia", icon: "SkillIconJulia" },
  skillIconLaTeX: { name: "LaTeX", icon: "SkillIconLaTeX" },
  skillIconLua: { name: "Lua", icon: "SkillIconLua" },
  skillIconMastodon: { name: "Mastodon", icon: "SkillIconMastodon" },
  skillIconLess: { name: "Less", icon: "SkillIconLess" },
  skillIconMatlab: { name: "Matlab", icon: "SkillIconMatlab" },
  skillIconMisskey: { name: "Misskey", icon: "SkillIconMisskey" },
  skillIconMaterialUI: {
    name: "Material UI",
    icon: "SkillIconMaterialUI",
  },
  skillIconMongoDB: { name: "Mongo DB", icon: "SkillIconMongoDB" },
  skillIconKtor: { name: "Ktor", icon: "SkillIconKtor" },
  skillIconMint: { name: "Mint", icon: "SkillIconMint" },
  skillIconLinux: { name: "Linux", icon: "SkillIconLinux" },
  skillIconMySQL: { name: "My SQL", icon: "SkillIconMySQL" },
  skillIconMaven: { name: "Maven", icon: "SkillIconMaven" },
  skillIconNeoVim: { name: "Neo Vim", icon: "SkillIconNeoVim" },
  skillIconNim: { name: "Nim", icon: "SkillIconNim" },
  skillIconNextJS: { name: "Next JS", icon: "SkillIconNextJS" },
  skillIconNix: { name: "Nix", icon: "SkillIconNix" },
  skillIconNginx: { name: "Nginx", icon: "SkillIconNginx" },
  skillIconNestJS: { name: "Nest JS", icon: "SkillIconNestJS" },
  skillIconNpm: { name: "Npm", icon: "SkillIconNpm" },
  skillIconNetlify: { name: "Netlify", icon: "SkillIconNetlify" },
  skillIconNuxtJS: { name: "Nuxt JS", icon: "SkillIconNuxtJS" },
  skillIconNodeJS: { name: "Node JS", icon: "SkillIconNodeJS" },
  skillIconNotion: { name: "Notion", icon: "SkillIconNotion" },
  skillIconOpenCV: { name: "Open CV", icon: "SkillIconOpenCV" },
  skillIconOctave: { name: "Octave", icon: "SkillIconOctave" },
  skillIconPHP: { name: "PHP", icon: "SkillIconPHP" },
  skillIconOpenStack: { name: "Open Stack", icon: "SkillIconOpenStack" },
  skillIconPhotoshop: { name: "Photoshop", icon: "SkillIconPhotoshop" },
  skillIconOpenShift: { name: "Open Shift", icon: "SkillIconOpenShift" },
  skillIconPhpStorm: { name: "Php Storm", icon: "SkillIconPhpStorm" },
  skillIconPkl: { name: "Pkl", icon: "SkillIconPkl" },
  skillIconObsidian: { name: "Obsidian", icon: "SkillIconObsidian" },
  skillIconPinia: { name: "Pinia", icon: "SkillIconPinia" },
  skillIconPnpm: { name: "Pnpm", icon: "SkillIconPnpm" },
  skillIconPostgreSQL: {
    name: "Postgre SQL",
    icon: "SkillIconPostgreSQL",
  },
  skillIconPerl: { name: "Perl", icon: "SkillIconPerl" },
  skillIconPlan9: { name: "Plan9", icon: "SkillIconPlan9" },
  skillIconPowershell: {
    name: "Powershell",
    icon: "SkillIconPowershell",
  },
  skillIconOCaml: { name: "OCaml", icon: "SkillIconOCaml" },
  skillIconPrisma: { name: "Prisma", icon: "SkillIconPrisma" },
  skillIconPremiere: { name: "Premiere", icon: "SkillIconPremiere" },
  skillIconPyCharm: { name: "Py Charm", icon: "SkillIconPyCharm" },
  skillIconProcessing: {
    name: "Processing",
    icon: "SkillIconProcessing",
  },
  skillIconPlanetScale: {
    name: "Planet Scale",
    icon: "SkillIconPlanetScale",
  },
  skillIconR: { name: "R", icon: "SkillIconR" },
  skillIconPrometheus: {
    name: "Prometheus",
    icon: "SkillIconPrometheus",
  },
  skillIconPostman: { name: "Postman", icon: "SkillIconPostman" },
  skillIconPyTorch: { name: "Py Torch", icon: "SkillIconPyTorch" },
  skillIconRails: { name: "Rails", icon: "SkillIconRails" },
  skillIconPug: { name: "Pug", icon: "SkillIconPug" },
  skillIconPython: { name: "Python", icon: "SkillIconPython" },
  skillIconROS: { name: "ROS", icon: "SkillIconROS" },
  skillIconQT: { name: "QT", icon: "SkillIconQT" },
  skillIconRedis: { name: "Redis", icon: "SkillIconRedis" },
  skillIconRabbitMQ: { name: "Rabbit MQ", icon: "SkillIconRabbitMQ" },
  skillIconReactiveX: { name: "Reactive X", icon: "SkillIconReactiveX" },
  skillIconRaspberryPi: {
    name: "Raspberry Pi",
    icon: "SkillIconRaspberryPi",
  },
  skillIconReact: { name: "React", icon: "SkillIconReact" },
  skillIconReplit: { name: "Replit", icon: "SkillIconReplit" },
  skillIconRemix: { name: "Remix", icon: "SkillIconRemix" },
  skillIconRedHat: { name: "Red Hat", icon: "SkillIconRedHat" },
  skillIconRust: { name: "Rust", icon: "SkillIconRust" },
  skillIconRocket: { name: "Rocket", icon: "SkillIconRocket" },
  skillIconRider: { name: "Rider", icon: "SkillIconRider" },
  skillIconRollupJS: { name: "Rollup JS", icon: "SkillIconRollupJS" },
  skillIconSVG: { name: "SVG", icon: "SkillIconSVG" },
  skillIconRegex: { name: "Regex", icon: "SkillIconRegex" },
  skillIconSQLite: { name: "SQLite", icon: "SkillIconSQLite" },
  skillIconRuby: { name: "Ruby", icon: "SkillIconRuby" },
  skillIconSentry: { name: "Sentry", icon: "SkillIconSentry" },
  skillIconSketchup: { name: "Sketchup", icon: "SkillIconSketchup" },
  skillIconSciKitLearn: {
    name: "Sci Kit Learn",
    icon: "SkillIconSciKitLearn",
  },
  skillIconSass: { name: "Sass", icon: "SkillIconSass" },
  skillIconSolidJS: { name: "Solid JS", icon: "SkillIconSolidJS" },
  skillIconSelenium: { name: "Selenium", icon: "SkillIconSelenium" },
  skillIconRobloxStudio: {
    name: "Roblox Studio",
    icon: "SkillIconRobloxStudio",
  },
  skillIconSequelize: { name: "Sequelize", icon: "SkillIconSequelize" },
  skillIconStackOverflow: {
    name: "Stack Overflow",
    icon: "SkillIconStackOverflow",
  },
  skillIconScala: { name: "Scala", icon: "SkillIconScala" },
  skillIconSolidity: { name: "Solidity", icon: "SkillIconSolidity" },
  skillIconRedux: { name: "Redux", icon: "SkillIconRedux" },
  skillIconSupabase: { name: "Supabase", icon: "SkillIconSupabase" },
  skillIconSpring: { name: "Spring", icon: "SkillIconSpring" },
  skillIconSwift: { name: "Swift", icon: "SkillIconSwift" },
  skillIconTauri: { name: "Tauri", icon: "SkillIconTauri" },
  skillIconTerraform: { name: "Terraform", icon: "SkillIconTerraform" },
  skillIconSublime: { name: "Sublime", icon: "SkillIconSublime" },
  skillIconSvelte: { name: "Svelte", icon: "SkillIconSvelte" },
  skillIconTailwindCSS: {
    name: "Tailwind CSS",
    icon: "SkillIconTailwindCSS",
  },
  skillIconThreeJS: { name: "Three JS", icon: "SkillIconThreeJS" },
  skillIconSymfony: { name: "Symfony", icon: "SkillIconSymfony" },
  skillIconTypeScript: {
    name: "Type Script",
    icon: "SkillIconTypeScript",
  },
  skillIconTwitter: { name: "Twitter", icon: "SkillIconTwitter" },
  skillIconUbuntu: { name: "Ubuntu", icon: "SkillIconUbuntu" },
  skillIconStyledComponents: {
    name: "Styled Components",
    icon: "SkillIconStyledComponents",
  },
  skillIconVSCode: { name: "VS Code", icon: "SkillIconVSCode" },
  skillIconVSCodium: { name: "VS Codium", icon: "SkillIconVSCodium" },
  skillIconVIM: { name: "VIM", icon: "SkillIconVIM" },
  skillIconUnrealEngine: {
    name: "Unreal Engine",
    icon: "SkillIconUnrealEngine",
  },
  skillIconVala: { name: "Vala", icon: "SkillIconVala" },
  skillIconV: { name: "V", icon: "SkillIconV" },
  skillIconVitest: { name: "Vitest", icon: "SkillIconVitest" },
  skillIconVercel: { name: "Vercel", icon: "SkillIconVercel" },
  skillIconVueJS: { name: "Vue JS", icon: "SkillIconVueJS" },
  skillIconWebAssembly: {
    name: "Web Assembly",
    icon: "SkillIconWebAssembly",
  },
  skillIconWebStorm: { name: "Web Storm", icon: "SkillIconWebStorm" },
  skillIconWindiCSS: { name: "Windi CSS", icon: "SkillIconWindiCSS" },
  skillIconWebpack: { name: "Webpack", icon: "SkillIconWebpack" },
  skillIconWindows: { name: "Windows", icon: "SkillIconWindows" },
  skillIconVisualStudio: {
    name: "Visual Studio",
    icon: "SkillIconVisualStudio",
  },
  skillIconWordpress: { name: "Wordpress", icon: "SkillIconWordpress" },
  skillIconTensorFlow: {
    name: "Tensor Flow",
    icon: "SkillIconTensorFlow",
  },
  skillIconWorkers: { name: "Workers", icon: "SkillIconWorkers" },
  skillIconYarn: { name: "Yarn", icon: "SkillIconYarn" },
  skillIconWebflow: { name: "Webflow", icon: "SkillIconWebflow" },
  skillIconUnity: { name: "Unity", icon: "SkillIconUnity" },
  skillIconXD: { name: "XD", icon: "SkillIconXD" },
  skillIconVite: { name: "Vite", icon: "SkillIconVite" },
  skillIconZig: { name: "Zig", icon: "SkillIconZig" },
  skillIconVuetify: { name: "Vuetify", icon: "SkillIconVuetify" },
  skillIconYew: { name: "Yew", icon: "SkillIconYew" },
  skillIconp5js: { name: "P5js", icon: "SkillIconp5js" },
};

export const AwsIcons = {
  aWSAppIntegrationAPIGateway: {
    name: "API Gateway",
    icon: "AWSAppIntegrationAPIGateway",
  },
  aWSAppIntegrationAppFlow: {
    name: "App Flow",
    icon: "AWSAppIntegrationAppFlow",
  },
  aWSAppIntegrationEventBridge: {
    name: "Event Bridge",
    icon: "AWSAppIntegrationEventBridge",
  },
  aWSAppIntegrationConsoleMobileApplication: {
    name: "Console Mobile Application",
    icon: "AWSAppIntegrationConsoleMobileApplication",
  },
  aWSAppIntegrationExpressWorkflows: {
    name: "Express Workflows",
    icon: "AWSAppIntegrationExpressWorkflows",
  },
  aWSAppIntegrationAppSync: {
    name: "App Sync",
    icon: "AWSAppIntegrationAppSync",
  },
  aWSAppIntegrationManagedWorkflowsforApacheAirflow: {
    name: "Managed Workflows for Apache Airflow",
    icon: "AWSAppIntegrationManagedWorkflowsforApacheAirflow",
  },
  aWSAppIntegrationMQ: { name: "MQ", icon: "AWSAppIntegrationMQ" },
  aWSAppIntegrationSimpleQueueService: {
    name: "Simple Queue Service",
    icon: "AWSAppIntegrationSimpleQueueService",
  },
  aWSAppIntegrationStepFunctions: {
    name: "Step Functions",
    icon: "AWSAppIntegrationStepFunctions",
  },
  aWSAppIntegrationSimpleNotificationService: {
    name: "Simple Notification Service",
    icon: "AWSAppIntegrationSimpleNotificationService",
  },
  aWSBusinessApplicationsChimeSDK: {
    name: "Chime SDK",
    icon: "AWSBusinessApplicationsChimeSDK",
  },
  aWSBusinessApplicationsChimeVoiceConnector: {
    name: "Chime Voice Connector",
    icon: "AWSBusinessApplicationsChimeVoiceConnector",
  },
  aWSBusinessApplicationsChime: {
    name: "Chime",
    icon: "AWSBusinessApplicationsChime",
  },
  aWSBusinessApplicationsPinpointAPIs: {
    name: "Pinpoint APIs",
    icon: "AWSBusinessApplicationsPinpointAPIs",
  },
  aWSBusinessApplicationsConnect: {
    name: "Connect",
    icon: "AWSBusinessApplicationsConnect",
  },
  aWSBusinessApplicationsPinpoint: {
    name: "Pinpoint",
    icon: "AWSBusinessApplicationsPinpoint",
  },
  aWSBusinessApplicationsSimpleEmailService: {
    name: "Simple Email Service",
    icon: "AWSBusinessApplicationsSimpleEmailService",
  },
  aWSBusinessApplicationsWickr: {
    name: "Wickr",
    icon: "AWSBusinessApplicationsWickr",
  },
  aWSBusinessApplicationsWorkDocsSDK: {
    name: "Work Docs SDK",
    icon: "AWSBusinessApplicationsWorkDocsSDK",
  },
  aWSBusinessApplicationsSupplyChain: {
    name: "Supply Chain",
    icon: "AWSBusinessApplicationsSupplyChain",
  },
  aWSBusinessApplicationsWorkDocs: {
    name: "Work Docs",
    icon: "AWSBusinessApplicationsWorkDocs",
  },
  aWSAnalyticsAthena: { name: "Athena", icon: "AWSAnalyticsAthena" },
  aWSBusinessApplicationsWorkMail: {
    name: "Work Mail",
    icon: "AWSBusinessApplicationsWorkMail",
  },
  aWSAnalyticsDataZone: { name: "Data Zone", icon: "AWSAnalyticsDataZone" },
  aWSAnalyticsDataPipeline: {
    name: "Data Pipeline",
    icon: "AWSAnalyticsDataPipeline",
  },
  aWSBusinessApplicationsAlexaForBusiness: {
    name: "Alexa For Business",
    icon: "AWSBusinessApplicationsAlexaForBusiness",
  },
  aWSAnalyticsCleanRooms: {
    name: "Clean Rooms",
    icon: "AWSAnalyticsCleanRooms",
  },
  aWSAnalyticsCloudSearch: {
    name: "Cloud Search",
    icon: "AWSAnalyticsCloudSearch",
  },
  aWSAnalyticsDataExchange: {
    name: "Data Exchange",
    icon: "AWSAnalyticsDataExchange",
  },
  aWSAnalyticsGlueDataBrew: {
    name: "Glue Data Brew",
    icon: "AWSAnalyticsGlueDataBrew",
  },
  aWSAnalyticsGlue: { name: "Glue", icon: "AWSAnalyticsGlue" },
  aWSAnalyticsKinesisDataAnalytics: {
    name: "Kinesis Data Analytics",
    icon: "AWSAnalyticsKinesisDataAnalytics",
  },
  aWSAnalyticsKinesisFirehose: {
    name: "Kinesis Firehose",
    icon: "AWSAnalyticsKinesisFirehose",
  },
  aWSAnalyticsKinesisVideoStreams: {
    name: "Kinesis Video Streams",
    icon: "AWSAnalyticsKinesisVideoStreams",
  },
  aWSAnalyticsKinesis: { name: "Kinesis", icon: "AWSAnalyticsKinesis" },
  aWSAnalyticsLakeFormation: {
    name: "Lake Formation",
    icon: "AWSAnalyticsLakeFormation",
  },
  aWSAnalyticsFinSpace: { name: "Fin Space", icon: "AWSAnalyticsFinSpace" },
  aWSAnalyticsManagedStreamingforApacheKafka: {
    name: "Managed Streaming for Apache Kafka",
    icon: "AWSAnalyticsManagedStreamingforApacheKafka",
  },
  aWSAnalyticsRedshift: { name: "Redshift", icon: "AWSAnalyticsRedshift" },
  aWSCloudFinancialManagementApplicationCostProfiler: {
    name: "Application Cost Profiler",
    icon: "AWSCloudFinancialManagementApplicationCostProfiler",
  },
  aWSCloudFinancialManagementBillingConductor: {
    name: "Billing Conductor",
    icon: "AWSCloudFinancialManagementBillingConductor",
  },
  aWSCloudFinancialManagementCostandUsageReport: {
    name: "Cost and Usage Report",
    icon: "AWSCloudFinancialManagementCostandUsageReport",
  },
  aWSCloudFinancialManagementCostExplorer: {
    name: "Cost Explorer",
    icon: "AWSCloudFinancialManagementCostExplorer",
  },
  aWSAnalyticsOpenSearchService: {
    name: "Open Search Service",
    icon: "AWSAnalyticsOpenSearchService",
  },
  aWSCloudFinancialManagementSavingsPlans: {
    name: "Savings Plans",
    icon: "AWSCloudFinancialManagementSavingsPlans",
  },
  aWSAnalyticsKinesisDataStreams: {
    name: "Kinesis Data Streams",
    icon: "AWSAnalyticsKinesisDataStreams",
  },
  aWSAnalyticsGlueElasticViews: {
    name: "Glue Elastic Views",
    icon: "AWSAnalyticsGlueElasticViews",
  },
  aWSCloudFinancialManagementReservedInstanceReporting: {
    name: "Reserved Instance Reporting",
    icon: "AWSCloudFinancialManagementReservedInstanceReporting",
  },
  aWSBlockchainManagedBlockchain: {
    name: "Managed Blockchain",
    icon: "AWSBlockchainManagedBlockchain",
  },
  aWSBlockchainQuantumLedgerDatabase: {
    name: "Quantum Ledger Database",
    icon: "AWSBlockchainQuantumLedgerDatabase",
  },
  aWSComputeApplicationAutoScaling: {
    name: "Application Auto Scaling",
    icon: "AWSComputeApplicationAutoScaling",
  },
  aWSComputeBottlerocket: {
    name: "Bottlerocket",
    icon: "AWSComputeBottlerocket",
  },
  aWSCloudFinancialManagementBudgets: {
    name: "Budgets",
    icon: "AWSCloudFinancialManagementBudgets",
  },
  aWSComputeComputeOptimizer: {
    name: "Compute Optimizer",
    icon: "AWSComputeComputeOptimizer",
  },
  aWSComputeEC2ImageBuilder: {
    name: "EC2 Image Builder",
    icon: "AWSComputeEC2ImageBuilder",
  },
  aWSComputeEC2AutoScaling: {
    name: "EC2 Auto Scaling",
    icon: "AWSComputeEC2AutoScaling",
  },
  aWSComputeEC2: { name: "EC2", icon: "AWSComputeEC2" },
  aWSComputeGenomicsCLI: {
    name: "Genomics CLI",
    icon: "AWSComputeGenomicsCLI",
  },
  aWSBusinessApplicationsHoneycode: {
    name: "Honeycode",
    icon: "AWSBusinessApplicationsHoneycode",
  },
  aWSComputeElasticFabricAdapter: {
    name: "Elastic Fabric Adapter",
    icon: "AWSComputeElasticFabricAdapter",
  },
  aWSComputeLocalZones: { name: "Local Zones", icon: "AWSComputeLocalZones" },
  aWSComputeLambda: { name: "Lambda", icon: "AWSComputeLambda" },
  aWSComputeAppRunner: { name: "App Runner", icon: "AWSComputeAppRunner" },
  aWSComputeNICEDCV: { name: "NICE DCV", icon: "AWSComputeNICEDCV" },
  aWSComputeNICEEnginFrame: {
    name: "NICE Engin Frame",
    icon: "AWSComputeNICEEnginFrame",
  },
  aWSComputeNitroEnclaves: {
    name: "Nitro Enclaves",
    icon: "AWSComputeNitroEnclaves",
  },
  aWSComputeOutpostsfamily: {
    name: "Outposts family",
    icon: "AWSComputeOutpostsfamily",
  },
  aWSComputeOutpostsrack: {
    name: "Outposts rack",
    icon: "AWSComputeOutpostsrack",
  },
  aWSAnalyticsEMR: { name: "EMR", icon: "AWSAnalyticsEMR" },
  aWSComputeSail: { name: "Sail", icon: "AWSComputeSail" },
  aWSComputeParallelCluster: {
    name: "Parallel Cluster",
    icon: "AWSComputeParallelCluster",
  },
  aWSComputeServerlessApplicationRepository: {
    name: "Serverless Application Repository",
    icon: "AWSComputeServerlessApplicationRepository",
  },
  aWSComputeBatch: { name: "Batch", icon: "AWSComputeBatch" },
  aWSComputeSimSpaceWeaver: {
    name: "Sim Space Weaver",
    icon: "AWSComputeSimSpaceWeaver",
  },
  aWSComputeThinkboxKrakatoa: {
    name: "Thinkbox Krakatoa",
    icon: "AWSComputeThinkboxKrakatoa",
  },
  aWSComputeThinkboxFrost: {
    name: "Thinkbox Frost",
    icon: "AWSComputeThinkboxFrost",
  },
  aWSComputeVMwareCloudonAWS: {
    name: "VMware Cloud on AWS",
    icon: "AWSComputeVMwareCloudonAWS",
  },
  aWSComputeThinkboxSequoia: {
    name: "Thinkbox Sequoia",
    icon: "AWSComputeThinkboxSequoia",
  },
  aWSComputeThinkboxStoke: {
    name: "Thinkbox Stoke",
    icon: "AWSComputeThinkboxStoke",
  },
  aWSComputeThinkboxXMesh: {
    name: "Thinkbox XMesh",
    icon: "AWSComputeThinkboxXMesh",
  },
  aWSComputeThinkboxDeadline: {
    name: "Thinkbox Deadline",
    icon: "AWSComputeThinkboxDeadline",
  },
  aWSComputeWavelength: { name: "Wavelength", icon: "AWSComputeWavelength" },
  aWSContainersEKSCloud: { name: "EKS Cloud", icon: "AWSContainersEKSCloud" },
  aWSComputeOutpostsservers: {
    name: "Outposts servers",
    icon: "AWSComputeOutpostsservers",
  },
  aWSComputeFargate: { name: "Fargate", icon: "AWSComputeFargate" },
  aWSComputeElasticBeanstalk: {
    name: "Elastic Beanstalk",
    icon: "AWSComputeElasticBeanstalk",
  },
  aWSContainersECSAnywhere: {
    name: "ECS Anywhere",
    icon: "AWSContainersECSAnywhere",
  },
  aWSContainersElasticKubernetesService: {
    name: "Elastic Kubernetes Service",
    icon: "AWSContainersElasticKubernetesService",
  },
  aWSContainersElasticContainerService: {
    name: "Elastic Container Service",
    icon: "AWSContainersElasticContainerService",
  },
  aWSCustomerEnablementActivate: {
    name: "Activate",
    icon: "AWSCustomerEnablementActivate",
  },
  aWSContainersFargate: { name: "Fargate", icon: "AWSContainersFargate" },
  aWSAnalyticsQuickSight: {
    name: "Quick Sight",
    icon: "AWSAnalyticsQuickSight",
  },
  aWSCustomerEnablementIQ: { name: "IQ", icon: "AWSCustomerEnablementIQ" },
  aWSContainersRedHatOpenShiftServiceonAWS: {
    name: "Red Hat Open Shift Service on AWS",
    icon: "AWSContainersRedHatOpenShiftServiceonAWS",
  },
  aWSContainersElasticContainerRegistry: {
    name: "Elastic Container Registry",
    icon: "AWSContainersElasticContainerRegistry",
  },
  aWSCustomerEnablementManagedServices: {
    name: "Managed Services",
    icon: "AWSCustomerEnablementManagedServices",
  },
  aWSCustomerEnablementSupport: {
    name: "Support",
    icon: "AWSCustomerEnablementSupport",
  },
  aWSCustomerEnablementTrainingCertification: {
    name: "Training Certification",
    icon: "AWSCustomerEnablementTrainingCertification",
  },
  aWSCustomerEnablementRePost: {
    name: "Re Post",
    icon: "AWSCustomerEnablementRePost",
  },
  aWSContainersEKSAnywhere: {
    name: "EKS Anywhere",
    icon: "AWSContainersEKSAnywhere",
  },
  aWSDatabaseDatabaseMigrationService: {
    name: "Database Migration Service",
    icon: "AWSDatabaseDatabaseMigrationService",
  },
  aWSDatabaseElastiCache: {
    name: "Elasti Cache",
    icon: "AWSDatabaseElastiCache",
  },
  aWSDatabaseKeyspaces: { name: "Keyspaces", icon: "AWSDatabaseKeyspaces" },
  aWSDatabaseMemoryDBforRedis: {
    name: "Memory DB for Redis",
    icon: "AWSDatabaseMemoryDBforRedis",
  },
  aWSDatabaseAurora: { name: "Aurora", icon: "AWSDatabaseAurora" },
  aWSDatabaseNeptune: { name: "Neptune", icon: "AWSDatabaseNeptune" },
  aWSDatabaseRDSonVMware: {
    name: "RDS on VMware",
    icon: "AWSDatabaseRDSonVMware",
  },
  aWSDatabaseTimestream: { name: "Timestream", icon: "AWSDatabaseTimestream" },
  aWSContainersEKSDistro: {
    name: "EKS Distro",
    icon: "AWSContainersEKSDistro",
  },
  aWSDatabaseDocumentDB: {
    name: "Document DB",
    icon: "AWSDatabaseDocumentDB",
  },
  aWSFrontEndWebMobileAmplify: {
    name: "Amplify",
    icon: "AWSFrontEndWebMobileAmplify",
  },
  aWSFrontEndWebMobileDeviceFarm: {
    name: "Device Farm",
    icon: "AWSFrontEndWebMobileDeviceFarm",
  },
  aWSFrontEndWebMobileLocationService: {
    name: "Location Service",
    icon: "AWSFrontEndWebMobileLocationService",
  },
  aWSDeveloperToolsApplicationComposer: {
    name: "Application Composer",
    icon: "AWSDeveloperToolsApplicationComposer",
  },
  aWSDeveloperToolsCloudDevelopmentKit: {
    name: "Cloud Development Kit",
    icon: "AWSDeveloperToolsCloudDevelopmentKit",
  },
  aWSDeveloperToolsCloudShell: {
    name: "Cloud Shell",
    icon: "AWSDeveloperToolsCloudShell",
  },
  aWSDatabaseDynamoDB: { name: "Dynamo DB", icon: "AWSDatabaseDynamoDB" },
  aWSDeveloperToolsCodeArtifact: {
    name: "Code Artifact",
    icon: "AWSDeveloperToolsCodeArtifact",
  },
  aWSDeveloperToolsCloud9: { name: "Cloud9", icon: "AWSDeveloperToolsCloud9" },
  aWSDeveloperToolsCodeBuild: {
    name: "Code Build",
    icon: "AWSDeveloperToolsCodeBuild",
  },
  aWSDeveloperToolsCodeCatalyst: {
    name: "Code Catalyst",
    icon: "AWSDeveloperToolsCodeCatalyst",
  },
  aWSDeveloperToolsCodeCommit: {
    name: "Code Commit",
    icon: "AWSDeveloperToolsCodeCommit",
  },
  aWSDeveloperToolsCloudControlAPI: {
    name: "Cloud Control API",
    icon: "AWSDeveloperToolsCloudControlAPI",
  },
  aWSDatabaseRDS: { name: "RDS", icon: "AWSDatabaseRDS" },
  aWSCustomerEnablementProfessionalServices: {
    name: "Professional Services",
    icon: "AWSCustomerEnablementProfessionalServices",
  },
  aWSDeveloperToolsCodePipeline: {
    name: "Code Pipeline",
    icon: "AWSDeveloperToolsCodePipeline",
  },
  aWSDeveloperToolsCommandLineInterface: {
    name: "Command Line Interface",
    icon: "AWSDeveloperToolsCommandLineInterface",
  },
  aWSDeveloperToolsToolsandSDKs: {
    name: "Tools and SDKs",
    icon: "AWSDeveloperToolsToolsandSDKs",
  },
  aWSDeveloperToolsCodeStar: {
    name: "Code Star",
    icon: "AWSDeveloperToolsCodeStar",
  },
  aWSDeveloperToolsCodeDeploy: {
    name: "Code Deploy",
    icon: "AWSDeveloperToolsCodeDeploy",
  },
  aWSDeveloperToolsXRay: { name: "X Ray", icon: "AWSDeveloperToolsXRay" },
  aWSGeneralIconsMarketplace_Dark: {
    name: "Marketplace Dark",
    icon: "AWSGeneralIconsMarketplace_Dark",
  },
  aWSGeneralIconsMarketplace_: {
    name: "Marketplace",
    icon: "AWSGeneralIconsMarketplace_",
  },
  aWSGamesGameKit: { name: "Game Kit", icon: "AWSGamesGameKit" },
  aWSGamesGameSparks: { name: "Game Sparks", icon: "AWSGamesGameSparks" },
  aWSGamesLumberyard: { name: "Lumberyard", icon: "AWSGamesLumberyard" },
  aWSGamesGameLift: { name: "Game Lift", icon: "AWSGamesGameLift" },
  aWSEndUserComputingAppStream: {
    name: "App Stream",
    icon: "AWSEndUserComputingAppStream",
  },
  aWSEndUserComputingWorkLink: {
    name: "Work Link",
    icon: "AWSEndUserComputingWorkLink",
  },
  aWSEndUserComputingWorkSpacesFamily: {
    name: "Work Spaces Family",
    icon: "AWSEndUserComputingWorkSpacesFamily",
  },
  aWSGamesOpen3DEngine: {
    name: "Open 3D Engine",
    icon: "AWSGamesOpen3DEngine",
  },
  aWSDeveloperToolsCorretto: {
    name: "Corretto",
    icon: "AWSDeveloperToolsCorretto",
  },
  aWSInternetofThingsFreeRTOS: {
    name: "Free RTOS",
    icon: "AWSInternetofThingsFreeRTOS",
  },
  aWSInternetofThingsIoTAnalytics: {
    name: "IoT Analytics",
    icon: "AWSInternetofThingsIoTAnalytics",
  },
  aWSInternetofThingsIoTButton: {
    name: "IoT Button",
    icon: "AWSInternetofThingsIoTButton",
  },
  aWSInternetofThingsIoT1Click: {
    name: "IoT 1 Click",
    icon: "AWSInternetofThingsIoT1Click",
  },
  aWSInternetofThingsIoTCore: {
    name: "IoT Core",
    icon: "AWSInternetofThingsIoTCore",
  },
  aWSInternetofThingsIoTDeviceDefender: {
    name: "IoT Device Defender",
    icon: "AWSInternetofThingsIoTDeviceDefender",
  },
  aWSInternetofThingsIoTEduKit: {
    name: "IoT Edu Kit",
    icon: "AWSInternetofThingsIoTEduKit",
  },
  aWSInternetofThingsIoTDeviceManagement: {
    name: "IoT Device Management",
    icon: "AWSInternetofThingsIoTDeviceManagement",
  },
  aWSInternetofThingsIoTEvents: {
    name: "IoT Events",
    icon: "AWSInternetofThingsIoTEvents",
  },
  aWSInternetofThingsIoTGreengrass: {
    name: "IoT Greengrass",
    icon: "AWSInternetofThingsIoTGreengrass",
  },
  aWSInternetofThingsIoTSiteWise: {
    name: "IoT Site Wise",
    icon: "AWSInternetofThingsIoTSiteWise",
  },
  aWSInternetofThingsIoTExpressLink: {
    name: "IoT Express Link",
    icon: "AWSInternetofThingsIoTExpressLink",
  },
  aWSInternetofThingsIoTThingsGraph: {
    name: "IoT Things Graph",
    icon: "AWSInternetofThingsIoTThingsGraph",
  },
  aWSInternetofThingsIoTTwinMaker: {
    name: "IoT Twin Maker",
    icon: "AWSInternetofThingsIoTTwinMaker",
  },
  aWSMachineLearningComprehendMedical: {
    name: "Comprehend Medical",
    icon: "AWSMachineLearningComprehendMedical",
  },
  aWSMachineLearningApacheMXNetonAWS: {
    name: "Apache MX Net on AWS",
    icon: "AWSMachineLearningApacheMXNetonAWS",
  },
  aWSInternetofThingsIoTRoboRunner: {
    name: "IoT Robo Runner",
    icon: "AWSInternetofThingsIoTRoboRunner",
  },
  aWSMachineLearningCodeWhisperer: {
    name: "Code Whisperer",
    icon: "AWSMachineLearningCodeWhisperer",
  },
  aWSInternetofThingsIoTFleetWise: {
    name: "IoT Fleet Wise",
    icon: "AWSInternetofThingsIoTFleetWise",
  },
  aWSMachineLearningComprehend: {
    name: "Comprehend",
    icon: "AWSMachineLearningComprehend",
  },
  aWSMachineLearningDeepComposer: {
    name: "Deep Composer",
    icon: "AWSMachineLearningDeepComposer",
  },
  aWSMachineLearningDeepLearningContainers: {
    name: "Deep Learning Containers",
    icon: "AWSMachineLearningDeepLearningContainers",
  },
  aWSMachineLearningDeepRacer: {
    name: "Deep Racer",
    icon: "AWSMachineLearningDeepRacer",
  },
  aWSMachineLearningDeepLens: {
    name: "Deep Lens",
    icon: "AWSMachineLearningDeepLens",
  },
  aWSMachineLearningElasticInference: {
    name: "Elastic Inference",
    icon: "AWSMachineLearningElasticInference",
  },
  aWSMachineLearningForecast: {
    name: "Forecast",
    icon: "AWSMachineLearningForecast",
  },
  aWSMachineLearningDeepLearningAMIs: {
    name: "Deep Learning AMIs",
    icon: "AWSMachineLearningDeepLearningAMIs",
  },
  aWSMachineLearningHealthLake: {
    name: "Health Lake",
    icon: "AWSMachineLearningHealthLake",
  },
  aWSMachineLearningAugmentedAIA2I: {
    name: "Augmented AI A2I",
    icon: "AWSMachineLearningAugmentedAIA2I",
  },
  aWSMachineLearningKendra: {
    name: "Kendra",
    icon: "AWSMachineLearningKendra",
  },
  aWSMachineLearningLookoutforEquipment: {
    name: "Lookout for Equipment",
    icon: "AWSMachineLearningLookoutforEquipment",
  },
  aWSMachineLearningLookoutforMetrics: {
    name: "Lookout for Metrics",
    icon: "AWSMachineLearningLookoutforMetrics",
  },
  aWSMachineLearningCodeGuru: {
    name: "Code Guru",
    icon: "AWSMachineLearningCodeGuru",
  },
  aWSMachineLearningLex: { name: "Lex", icon: "AWSMachineLearningLex" },
  aWSMachineLearningLookoutforVision: {
    name: "Lookout for Vision",
    icon: "AWSMachineLearningLookoutforVision",
  },
  aWSMachineLearningMonitron: {
    name: "Monitron",
    icon: "AWSMachineLearningMonitron",
  },
  aWSMachineLearningOmics: { name: "Omics", icon: "AWSMachineLearningOmics" },
  aWSMachineLearningPersonalize: {
    name: "Personalize",
    icon: "AWSMachineLearningPersonalize",
  },
  aWSMachineLearningDevOpsGuru: {
    name: "Dev Ops Guru",
    icon: "AWSMachineLearningDevOpsGuru",
  },
  aWSMachineLearningSageMakerStudioLab: {
    name: "Sage Maker Studio Lab",
    icon: "AWSMachineLearningSageMakerStudioLab",
  },
  aWSMachineLearningPanorama: {
    name: "Panorama",
    icon: "AWSMachineLearningPanorama",
  },
  aWSMachineLearningSageMaker: {
    name: "Sage Maker",
    icon: "AWSMachineLearningSageMaker",
  },
  aWSMachineLearningFraudDetector: {
    name: "Fraud Detector",
    icon: "AWSMachineLearningFraudDetector",
  },
  aWSMachineLearningRekognition: {
    name: "Rekognition",
    icon: "AWSMachineLearningRekognition",
  },
  aWSMachineLearningTorchServe: {
    name: "Torch Serve",
    icon: "AWSMachineLearningTorchServe",
  },
  aWSMachineLearningTextract: {
    name: "Textract",
    icon: "AWSMachineLearningTextract",
  },
  aWSMachineLearningNeuron: {
    name: "Neuron",
    icon: "AWSMachineLearningNeuron",
  },
  aWSMachineLearningTensorFlowonAWS: {
    name: "Tensor Flow on AWS",
    icon: "AWSMachineLearningTensorFlowonAWS",
  },
  aWSMachineLearningTranscribe: {
    name: "Transcribe",
    icon: "AWSMachineLearningTranscribe",
  },
  aWSMigrationTransferApplicationDiscoveryService: {
    name: "Application Discovery Service",
    icon: "AWSMigrationTransferApplicationDiscoveryService",
  },
  aWSMachineLearningTranslate: {
    name: "Translate",
    icon: "AWSMachineLearningTranslate",
  },
  aWSMigrationTransferDataSync: {
    name: "Data Sync",
    icon: "AWSMigrationTransferDataSync",
  },
  aWSMachineLearningSageMakerGroundTruth: {
    name: "Sage Maker Ground Truth",
    icon: "AWSMachineLearningSageMakerGroundTruth",
  },
  aWSMigrationTransferMainframeModernization: {
    name: "Mainframe Modernization",
    icon: "AWSMigrationTransferMainframeModernization",
  },
  aWSMigrationTransferServerMigrationService: {
    name: "Server Migration Service",
    icon: "AWSMigrationTransferServerMigrationService",
  },
  aWSMigrationTransferApplicationMigrationService: {
    name: "Application Migration Service",
    icon: "AWSMigrationTransferApplicationMigrationService",
  },
  aWSMigrationTransferTransferFamily: {
    name: "Transfer Family",
    icon: "AWSMigrationTransferTransferFamily",
  },
  aWSNetworkingContentDeliveryAppMesh: {
    name: "App Mesh",
    icon: "AWSNetworkingContentDeliveryAppMesh",
  },
  aWSNetworkingContentDeliveryCloudDirectory: {
    name: "Cloud Directory",
    icon: "AWSNetworkingContentDeliveryCloudDirectory",
  },
  aWSNetworkingContentDeliveryCloudMap: {
    name: "Cloud Map",
    icon: "AWSNetworkingContentDeliveryCloudMap",
  },
  aWSMigrationTransferMigrationHub: {
    name: "Migration Hub",
    icon: "AWSMigrationTransferMigrationHub",
  },
  aWSMigrationTransferMigrationEvaluator: {
    name: "Migration Evaluator",
    icon: "AWSMigrationTransferMigrationEvaluator",
  },
  aWSNetworkingContentDeliveryCloudWAN: {
    name: "Cloud WAN",
    icon: "AWSNetworkingContentDeliveryCloudWAN",
  },
  aWSNetworkingContentDeliveryClientVPN: {
    name: "Client VPN",
    icon: "AWSNetworkingContentDeliveryClientVPN",
  },
  aWSNetworkingContentDeliveryCloudFront: {
    name: "Cloud Front",
    icon: "AWSNetworkingContentDeliveryCloudFront",
  },
  aWSNetworkingContentDeliveryGlobalAccelerator: {
    name: "Global Accelerator",
    icon: "AWSNetworkingContentDeliveryGlobalAccelerator",
  },
  aWSNetworkingContentDeliveryElasticLoadBalancing: {
    name: "Elastic Load Balancing",
    icon: "AWSNetworkingContentDeliveryElasticLoadBalancing",
  },
  aWSNetworkingContentDeliveryRoute53: {
    name: "Route 53",
    icon: "AWSNetworkingContentDeliveryRoute53",
  },
  aWSNetworkingContentDeliveryPrivateLink: {
    name: "Private Link",
    icon: "AWSNetworkingContentDeliveryPrivateLink",
  },
  aWSNetworkingContentDeliverySitetoSiteVPN: {
    name: "Site to Site VPN",
    icon: "AWSNetworkingContentDeliverySitetoSiteVPN",
  },
  aWSNetworkingContentDeliveryPrivate5G: {
    name: "Private 5G",
    icon: "AWSNetworkingContentDeliveryPrivate5G",
  },
  aWSNetworkingContentDeliveryDirectConnect: {
    name: "Direct Connect",
    icon: "AWSNetworkingContentDeliveryDirectConnect",
  },
  aWSNetworkingContentDeliveryTransitGateway: {
    name: "Transit Gateway",
    icon: "AWSNetworkingContentDeliveryTransitGateway",
  },
  aWSNetworkingContentDeliveryVPCLattice: {
    name: "VPC Lattice",
    icon: "AWSNetworkingContentDeliveryVPCLattice",
  },
  aWSRoboticsRoboMaker: { name: "Robo Maker", icon: "AWSRoboticsRoboMaker" },
  aWSNetworkingContentDeliveryVirtualPrivateCloud: {
    name: "Virtual Private Cloud",
    icon: "AWSNetworkingContentDeliveryVirtualPrivateCloud",
  },
  aWSNetworkingContentDeliveryVerifiedAccess: {
    name: "Verified Access",
    icon: "AWSNetworkingContentDeliveryVerifiedAccess",
  },
  aWSStorageBackup: { name: "Backup", icon: "AWSStorageBackup" },
  aWSQuantumTechnologiesBraket: {
    name: "Braket",
    icon: "AWSQuantumTechnologiesBraket",
  },
  aWSStorageElasticBlockStore: {
    name: "Elastic Block Store",
    icon: "AWSStorageElasticBlockStore",
  },
  aWSStorageEFS: { name: "EFS", icon: "AWSStorageEFS" },
  aWSStorageElasticDisasterRecovery: {
    name: "Elastic Disaster Recovery",
    icon: "AWSStorageElasticDisasterRecovery",
  },
  aWSStorageFSxforNetAppONTAP: {
    name: "FSx for Net App ONTAP",
    icon: "AWSStorageFSxforNetAppONTAP",
  },
  aWSStorageFSx: { name: "FSx", icon: "AWSStorageFSx" },
  aWSStorageFileCache: { name: "File Cache", icon: "AWSStorageFileCache" },
  aWSMachineLearningPolly: { name: "Polly", icon: "AWSMachineLearningPolly" },
  aWSStorageS3onOutposts: {
    name: "S3 on Outposts",
    icon: "AWSStorageS3onOutposts",
  },
  aWSStorageFSxforLustre: {
    name: "FSx for Lustre",
    icon: "AWSStorageFSxforLustre",
  },
  aWSStorageSimpleStorageServiceGlacier: {
    name: "Simple Storage Service Glacier",
    icon: "AWSStorageSimpleStorageServiceGlacier",
  },
  aWSStorageSnowballEdge: {
    name: "Snowball Edge",
    icon: "AWSStorageSnowballEdge",
  },
  aWSStorageFSxforWFS: { name: "FSx for WFS", icon: "AWSStorageFSxforWFS" },
  aWSStorageSnowcone: { name: "Snowcone", icon: "AWSStorageSnowcone" },
  aWSStorageStorageGateway: {
    name: "Storage Gateway",
    icon: "AWSStorageStorageGateway",
  },
  aWSStorageFSxforOpenZFS: {
    name: "FSx for Open ZFS",
    icon: "AWSStorageFSxforOpenZFS",
  },
  aWSSatelliteGroundStation: {
    name: "Ground Station",
    icon: "AWSSatelliteGroundStation",
  },
  aWSStorageSimpleStorageService: {
    name: "Simple Storage Service",
    icon: "AWSStorageSimpleStorageService",
  },
  aWSStorageSnowmobile: { name: "Snowmobile", icon: "AWSStorageSnowmobile" },
  aWSManagementGovernanceAutoScaling: {
    name: "Auto Scaling",
    icon: "AWSManagementGovernanceAutoScaling",
  },
  aWSManagementGovernanceBackintAgent: {
    name: "Backint Agent",
    icon: "AWSManagementGovernanceBackintAgent",
  },
  aWSManagementGovernanceChatbot: {
    name: "Chatbot",
    icon: "AWSManagementGovernanceChatbot",
  },
  aWSStorageSnowball: { name: "Snowball", icon: "AWSStorageSnowball" },
  aWSManagementGovernanceCloudWatch: {
    name: "Cloud Watch",
    icon: "AWSManagementGovernanceCloudWatch",
  },
  aWSManagementGovernanceConfig: {
    name: "Config",
    icon: "AWSManagementGovernanceConfig",
  },
  aWSManagementGovernanceCloudFormation: {
    name: "Cloud Formation",
    icon: "AWSManagementGovernanceCloudFormation",
  },
  aWSManagementGovernanceCloudTrail: {
    name: "Cloud Trail",
    icon: "AWSManagementGovernanceCloudTrail",
  },
  aWSManagementGovernanceControlTower: {
    name: "Control Tower",
    icon: "AWSManagementGovernanceControlTower",
  },
  aWSManagementGovernanceAppConfig: {
    name: "App Config",
    icon: "AWSManagementGovernanceAppConfig",
  },
  aWSManagementGovernanceLaunchWizard: {
    name: "Launch Wizard",
    icon: "AWSManagementGovernanceLaunchWizard",
  },
  aWSManagementGovernanceDistroforOpenTelemetry: {
    name: "Distro for Open Telemetry",
    icon: "AWSManagementGovernanceDistroforOpenTelemetry",
  },
  aWSManagementGovernanceApplicationAutoScaling: {
    name: "Application Auto Scaling",
    icon: "AWSManagementGovernanceApplicationAutoScaling",
  },
  aWSManagementGovernanceManagedGrafana: {
    name: "Managed Grafana",
    icon: "AWSManagementGovernanceManagedGrafana",
  },
  aWSManagementGovernanceOpsWorks: {
    name: "Ops Works",
    icon: "AWSManagementGovernanceOpsWorks",
  },
  aWSManagementGovernanceManagedServiceforPrometheus: {
    name: "Managed Service for Prometheus",
    icon: "AWSManagementGovernanceManagedServiceforPrometheus",
  },
  aWSManagementGovernanceOrganizations: {
    name: "Organizations",
    icon: "AWSManagementGovernanceOrganizations",
  },
  aWSManagementGovernanceResilienceHub: {
    name: "Resilience Hub",
    icon: "AWSManagementGovernanceResilienceHub",
  },
  aWSManagementGovernanceProton: {
    name: "Proton",
    icon: "AWSManagementGovernanceProton",
  },
  aWSManagementGovernanceServiceCatalog: {
    name: "Service Catalog",
    icon: "AWSManagementGovernanceServiceCatalog",
  },
  aWSManagementGovernanceLicenseManager: {
    name: "License Manager",
    icon: "AWSManagementGovernanceLicenseManager",
  },
  aWSManagementGovernanceServiceManagementConnector: {
    name: "Service Management Connector",
    icon: "AWSManagementGovernanceServiceManagementConnector",
  },
  aWSManagementGovernanceTrustedAdvisor: {
    name: "Trusted Advisor",
    icon: "AWSManagementGovernanceTrustedAdvisor",
  },
  aWSMediaServicesElasticTranscoder: {
    name: "Elastic Transcoder",
    icon: "AWSMediaServicesElasticTranscoder",
  },
  aWSVRARSumerian: { name: "Sumerian", icon: "AWSVRARSumerian" },
  aWSMediaServicesElementalAppliancesSoftware: {
    name: "Elemental Appliances & Software",
    icon: "AWSMediaServicesElementalAppliancesSoftware",
  },
  aWSManagementGovernanceManagementConsole: {
    name: "Management Console",
    icon: "AWSManagementGovernanceManagementConsole",
  },
  aWSMediaServicesElementalDelta: {
    name: "Elemental Delta",
    icon: "AWSMediaServicesElementalDelta",
  },
  aWSManagementGovernanceWellArchitectedTool: {
    name: "Well Architected Tool",
    icon: "AWSManagementGovernanceWellArchitectedTool",
  },
  aWSManagementGovernanceFaultInjectionSimulator: {
    name: "Fault Injection Simulator",
    icon: "AWSManagementGovernanceFaultInjectionSimulator",
  },
  aWSMediaServicesElementalConductor: {
    name: "Elemental Conductor",
    icon: "AWSMediaServicesElementalConductor",
  },
  aWSMediaServicesElementalLink: {
    name: "Elemental Link",
    icon: "AWSMediaServicesElementalLink",
  },
  aWSManagementGovernanceSystemsManager: {
    name: "Systems Manager",
    icon: "AWSManagementGovernanceSystemsManager",
  },
  aWSManagementGovernancePersonalHealthDashboard: {
    name: "Personal Health Dashboard",
    icon: "AWSManagementGovernancePersonalHealthDashboard",
  },
  aWSMediaServicesElementalMediaConvert: {
    name: "Elemental Media Convert",
    icon: "AWSMediaServicesElementalMediaConvert",
  },
  aWSMediaServicesElementalMediaPackage: {
    name: "Elemental Media Package",
    icon: "AWSMediaServicesElementalMediaPackage",
  },
  aWSMediaServicesElementalMediaStore: {
    name: "Elemental Media Store",
    icon: "AWSMediaServicesElementalMediaStore",
  },
  aWSMediaServicesElementalMediaLive: {
    name: "Elemental Media Live",
    icon: "AWSMediaServicesElementalMediaLive",
  },
  aWSMediaServicesElementalMediaConnect: {
    name: "Elemental Media Connect",
    icon: "AWSMediaServicesElementalMediaConnect",
  },
  aWSMediaServicesInteractiveVideoService: {
    name: "Interactive Video Service",
    icon: "AWSMediaServicesInteractiveVideoService",
  },
  aWSMediaServicesElementalServer: {
    name: "Elemental Server",
    icon: "AWSMediaServicesElementalServer",
  },
  aWSMediaServicesKinesisVideoStreams: {
    name: "Kinesis Video Streams",
    icon: "AWSMediaServicesKinesisVideoStreams",
  },
  aWSSecurityIdentityComplianceArtifact: {
    name: "Artifact",
    icon: "AWSSecurityIdentityComplianceArtifact",
  },
  aWSSecurityIdentityComplianceCloudHSM: {
    name: "Cloud HSM",
    icon: "AWSSecurityIdentityComplianceCloudHSM",
  },
  aWSSecurityIdentityComplianceAuditManager: {
    name: "Audit Manager",
    icon: "AWSSecurityIdentityComplianceAuditManager",
  },
  aWSMediaServicesElementalMediaTailor: {
    name: "Elemental Media Tailor",
    icon: "AWSMediaServicesElementalMediaTailor",
  },
  aWSSecurityIdentityComplianceCertificateManager: {
    name: "Certificate Manager",
    icon: "AWSSecurityIdentityComplianceCertificateManager",
  },
  aWSSecurityIdentityComplianceCloudDirectory: {
    name: "Cloud Directory",
    icon: "AWSSecurityIdentityComplianceCloudDirectory",
  },
  aWSSecurityIdentityComplianceDirectoryService: {
    name: "Directory Service",
    icon: "AWSSecurityIdentityComplianceDirectoryService",
  },
  aWSSecurityIdentityComplianceDetective: {
    name: "Detective",
    icon: "AWSSecurityIdentityComplianceDetective",
  },
  aWSSecurityIdentityComplianceFirewallManager: {
    name: "Firewall Manager",
    icon: "AWSSecurityIdentityComplianceFirewallManager",
  },
  aWSMediaServicesElementalLive: {
    name: "Elemental Live",
    icon: "AWSMediaServicesElementalLive",
  },
  aWSSecurityIdentityComplianceCognito: {
    name: "Cognito",
    icon: "AWSSecurityIdentityComplianceCognito",
  },
  aWSSecurityIdentityComplianceIdentityandAccessManagement: {
    name: "Identity and Access Management",
    icon: "AWSSecurityIdentityComplianceIdentityandAccessManagement",
  },
  aWSSecurityIdentityComplianceInspector: {
    name: "Inspector",
    icon: "AWSSecurityIdentityComplianceInspector",
  },
  aWSManagementGovernanceResourceExplorer: {
    name: "Resource Explorer",
    icon: "AWSManagementGovernanceResourceExplorer",
  },
  aWSSecurityIdentityComplianceResourceAccessManager: {
    name: "Resource Access Manager",
    icon: "AWSSecurityIdentityComplianceResourceAccessManager",
  },
  aWSMediaServicesNimbleStudio: {
    name: "Nimble Studio",
    icon: "AWSMediaServicesNimbleStudio",
  },
  aWSSecurityIdentityComplianceSecurityHub: {
    name: "Security Hub",
    icon: "AWSSecurityIdentityComplianceSecurityHub",
  },
  aWSSecurityIdentityComplianceSecurityLake: {
    name: "Security Lake",
    icon: "AWSSecurityIdentityComplianceSecurityLake",
  },
  aWSSecurityIdentityComplianceVerifiedPermissions: {
    name: "Verified Permissions",
    icon: "AWSSecurityIdentityComplianceVerifiedPermissions",
  },
  aWSSecurityIdentityComplianceShield: {
    name: "Shield",
    icon: "AWSSecurityIdentityComplianceShield",
  },
  aWSSecurityIdentityComplianceIAMIdentityCenter: {
    name: "IAM Identity Center",
    icon: "AWSSecurityIdentityComplianceIAMIdentityCenter",
  },
  aWSSecurityIdentityComplianceNetworkFirewall: {
    name: "Network Firewall",
    icon: "AWSSecurityIdentityComplianceNetworkFirewall",
  },
  aWSSecurityIdentityComplianceMacie: {
    name: "Macie",
    icon: "AWSSecurityIdentityComplianceMacie",
  },
  aWSSecurityIdentityCompliancePrivateCertificateAuthority: {
    name: "Private Certificate Authority",
    icon: "AWSSecurityIdentityCompliancePrivateCertificateAuthority",
  },
  aWSSecurityIdentityComplianceKeyManagementService: {
    name: "Key Management Service",
    icon: "AWSSecurityIdentityComplianceKeyManagementService",
  },
  aWSSecurityIdentityComplianceGuardDuty: {
    name: "Guard Duty",
    icon: "AWSSecurityIdentityComplianceGuardDuty",
  },
  aWSSecurityIdentityComplianceSigner: {
    name: "Signer",
    icon: "AWSSecurityIdentityComplianceSigner",
  },
  aWSSecurityIdentityComplianceWAF: {
    name: "WAF",
    icon: "AWSSecurityIdentityComplianceWAF",
  },
  aWSSecurityIdentityComplianceSecretsManager: {
    name: "Secrets Manager",
    icon: "AWSSecurityIdentityComplianceSecretsManager",
  },
};
