interface IconNames {
  [key: string]: string;
}

export const SkillIconNames: IconNames = {
  skillIconAbleton: "SkillIconAbleton",
  skillIconActivityPub: "SkillIconActivityPub",
  skillIconAWS: "SkillIconAWS",
  skillIconAdonis: "SkillIconAdonis",
  skillIconAfterEffects: "SkillIconAfterEffects",
  skillIconAlpineJS: "SkillIconAlpineJS",
  skillIconAndroidStudio: "SkillIconAndroidStudio",
  skillIconAngular: "SkillIconAngular",
  skillIconAnsible: "SkillIconAnsible",
  skillIconApollo: "SkillIconApollo",
  skillIconAppwrite: "SkillIconAppwrite",
  skillIconAnaconda: "SkillIconAnaconda",
  skillIconAiScript: "SkillIconAiScript",
  skillIconActix: "SkillIconActix",
  skillIconArch: "SkillIconArch",
  skillIconArduino: "SkillIconArduino",
  skillIconApple: "SkillIconApple",
  skillIconAtom: "SkillIconAtom",
  skillIconAudition: "SkillIconAudition",
  skillIconAstro: "SkillIconAstro",
  skillIconAutoCAD: "SkillIconAutoCAD",
  skillIconAzul: "SkillIconAzul",
  skillIconAzure: "SkillIconAzure",
  skillIconBitBucket: "SkillIconBitBucket",
  skillIconBash: "SkillIconBash",
  skillIconBSD: "SkillIconBSD",
  skillIconC: "SkillIconC",
  skillIconBevy: "SkillIconBevy",
  skillIconCPP: "SkillIconCPP",
  skillIconCMake: "SkillIconCMake",
  skillIconCLion: "SkillIconCLion",
  skillIconBun: "SkillIconBun",
  skillIconBabel: "SkillIconBabel",
  skillIconBlender: "SkillIconBlender",
  skillIconCSS: "SkillIconCSS",
  skillIconCloudflare: "SkillIconCloudflare",
  skillIconClojure: "SkillIconClojure",
  skillIconCoffeeScript: "SkillIconCoffeeScript",
  skillIconCodePen: "SkillIconCodePen",
  skillIconCrystal: "SkillIconCrystal",
  skillIconD3: "SkillIconD3",
  skillIconBootstrap: "SkillIconBootstrap",
  skillIconCS: "SkillIconCS",
  skillIconCypress: "SkillIconCypress",
  skillIconDiscord: "SkillIconDiscord",
  skillIconDevTo: "SkillIconDevTo",
  skillIconCassandra: "SkillIconCassandra",
  skillIconDiscordBots: "SkillIconDiscordBots",
  skillIconDENO: "SkillIconDENO",
  skillIconDart: "SkillIconDart",
  skillIconDebian: "SkillIconDebian",
  skillIconDjango: "SkillIconDjango",
  skillIconDiscordJS: "SkillIconDiscordJS",
  skillIconDotNet: "SkillIconDotNet",
  skillIconDocker: "SkillIconDocker",
  skillIconEclipse: "SkillIconEclipse",
  skillIconElectron: "SkillIconElectron",
  skillIconElixir: "SkillIconElixir",
  skillIconEmacs: "SkillIconEmacs",
  skillIconElysia: "SkillIconElysia",
  skillIconEmber: "SkillIconEmber",
  skillIconExpressJS: "SkillIconExpressJS",
  skillIconElasticsearch: "SkillIconElasticsearch",
  skillIconFediverse: "SkillIconFediverse",
  skillIconDynamoDB: "SkillIconDynamoDB",
  skillIconFlutter: "SkillIconFlutter",
  skillIconFigma: "SkillIconFigma",
  skillIconGTK: "SkillIconGTK",
  skillIconFortran: "SkillIconFortran",
  skillIconEmotion: "SkillIconEmotion",
  skillIconForth: "SkillIconForth",
  skillIconFirebase: "SkillIconFirebase",
  skillIconFlask: "SkillIconFlask",
  skillIconGCP: "SkillIconGCP",
  skillIconFastAPI: "SkillIconFastAPI",
  skillIconGherkin: "SkillIconGherkin",
  skillIconGit: "SkillIconGit",
  skillIconGameMakerStudio: "SkillIconGameMakerStudio",
  skillIconGatsby: "SkillIconGatsby",
  skillIconGoLang: "SkillIconGoLang",
  skillIconGithub: "SkillIconGithub",
  skillIconGitLab: "SkillIconGitLab",
  skillIconGmail: "SkillIconGmail",
  skillIconHTML: "SkillIconHTML",
  skillIconGodot: "SkillIconGodot",
  skillIconGraphQL: "SkillIconGraphQL",
  skillIconHaskell: "SkillIconHaskell",
  skillIconHaxe: "SkillIconHaxe",
  skillIconGithubActions: "SkillIconGithubActions",
  skillIconGulp: "SkillIconGulp",
  skillIconHeroku: "SkillIconHeroku",
  skillIconGradle: "SkillIconGradle",
  skillIconHibernate: "SkillIconHibernate",
  skillIconHtmx: "SkillIconHtmx",
  skillIconIPFS: "SkillIconIPFS",
  skillIconIdea: "SkillIconIdea",
  skillIconIllustrator: "SkillIconIllustrator",
  skillIconHaxeFlixel: "SkillIconHaxeFlixel",
  skillIconJava: "SkillIconJava",
  skillIconGrafana: "SkillIconGrafana",
  skillIconInstagram: "SkillIconInstagram",
  skillIconJenkins: "SkillIconJenkins",
  skillIconJavaScript: "SkillIconJavaScript",
  skillIconJest: "SkillIconJest",
  skillIconKtor: "SkillIconKtor",
  skillIconJQuery: "SkillIconJQuery",
  skillIconKafka: "SkillIconKafka",
  skillIconKubernetes: "SkillIconKubernetes",
  skillIconKali: "SkillIconKali",
  skillIconKotlin: "SkillIconKotlin",
  skillIconJulia: "SkillIconJulia",
  skillIconLaravel: "SkillIconLaravel",
  skillIconLinkedIn: "SkillIconLinkedIn",
  skillIconLit: "SkillIconLit",
  skillIconMatlab: "SkillIconMatlab",
  skillIconMarkdown: "SkillIconMarkdown",
  skillIconLaTeX: "SkillIconLaTeX",
  skillIconMaterialUI: "SkillIconMaterialUI",
  skillIconMastodon: "SkillIconMastodon",
  skillIconMisskey: "SkillIconMisskey",
  skillIconLinux: "SkillIconLinux",
  skillIconMongoDB: "SkillIconMongoDB",
  skillIconLess: "SkillIconLess",
  skillIconMySQL: "SkillIconMySQL",
  skillIconNeoVim: "SkillIconNeoVim",
  skillIconMint: "SkillIconMint",
  skillIconLua: "SkillIconLua",
  skillIconNginx: "SkillIconNginx",
  skillIconNim: "SkillIconNim",
  skillIconNix: "SkillIconNix",
  skillIconNotion: "SkillIconNotion",
  skillIconNetlify: "SkillIconNetlify",
  skillIconMaven: "SkillIconMaven",
  skillIconNuxtJS: "SkillIconNuxtJS",
  skillIconOCaml: "SkillIconOCaml",
  skillIconNestJS: "SkillIconNestJS",
  skillIconOpenCV: "SkillIconOpenCV",
  skillIconOctave: "SkillIconOctave",
  skillIconObsidian: "SkillIconObsidian",
  skillIconNodeJS: "SkillIconNodeJS",
  skillIconOpenShift: "SkillIconOpenShift",
  skillIconOpenStack: "SkillIconOpenStack",
  skillIconNpm: "SkillIconNpm",
  skillIconPHP: "SkillIconPHP",
  skillIconPkl: "SkillIconPkl",
  skillIconPnpm: "SkillIconPnpm",
  skillIconPinia: "SkillIconPinia",
  skillIconPhpStorm: "SkillIconPhpStorm",
  skillIconPostgreSQL: "SkillIconPostgreSQL",
  skillIconPlanetScale: "SkillIconPlanetScale",
  skillIconPhotoshop: "SkillIconPhotoshop",
  skillIconPrisma: "SkillIconPrisma",
  skillIconPowershell: "SkillIconPowershell",
  skillIconPerl: "SkillIconPerl",
  skillIconPrometheus: "SkillIconPrometheus",
  skillIconPyCharm: "SkillIconPyCharm",
  skillIconPyTorch: "SkillIconPyTorch",
  skillIconPug: "SkillIconPug",
  skillIconPostman: "SkillIconPostman",
  skillIconNextJS: "SkillIconNextJS",
  skillIconPremiere: "SkillIconPremiere",
  skillIconPlan9: "SkillIconPlan9",
  skillIconProcessing: "SkillIconProcessing",
  skillIconQT: "SkillIconQT",
  skillIconROS: "SkillIconROS",
  skillIconRails: "SkillIconRails",
  skillIconR: "SkillIconR",
  skillIconRaspberryPi: "SkillIconRaspberryPi",
  skillIconRabbitMQ: "SkillIconRabbitMQ",
  skillIconPython: "SkillIconPython",
  skillIconReactiveX: "SkillIconReactiveX",
  skillIconReact: "SkillIconReact",
  skillIconRedis: "SkillIconRedis",
  skillIconRedHat: "SkillIconRedHat",
  skillIconRemix: "SkillIconRemix",
  skillIconRegex: "SkillIconRegex",
  skillIconReplit: "SkillIconReplit",
  skillIconRider: "SkillIconRider",
  skillIconRocket: "SkillIconRocket",
  skillIconSVG: "SkillIconSVG",
  skillIconSass: "SkillIconSass",
  skillIconRobloxStudio: "SkillIconRobloxStudio",
  skillIconRuby: "SkillIconRuby",
  skillIconScala: "SkillIconScala",
  skillIconRust: "SkillIconRust",
  skillIconRollupJS: "SkillIconRollupJS",
  skillIconSentry: "SkillIconSentry",
  skillIconSequelize: "SkillIconSequelize",
  skillIconSciKitLearn: "SkillIconSciKitLearn",
  skillIconSolidity: "SkillIconSolidity",
  skillIconSelenium: "SkillIconSelenium",
  skillIconStackOverflow: "SkillIconStackOverflow",
  skillIconStyledComponents: "SkillIconStyledComponents",
  skillIconSpring: "SkillIconSpring",
  skillIconSublime: "SkillIconSublime",
  skillIconSQLite: "SkillIconSQLite",
  skillIconSwift: "SkillIconSwift",
  skillIconSvelte: "SkillIconSvelte",
  skillIconSupabase: "SkillIconSupabase",
  skillIconSketchup: "SkillIconSketchup",
  skillIconRedux: "SkillIconRedux",
  skillIconTailwindCSS: "SkillIconTailwindCSS",
  skillIconSolidJS: "SkillIconSolidJS",
  skillIconTerraform: "SkillIconTerraform",
  skillIconSymfony: "SkillIconSymfony",
  skillIconTauri: "SkillIconTauri",
  skillIconUnrealEngine: "SkillIconUnrealEngine",
  skillIconTwitter: "SkillIconTwitter",
  skillIconUnity: "SkillIconUnity",
  skillIconTensorFlow: "SkillIconTensorFlow",
  skillIconVIM: "SkillIconVIM",
  skillIconVSCodium: "SkillIconVSCodium",
  skillIconUbuntu: "SkillIconUbuntu",
  skillIconVSCode: "SkillIconVSCode",
  skillIconVercel: "SkillIconVercel",
  skillIconThreeJS: "SkillIconThreeJS",
  skillIconVite: "SkillIconVite",
  skillIconTypeScript: "SkillIconTypeScript",
  skillIconVala: "SkillIconVala",
  skillIconV: "SkillIconV",
  skillIconVitest: "SkillIconVitest",
  skillIconWebAssembly: "SkillIconWebAssembly",
  skillIconVisualStudio: "SkillIconVisualStudio",
  skillIconVueJS: "SkillIconVueJS",
  skillIconWebflow: "SkillIconWebflow",
  skillIconWindiCSS: "SkillIconWindiCSS",
  skillIconWindows: "SkillIconWindows",
  skillIconWebpack: "SkillIconWebpack",
  skillIconVuetify: "SkillIconVuetify",
  skillIconXD: "SkillIconXD",
  skillIconWordpress: "SkillIconWordpress",
  skillIconWorkers: "SkillIconWorkers",
  skillIconYarn: "SkillIconYarn",
  skillIconWebStorm: "SkillIconWebStorm",
  skillIconYew: "SkillIconYew",
  skillIconZig: "SkillIconZig",
  skillIconp5js: "SkillIconp5js",
};

export const AWSIconNames: IconNames = {
  aWSAnalyticsCleanRooms: "AWSAnalyticsCleanRooms",
  aWSAnalyticsDataExchange: "AWSAnalyticsDataExchange",
  aWSAnalyticsAthena: "AWSAnalyticsAthena",
  aWSAnalyticsCloudSearch: "AWSAnalyticsCloudSearch",
  aWSAnalyticsDataZone: "AWSAnalyticsDataZone",
  aWSAnalyticsEMR: "AWSAnalyticsEMR",
  aWSAnalyticsGlueDataBrew: "AWSAnalyticsGlueDataBrew",
  aWSAnalyticsFinSpace: "AWSAnalyticsFinSpace",
  aWSAnalyticsGlueElasticViews: "AWSAnalyticsGlueElasticViews",
  aWSAnalyticsKinesisDataStreams: "AWSAnalyticsKinesisDataStreams",
  aWSAnalyticsGlue: "AWSAnalyticsGlue",
  aWSAnalyticsKinesisDataAnalytics: "AWSAnalyticsKinesisDataAnalytics",
  aWSAnalyticsDataPipeline: "AWSAnalyticsDataPipeline",
  aWSAnalyticsKinesisVideoStreams: "AWSAnalyticsKinesisVideoStreams",
  aWSAnalyticsKinesisFirehose: "AWSAnalyticsKinesisFirehose",
  aWSAnalyticsKinesis: "AWSAnalyticsKinesis",
  aWSAnalyticsLakeFormation: "AWSAnalyticsLakeFormation",
  aWSAnalyticsManagedStreamingforApacheKafka:
    "AWSAnalyticsManagedStreamingforApacheKafka",
  aWSAnalyticsQuickSight: "AWSAnalyticsQuickSight",
  aWSAnalyticsOpenSearchService: "AWSAnalyticsOpenSearchService",
  aWSAnalyticsRedshift: "AWSAnalyticsRedshift",
  aWSAppIntegrationAPIGateway: "AWSAppIntegrationAPIGateway",
  aWSAppIntegrationAppFlow: "AWSAppIntegrationAppFlow",
  aWSAppIntegrationEventBridge: "AWSAppIntegrationEventBridge",
  aWSBlockchainQuantumLedgerDatabase: "AWSBlockchainQuantumLedgerDatabase",
  aWSBlockchainManagedBlockchain: "AWSBlockchainManagedBlockchain",
  aWSAppIntegrationAppSync: "AWSAppIntegrationAppSync",
  aWSAppIntegrationSimpleNotificationService:
    "AWSAppIntegrationSimpleNotificationService",
  aWSAppIntegrationStepFunctions: "AWSAppIntegrationStepFunctions",
  aWSAppIntegrationManagedWorkflowsforApacheAirflow:
    "AWSAppIntegrationManagedWorkflowsforApacheAirflow",
  aWSBusinessApplicationsAlexaForBusiness:
    "AWSBusinessApplicationsAlexaForBusiness",
  aWSBusinessApplicationsChimeSDK: "AWSBusinessApplicationsChimeSDK",
  aWSAppIntegrationExpressWorkflows: "AWSAppIntegrationExpressWorkflows",
  aWSAppIntegrationConsoleMobileApplication:
    "AWSAppIntegrationConsoleMobileApplication",
  aWSAppIntegrationSimpleQueueService: "AWSAppIntegrationSimpleQueueService",
  aWSBusinessApplicationsChime: "AWSBusinessApplicationsChime",
  aWSBusinessApplicationsHoneycode: "AWSBusinessApplicationsHoneycode",
  aWSAppIntegrationMQ: "AWSAppIntegrationMQ",
  aWSBusinessApplicationsConnect: "AWSBusinessApplicationsConnect",
  aWSBusinessApplicationsPinpoint: "AWSBusinessApplicationsPinpoint",
  aWSBusinessApplicationsChimeVoiceConnector:
    "AWSBusinessApplicationsChimeVoiceConnector",
  aWSBusinessApplicationsSimpleEmailService:
    "AWSBusinessApplicationsSimpleEmailService",
  aWSBusinessApplicationsWickr: "AWSBusinessApplicationsWickr",
  aWSBusinessApplicationsWorkDocsSDK: "AWSBusinessApplicationsWorkDocsSDK",
  aWSCloudFinancialManagementApplicationCostProfiler:
    "AWSCloudFinancialManagementApplicationCostProfiler",
  aWSCloudFinancialManagementBillingConductor:
    "AWSCloudFinancialManagementBillingConductor",
  aWSBusinessApplicationsWorkMail: "AWSBusinessApplicationsWorkMail",
  aWSBusinessApplicationsWorkDocs: "AWSBusinessApplicationsWorkDocs",
  aWSBusinessApplicationsSupplyChain: "AWSBusinessApplicationsSupplyChain",
  aWSBusinessApplicationsPinpointAPIs: "AWSBusinessApplicationsPinpointAPIs",
  aWSCloudFinancialManagementBudgets: "AWSCloudFinancialManagementBudgets",
  aWSCloudFinancialManagementCostandUsageReport:
    "AWSCloudFinancialManagementCostandUsageReport",
  aWSCloudFinancialManagementCostExplorer:
    "AWSCloudFinancialManagementCostExplorer",
  aWSCloudFinancialManagementReservedInstanceReporting:
    "AWSCloudFinancialManagementReservedInstanceReporting",
  aWSCloudFinancialManagementSavingsPlans:
    "AWSCloudFinancialManagementSavingsPlans",
  aWSCustomerEnablementTrainingCertification:
    "AWSCustomerEnablementTrainingCertification",
  aWSCustomerEnablementActivate: "AWSCustomerEnablementActivate",
  aWSCustomerEnablementIQ: "AWSCustomerEnablementIQ",
  aWSCustomerEnablementManagedServices: "AWSCustomerEnablementManagedServices",
  aWSComputeApplicationAutoScaling: "AWSComputeApplicationAutoScaling",
  aWSCustomerEnablementRePost: "AWSCustomerEnablementRePost",
  aWSComputeEC2AutoScaling: "AWSComputeEC2AutoScaling",
  aWSCustomerEnablementSupport: "AWSCustomerEnablementSupport",
  aWSComputeBottlerocket: "AWSComputeBottlerocket",
  aWSCustomerEnablementProfessionalServices:
    "AWSCustomerEnablementProfessionalServices",
  aWSComputeEC2ImageBuilder: "AWSComputeEC2ImageBuilder",
  aWSComputeComputeOptimizer: "AWSComputeComputeOptimizer",
  aWSComputeEC2: "AWSComputeEC2",
  aWSComputeElasticFabricAdapter: "AWSComputeElasticFabricAdapter",
  aWSComputeAppRunner: "AWSComputeAppRunner",
  aWSComputeBatch: "AWSComputeBatch",
  aWSComputeElasticBeanstalk: "AWSComputeElasticBeanstalk",
  aWSComputeLambda: "AWSComputeLambda",
  aWSComputeNICEDCV: "AWSComputeNICEDCV",
  aWSComputeNICEEnginFrame: "AWSComputeNICEEnginFrame",
  aWSComputeLocalZones: "AWSComputeLocalZones",
  aWSComputeNitroEnclaves: "AWSComputeNitroEnclaves",
  aWSComputeGenomicsCLI: "AWSComputeGenomicsCLI",
  aWSComputeFargate: "AWSComputeFargate",
  aWSComputeOutpostsfamily: "AWSComputeOutpostsfamily",
  aWSComputeSail: "AWSComputeSail",
  aWSComputeOutpostsrack: "AWSComputeOutpostsrack",
  aWSComputeOutpostsservers: "AWSComputeOutpostsservers",
  aWSComputeServerlessApplicationRepository:
    "AWSComputeServerlessApplicationRepository",
  aWSComputeThinkboxKrakatoa: "AWSComputeThinkboxKrakatoa",
  aWSComputeThinkboxDeadline: "AWSComputeThinkboxDeadline",
  aWSComputeSimSpaceWeaver: "AWSComputeSimSpaceWeaver",
  aWSComputeThinkboxStoke: "AWSComputeThinkboxStoke",
  aWSComputeThinkboxXMesh: "AWSComputeThinkboxXMesh",
  aWSComputeThinkboxSequoia: "AWSComputeThinkboxSequoia",
  aWSComputeThinkboxFrost: "AWSComputeThinkboxFrost",
  aWSComputeParallelCluster: "AWSComputeParallelCluster",
  aWSContainersEKSAnywhere: "AWSContainersEKSAnywhere",
  aWSComputeWavelength: "AWSComputeWavelength",
  aWSContainersEKSDistro: "AWSContainersEKSDistro",
  aWSContainersElasticKubernetesService:
    "AWSContainersElasticKubernetesService",
  aWSContainersFargate: "AWSContainersFargate",
  aWSComputeVMwareCloudonAWS: "AWSComputeVMwareCloudonAWS",
  aWSContainersElasticContainerRegistry:
    "AWSContainersElasticContainerRegistry",
  aWSContainersECSAnywhere: "AWSContainersECSAnywhere",
  aWSContainersEKSCloud: "AWSContainersEKSCloud",
  aWSDatabaseAurora: "AWSDatabaseAurora",
  aWSContainersRedHatOpenShiftServiceonAWS:
    "AWSContainersRedHatOpenShiftServiceonAWS",
  aWSDatabaseElastiCache: "AWSDatabaseElastiCache",
  aWSDatabaseNeptune: "AWSDatabaseNeptune",
  aWSDatabaseKeyspaces: "AWSDatabaseKeyspaces",
  aWSDatabaseDynamoDB: "AWSDatabaseDynamoDB",
  aWSDatabaseMemoryDBforRedis: "AWSDatabaseMemoryDBforRedis",
  aWSDatabaseDatabaseMigrationService: "AWSDatabaseDatabaseMigrationService",
  aWSDatabaseDocumentDB: "AWSDatabaseDocumentDB",
  aWSDatabaseRDSonVMware: "AWSDatabaseRDSonVMware",
  aWSDatabaseRDS: "AWSDatabaseRDS",
  aWSContainersElasticContainerService: "AWSContainersElasticContainerService",
  aWSFrontEndWebMobileDeviceFarm: "AWSFrontEndWebMobileDeviceFarm",
  aWSEndUserComputingAppStream: "AWSEndUserComputingAppStream",
  aWSFrontEndWebMobileAmplify: "AWSFrontEndWebMobileAmplify",
  aWSEndUserComputingWorkLink: "AWSEndUserComputingWorkLink",
  aWSDeveloperToolsApplicationComposer: "AWSDeveloperToolsApplicationComposer",
  aWSFrontEndWebMobileLocationService: "AWSFrontEndWebMobileLocationService",
  aWSDeveloperToolsCloudControlAPI: "AWSDeveloperToolsCloudControlAPI",
  aWSEndUserComputingWorkSpacesFamily: "AWSEndUserComputingWorkSpacesFamily",
  aWSDeveloperToolsCloudDevelopmentKit: "AWSDeveloperToolsCloudDevelopmentKit",
  aWSDeveloperToolsCodeArtifact: "AWSDeveloperToolsCodeArtifact",
  aWSDeveloperToolsCodeDeploy: "AWSDeveloperToolsCodeDeploy",
  aWSDeveloperToolsCloud9: "AWSDeveloperToolsCloud9",
  aWSDatabaseTimestream: "AWSDatabaseTimestream",
  aWSDeveloperToolsCodePipeline: "AWSDeveloperToolsCodePipeline",
  aWSDeveloperToolsCommandLineInterface:
    "AWSDeveloperToolsCommandLineInterface",
  aWSDeveloperToolsCodeCatalyst: "AWSDeveloperToolsCodeCatalyst",
  aWSDeveloperToolsCodeStar: "AWSDeveloperToolsCodeStar",
  aWSDeveloperToolsCloudShell: "AWSDeveloperToolsCloudShell",
  aWSDeveloperToolsCodeCommit: "AWSDeveloperToolsCodeCommit",
  aWSDeveloperToolsCorretto: "AWSDeveloperToolsCorretto",
  aWSDeveloperToolsCodeBuild: "AWSDeveloperToolsCodeBuild",
  aWSGamesGameSparks: "AWSGamesGameSparks",
  aWSGamesGameKit: "AWSGamesGameKit",
  aWSGamesGameLift: "AWSGamesGameLift",
  aWSDeveloperToolsToolsandSDKs: "AWSDeveloperToolsToolsandSDKs",
  aWSGamesOpen3DEngine: "AWSGamesOpen3DEngine",
  aWSGeneralIconsMarketplace_Dark: "AWSGeneralIconsMarketplace_Dark",
  aWSDeveloperToolsXRay: "AWSDeveloperToolsXRay",
  aWSGeneralIconsMarketplace_: "AWSGeneralIconsMarketplace_",
  aWSGamesLumberyard: "AWSGamesLumberyard",
  aWSInternetofThingsFreeRTOS: "AWSInternetofThingsFreeRTOS",
  aWSInternetofThingsIoT1Click: "AWSInternetofThingsIoT1Click",
  aWSInternetofThingsIoTEduKit: "AWSInternetofThingsIoTEduKit",
  aWSInternetofThingsIoTCore: "AWSInternetofThingsIoTCore",
  aWSInternetofThingsIoTEvents: "AWSInternetofThingsIoTEvents",
  aWSInternetofThingsIoTDeviceDefender: "AWSInternetofThingsIoTDeviceDefender",
  aWSInternetofThingsIoTFleetWise: "AWSInternetofThingsIoTFleetWise",
  aWSInternetofThingsIoTGreengrass: "AWSInternetofThingsIoTGreengrass",
  aWSInternetofThingsIoTExpressLink: "AWSInternetofThingsIoTExpressLink",
  aWSInternetofThingsIoTDeviceManagement:
    "AWSInternetofThingsIoTDeviceManagement",
  aWSInternetofThingsIoTAnalytics: "AWSInternetofThingsIoTAnalytics",
  aWSInternetofThingsIoTSiteWise: "AWSInternetofThingsIoTSiteWise",
  aWSInternetofThingsIoTButton: "AWSInternetofThingsIoTButton",
  aWSInternetofThingsIoTTwinMaker: "AWSInternetofThingsIoTTwinMaker",
  aWSMachineLearningAugmentedAIA2I: "AWSMachineLearningAugmentedAIA2I",
  aWSInternetofThingsIoTRoboRunner: "AWSInternetofThingsIoTRoboRunner",
  aWSInternetofThingsIoTThingsGraph: "AWSInternetofThingsIoTThingsGraph",
  aWSMachineLearningCodeGuru: "AWSMachineLearningCodeGuru",
  aWSMachineLearningDeepLearningAMIs: "AWSMachineLearningDeepLearningAMIs",
  aWSMachineLearningDeepLearningContainers:
    "AWSMachineLearningDeepLearningContainers",
  aWSMachineLearningComprehend: "AWSMachineLearningComprehend",
  aWSMachineLearningDeepLens: "AWSMachineLearningDeepLens",
  aWSMachineLearningDeepComposer: "AWSMachineLearningDeepComposer",
  aWSMachineLearningComprehendMedical: "AWSMachineLearningComprehendMedical",
  aWSMachineLearningCodeWhisperer: "AWSMachineLearningCodeWhisperer",
  aWSMachineLearningApacheMXNetonAWS: "AWSMachineLearningApacheMXNetonAWS",
  aWSMachineLearningDevOpsGuru: "AWSMachineLearningDevOpsGuru",
  aWSMachineLearningHealthLake: "AWSMachineLearningHealthLake",
  aWSMachineLearningLex: "AWSMachineLearningLex",
  aWSMachineLearningElasticInference: "AWSMachineLearningElasticInference",
  aWSMachineLearningLookoutforEquipment:
    "AWSMachineLearningLookoutforEquipment",
  aWSMachineLearningKendra: "AWSMachineLearningKendra",
  aWSMachineLearningLookoutforMetrics: "AWSMachineLearningLookoutforMetrics",
  aWSMachineLearningDeepRacer: "AWSMachineLearningDeepRacer",
  aWSMachineLearningFraudDetector: "AWSMachineLearningFraudDetector",
  aWSMachineLearningNeuron: "AWSMachineLearningNeuron",
  aWSMachineLearningPanorama: "AWSMachineLearningPanorama",
  aWSMachineLearningLookoutforVision: "AWSMachineLearningLookoutforVision",
  aWSMachineLearningOmics: "AWSMachineLearningOmics",
  aWSMachineLearningMonitron: "AWSMachineLearningMonitron",
  aWSMachineLearningSageMaker: "AWSMachineLearningSageMaker",
  aWSMachineLearningForecast: "AWSMachineLearningForecast",
  aWSMachineLearningPersonalize: "AWSMachineLearningPersonalize",
  aWSMachineLearningSageMakerGroundTruth:
    "AWSMachineLearningSageMakerGroundTruth",
  aWSMachineLearningTensorFlowonAWS: "AWSMachineLearningTensorFlowonAWS",
  aWSMachineLearningTranscribe: "AWSMachineLearningTranscribe",
  aWSMachineLearningTextract: "AWSMachineLearningTextract",
  aWSMachineLearningTranslate: "AWSMachineLearningTranslate",
  aWSMachineLearningPolly: "AWSMachineLearningPolly",
  aWSMachineLearningTorchServe: "AWSMachineLearningTorchServe",
  aWSMachineLearningSageMakerStudioLab: "AWSMachineLearningSageMakerStudioLab",
  aWSMigrationTransferApplicationDiscoveryService:
    "AWSMigrationTransferApplicationDiscoveryService",
  aWSMigrationTransferMigrationEvaluator:
    "AWSMigrationTransferMigrationEvaluator",
  aWSMigrationTransferDataSync: "AWSMigrationTransferDataSync",
  aWSMachineLearningRekognition: "AWSMachineLearningRekognition",
  aWSMigrationTransferMigrationHub: "AWSMigrationTransferMigrationHub",
  aWSMigrationTransferTransferFamily: "AWSMigrationTransferTransferFamily",
  aWSMigrationTransferMainframeModernization:
    "AWSMigrationTransferMainframeModernization",
  aWSMediaServicesElasticTranscoder: "AWSMediaServicesElasticTranscoder",
  aWSMediaServicesElementalAppliancesSoftware:
    "AWSMediaServicesElementalAppliancesSoftware",
  aWSMigrationTransferServerMigrationService:
    "AWSMigrationTransferServerMigrationService",
  aWSMediaServicesElementalLink: "AWSMediaServicesElementalLink",
  aWSMigrationTransferApplicationMigrationService:
    "AWSMigrationTransferApplicationMigrationService",
  aWSMediaServicesElementalDelta: "AWSMediaServicesElementalDelta",
  aWSMediaServicesElementalLive: "AWSMediaServicesElementalLive",
  aWSMediaServicesElementalMediaLive: "AWSMediaServicesElementalMediaLive",
  aWSMediaServicesElementalMediaConnect:
    "AWSMediaServicesElementalMediaConnect",
  aWSMediaServicesElementalMediaPackage:
    "AWSMediaServicesElementalMediaPackage",
  aWSMediaServicesElementalMediaTailor: "AWSMediaServicesElementalMediaTailor",
  aWSMediaServicesElementalServer: "AWSMediaServicesElementalServer",
  aWSMediaServicesElementalMediaStore: "AWSMediaServicesElementalMediaStore",
  aWSMediaServicesElementalConductor: "AWSMediaServicesElementalConductor",
  aWSMediaServicesInteractiveVideoService:
    "AWSMediaServicesInteractiveVideoService",
  aWSMediaServicesKinesisVideoStreams: "AWSMediaServicesKinesisVideoStreams",
  aWSMediaServicesElementalMediaConvert:
    "AWSMediaServicesElementalMediaConvert",
  aWSMediaServicesNimbleStudio: "AWSMediaServicesNimbleStudio",
  aWSNetworkingContentDeliveryClientVPN:
    "AWSNetworkingContentDeliveryClientVPN",
  aWSNetworkingContentDeliveryCloudDirectory:
    "AWSNetworkingContentDeliveryCloudDirectory",
  aWSQuantumTechnologiesBraket: "AWSQuantumTechnologiesBraket",
  aWSRoboticsRoboMaker: "AWSRoboticsRoboMaker",
  aWSNetworkingContentDeliveryElasticLoadBalancing:
    "AWSNetworkingContentDeliveryElasticLoadBalancing",
  aWSNetworkingContentDeliveryCloudMap: "AWSNetworkingContentDeliveryCloudMap",
  aWSNetworkingContentDeliveryCloudFront:
    "AWSNetworkingContentDeliveryCloudFront",
  aWSNetworkingContentDeliveryGlobalAccelerator:
    "AWSNetworkingContentDeliveryGlobalAccelerator",
  aWSNetworkingContentDeliveryDirectConnect:
    "AWSNetworkingContentDeliveryDirectConnect",
  aWSSatelliteGroundStation: "AWSSatelliteGroundStation",
  aWSNetworkingContentDeliveryAppMesh: "AWSNetworkingContentDeliveryAppMesh",
  aWSNetworkingContentDeliveryPrivateLink:
    "AWSNetworkingContentDeliveryPrivateLink",
  aWSNetworkingContentDeliverySitetoSiteVPN:
    "AWSNetworkingContentDeliverySitetoSiteVPN",
  aWSNetworkingContentDeliveryCloudWAN: "AWSNetworkingContentDeliveryCloudWAN",
  aWSNetworkingContentDeliveryRoute53: "AWSNetworkingContentDeliveryRoute53",
  aWSNetworkingContentDeliveryVPCLattice:
    "AWSNetworkingContentDeliveryVPCLattice",
  aWSNetworkingContentDeliveryPrivate5G:
    "AWSNetworkingContentDeliveryPrivate5G",
  aWSNetworkingContentDeliveryVerifiedAccess:
    "AWSNetworkingContentDeliveryVerifiedAccess",
  aWSNetworkingContentDeliveryTransitGateway:
    "AWSNetworkingContentDeliveryTransitGateway",
  aWSNetworkingContentDeliveryVirtualPrivateCloud:
    "AWSNetworkingContentDeliveryVirtualPrivateCloud",
  aWSManagementGovernanceAutoScaling: "AWSManagementGovernanceAutoScaling",
  aWSManagementGovernanceAppConfig: "AWSManagementGovernanceAppConfig",
  aWSManagementGovernanceBackintAgent: "AWSManagementGovernanceBackintAgent",
  aWSManagementGovernanceCloudWatch: "AWSManagementGovernanceCloudWatch",
  aWSManagementGovernanceControlTower: "AWSManagementGovernanceControlTower",
  aWSManagementGovernanceCloudFormation:
    "AWSManagementGovernanceCloudFormation",
  aWSManagementGovernanceCloudTrail: "AWSManagementGovernanceCloudTrail",
  aWSManagementGovernanceApplicationAutoScaling:
    "AWSManagementGovernanceApplicationAutoScaling",
  aWSManagementGovernanceChatbot: "AWSManagementGovernanceChatbot",
  aWSManagementGovernanceDistroforOpenTelemetry:
    "AWSManagementGovernanceDistroforOpenTelemetry",
  aWSManagementGovernanceManagedGrafana:
    "AWSManagementGovernanceManagedGrafana",
  aWSManagementGovernanceLicenseManager:
    "AWSManagementGovernanceLicenseManager",
  aWSManagementGovernanceFaultInjectionSimulator:
    "AWSManagementGovernanceFaultInjectionSimulator",
  aWSManagementGovernanceLaunchWizard: "AWSManagementGovernanceLaunchWizard",
  aWSManagementGovernanceManagedServiceforPrometheus:
    "AWSManagementGovernanceManagedServiceforPrometheus",
  aWSManagementGovernanceProton: "AWSManagementGovernanceProton",
  aWSManagementGovernanceOrganizations: "AWSManagementGovernanceOrganizations",
  aWSManagementGovernanceOpsWorks: "AWSManagementGovernanceOpsWorks",
  aWSManagementGovernanceResilienceHub: "AWSManagementGovernanceResilienceHub",
  aWSManagementGovernanceConfig: "AWSManagementGovernanceConfig",
  aWSManagementGovernanceSystemsManager:
    "AWSManagementGovernanceSystemsManager",
  aWSManagementGovernancePersonalHealthDashboard:
    "AWSManagementGovernancePersonalHealthDashboard",
  aWSManagementGovernanceServiceCatalog:
    "AWSManagementGovernanceServiceCatalog",
  aWSManagementGovernanceResourceExplorer:
    "AWSManagementGovernanceResourceExplorer",
  aWSManagementGovernanceServiceManagementConnector:
    "AWSManagementGovernanceServiceManagementConnector",
  aWSManagementGovernanceWellArchitectedTool:
    "AWSManagementGovernanceWellArchitectedTool",
  aWSManagementGovernanceTrustedAdvisor:
    "AWSManagementGovernanceTrustedAdvisor",
  aWSStorageBackup: "AWSStorageBackup",
  aWSVRARSumerian: "AWSVRARSumerian",
  aWSManagementGovernanceManagementConsole:
    "AWSManagementGovernanceManagementConsole",
  aWSStorageEFS: "AWSStorageEFS",
  aWSStorageElasticDisasterRecovery: "AWSStorageElasticDisasterRecovery",
  aWSStorageFSxforLustre: "AWSStorageFSxforLustre",
  aWSStorageFSxforNetAppONTAP: "AWSStorageFSxforNetAppONTAP",
  aWSStorageElasticBlockStore: "AWSStorageElasticBlockStore",
  aWSStorageFSxforOpenZFS: "AWSStorageFSxforOpenZFS",
  aWSStorageFileCache: "AWSStorageFileCache",
  aWSStorageS3onOutposts: "AWSStorageS3onOutposts",
  aWSStorageFSxforWFS: "AWSStorageFSxforWFS",
  aWSStorageFSx: "AWSStorageFSx",
  aWSStorageSnowballEdge: "AWSStorageSnowballEdge",
  aWSStorageStorageGateway: "AWSStorageStorageGateway",
  aWSStorageSnowmobile: "AWSStorageSnowmobile",
  aWSStorageSnowcone: "AWSStorageSnowcone",
  aWSSecurityIdentityComplianceCloudDirectory:
    "AWSSecurityIdentityComplianceCloudDirectory",
  aWSStorageSnowball: "AWSStorageSnowball",
  aWSSecurityIdentityComplianceCertificateManager:
    "AWSSecurityIdentityComplianceCertificateManager",
  aWSSecurityIdentityComplianceCognito: "AWSSecurityIdentityComplianceCognito",
  aWSStorageSimpleStorageService: "AWSStorageSimpleStorageService",
  aWSSecurityIdentityComplianceAuditManager:
    "AWSSecurityIdentityComplianceAuditManager",
  aWSStorageSimpleStorageServiceGlacier:
    "AWSStorageSimpleStorageServiceGlacier",
  aWSSecurityIdentityComplianceDetective:
    "AWSSecurityIdentityComplianceDetective",
  aWSSecurityIdentityComplianceArtifact:
    "AWSSecurityIdentityComplianceArtifact",
  aWSSecurityIdentityComplianceDirectoryService:
    "AWSSecurityIdentityComplianceDirectoryService",
  aWSSecurityIdentityComplianceIAMIdentityCenter:
    "AWSSecurityIdentityComplianceIAMIdentityCenter",
  aWSSecurityIdentityComplianceFirewallManager:
    "AWSSecurityIdentityComplianceFirewallManager",
  aWSSecurityIdentityComplianceIdentityandAccessManagement:
    "AWSSecurityIdentityComplianceIdentityandAccessManagement",
  aWSSecurityIdentityComplianceGuardDuty:
    "AWSSecurityIdentityComplianceGuardDuty",
  aWSSecurityIdentityComplianceInspector:
    "AWSSecurityIdentityComplianceInspector",
  aWSSecurityIdentityComplianceCloudHSM:
    "AWSSecurityIdentityComplianceCloudHSM",
  aWSSecurityIdentityComplianceResourceAccessManager:
    "AWSSecurityIdentityComplianceResourceAccessManager",
  aWSSecurityIdentityComplianceNetworkFirewall:
    "AWSSecurityIdentityComplianceNetworkFirewall",
  aWSSecurityIdentityComplianceSecretsManager:
    "AWSSecurityIdentityComplianceSecretsManager",
  aWSSecurityIdentityComplianceKeyManagementService:
    "AWSSecurityIdentityComplianceKeyManagementService",
  aWSSecurityIdentityComplianceMacie: "AWSSecurityIdentityComplianceMacie",
  aWSSecurityIdentityComplianceSecurityHub:
    "AWSSecurityIdentityComplianceSecurityHub",
  aWSSecurityIdentityComplianceShield: "AWSSecurityIdentityComplianceShield",
  aWSSecurityIdentityCompliancePrivateCertificateAuthority:
    "AWSSecurityIdentityCompliancePrivateCertificateAuthority",
  aWSSecurityIdentityComplianceSecurityLake:
    "AWSSecurityIdentityComplianceSecurityLake",
  aWSSecurityIdentityComplianceSigner: "AWSSecurityIdentityComplianceSigner",
  aWSSecurityIdentityComplianceVerifiedPermissions:
    "AWSSecurityIdentityComplianceVerifiedPermissions",
  aWSSecurityIdentityComplianceWAF: "AWSSecurityIdentityComplianceWAF",
};

export const SkillIcons = {
  skillIconActivityPub: {
    name: "Activity Pub",
    icon: "SkillIconActivityPub",
  },
  skillIconAbleton: { name: "Ableton", icon: "SkillIconAbleton" },
  skillIconAWS: { name: "A W S", icon: "SkillIconAWS" },
  skillIconAfterEffects: {
    name: "After Effects",
    icon: "SkillIconAfterEffects",
  },
  skillIconAndroidStudio: {
    name: "Android Studio",
    icon: "SkillIconAndroidStudio",
  },
  skillIconAlpineJS: { name: "Alpine J S", icon: "SkillIconAlpineJS" },
  skillIconAngular: { name: "Angular", icon: "SkillIconAngular" },
  skillIconAnaconda: { name: "Anaconda", icon: "SkillIconAnaconda" },
  skillIconAiScript: { name: "Ai Script", icon: "SkillIconAiScript" },
  skillIconAnsible: { name: "Ansible", icon: "SkillIconAnsible" },
  skillIconAppwrite: { name: "Appwrite", icon: "SkillIconAppwrite" },
  skillIconActix: { name: "Actix", icon: "SkillIconActix" },
  skillIconAstro: { name: "Astro", icon: "SkillIconAstro" },
  skillIconApple: { name: "Apple", icon: "SkillIconApple" },
  skillIconArduino: { name: "Arduino", icon: "SkillIconArduino" },
  skillIconApollo: { name: "Apollo", icon: "SkillIconApollo" },
  skillIconAzul: { name: "Azul", icon: "SkillIconAzul" },
  skillIconAudition: { name: "Audition", icon: "SkillIconAudition" },
  skillIconAdonis: { name: "Adonis", icon: "SkillIconAdonis" },
  skillIconAzure: { name: "Azure", icon: "SkillIconAzure" },
  skillIconAutoCAD: { name: "Auto C A D", icon: "SkillIconAutoCAD" },
  skillIconBlender: { name: "Blender", icon: "SkillIconBlender" },
  skillIconArch: { name: "Arch", icon: "SkillIconArch" },
  skillIconBash: { name: "Bash", icon: "SkillIconBash" },
  skillIconBevy: { name: "Bevy", icon: "SkillIconBevy" },
  skillIconBootstrap: { name: "Bootstrap", icon: "SkillIconBootstrap" },
  skillIconBSD: { name: "B S D", icon: "SkillIconBSD" },
  skillIconCLion: { name: "C Lion", icon: "SkillIconCLion" },
  skillIconBun: { name: "Bun", icon: "SkillIconBun" },
  skillIconC: { name: "C", icon: "SkillIconC" },
  skillIconBitBucket: { name: "Bit Bucket", icon: "SkillIconBitBucket" },
  skillIconCMake: { name: "C Make", icon: "SkillIconCMake" },
  skillIconAtom: { name: "Atom", icon: "SkillIconAtom" },
  skillIconCSS: { name: "C S S", icon: "SkillIconCSS" },
  skillIconCPP: { name: "C P P", icon: "SkillIconCPP" },
  skillIconCS: { name: "C S", icon: "SkillIconCS" },
  skillIconCloudflare: {
    name: "Cloudflare",
    icon: "SkillIconCloudflare",
  },
  skillIconClojure: { name: "Clojure", icon: "SkillIconClojure" },
  skillIconCodePen: { name: "Code Pen", icon: "SkillIconCodePen" },
  skillIconCassandra: { name: "Cassandra", icon: "SkillIconCassandra" },
  skillIconCrystal: { name: "Crystal", icon: "SkillIconCrystal" },
  skillIconDart: { name: "Dart", icon: "SkillIconDart" },
  skillIconCypress: { name: "Cypress", icon: "SkillIconCypress" },
  skillIconDENO: { name: "D E N O", icon: "SkillIconDENO" },
  skillIconCoffeeScript: {
    name: "Coffee Script",
    icon: "SkillIconCoffeeScript",
  },
  skillIconD3: { name: "D3", icon: "SkillIconD3" },
  skillIconDevTo: { name: "Dev To", icon: "SkillIconDevTo" },
  skillIconDiscord: { name: "Discord", icon: "SkillIconDiscord" },
  skillIconDiscordJS: { name: "Discord J S", icon: "SkillIconDiscordJS" },
  skillIconDjango: { name: "Django", icon: "SkillIconDjango" },
  skillIconBabel: { name: "Babel", icon: "SkillIconBabel" },
  skillIconDiscordBots: {
    name: "Discord Bots",
    icon: "SkillIconDiscordBots",
  },
  skillIconDotNet: { name: "Dot Net", icon: "SkillIconDotNet" },
  skillIconDynamoDB: { name: "Dynamo D B", icon: "SkillIconDynamoDB" },
  skillIconDocker: { name: "Docker", icon: "SkillIconDocker" },
  skillIconElixir: { name: "Elixir", icon: "SkillIconElixir" },
  skillIconDebian: { name: "Debian", icon: "SkillIconDebian" },
  skillIconElasticsearch: {
    name: "Elasticsearch",
    icon: "SkillIconElasticsearch",
  },
  skillIconEmacs: { name: "Emacs", icon: "SkillIconEmacs" },
  skillIconElysia: { name: "Elysia", icon: "SkillIconElysia" },
  skillIconFastAPI: { name: "Fast A P I", icon: "SkillIconFastAPI" },
  skillIconElectron: { name: "Electron", icon: "SkillIconElectron" },
  skillIconEclipse: { name: "Eclipse", icon: "SkillIconEclipse" },
  skillIconEmber: { name: "Ember", icon: "SkillIconEmber" },
  skillIconFlutter: { name: "Flutter", icon: "SkillIconFlutter" },
  skillIconFediverse: { name: "Fediverse", icon: "SkillIconFediverse" },
  skillIconFortran: { name: "Fortran", icon: "SkillIconFortran" },
  skillIconExpressJS: { name: "Express J S", icon: "SkillIconExpressJS" },
  skillIconEmotion: { name: "Emotion", icon: "SkillIconEmotion" },
  skillIconGTK: { name: "G T K", icon: "SkillIconGTK" },
  skillIconFirebase: { name: "Firebase", icon: "SkillIconFirebase" },
  skillIconFigma: { name: "Figma", icon: "SkillIconFigma" },
  skillIconGCP: { name: "G C P", icon: "SkillIconGCP" },
  skillIconGherkin: { name: "Gherkin", icon: "SkillIconGherkin" },
  skillIconGit: { name: "Git", icon: "SkillIconGit" },
  skillIconGameMakerStudio: {
    name: "Game Maker Studio",
    icon: "SkillIconGameMakerStudio",
  },
  skillIconGithub: { name: "Github", icon: "SkillIconGithub" },
  skillIconGithubActions: {
    name: "Github Actions",
    icon: "SkillIconGithubActions",
  },
  skillIconFlask: { name: "Flask", icon: "SkillIconFlask" },
  skillIconGoLang: { name: "Go Lang", icon: "SkillIconGoLang" },
  skillIconGmail: { name: "Gmail", icon: "SkillIconGmail" },
  skillIconForth: { name: "Forth", icon: "SkillIconForth" },
  skillIconGraphQL: { name: "Graph Q L", icon: "SkillIconGraphQL" },
  skillIconGitLab: { name: "Git Lab", icon: "SkillIconGitLab" },
  skillIconGatsby: { name: "Gatsby", icon: "SkillIconGatsby" },
  skillIconGulp: { name: "Gulp", icon: "SkillIconGulp" },
  skillIconHaxe: { name: "Haxe", icon: "SkillIconHaxe" },
  skillIconHaskell: { name: "Haskell", icon: "SkillIconHaskell" },
  skillIconHTML: { name: "H T M L", icon: "SkillIconHTML" },
  skillIconGrafana: { name: "Grafana", icon: "SkillIconGrafana" },
  skillIconHeroku: { name: "Heroku", icon: "SkillIconHeroku" },
  skillIconHaxeFlixel: {
    name: "Haxe Flixel",
    icon: "SkillIconHaxeFlixel",
  },
  skillIconHibernate: { name: "Hibernate", icon: "SkillIconHibernate" },
  skillIconGradle: { name: "Gradle", icon: "SkillIconGradle" },
  skillIconHtmx: { name: "Htmx", icon: "SkillIconHtmx" },
  skillIconGodot: { name: "Godot", icon: "SkillIconGodot" },
  skillIconIPFS: { name: "I P F S", icon: "SkillIconIPFS" },
  skillIconIdea: { name: "Idea", icon: "SkillIconIdea" },
  skillIconInstagram: { name: "Instagram", icon: "SkillIconInstagram" },
  skillIconJava: { name: "Java", icon: "SkillIconJava" },
  skillIconIllustrator: {
    name: "Illustrator",
    icon: "SkillIconIllustrator",
  },
  skillIconJenkins: { name: "Jenkins", icon: "SkillIconJenkins" },
  skillIconJest: { name: "Jest", icon: "SkillIconJest" },
  skillIconJQuery: { name: "J Query", icon: "SkillIconJQuery" },
  skillIconJavaScript: {
    name: "Java Script",
    icon: "SkillIconJavaScript",
  },
  skillIconKubernetes: {
    name: "Kubernetes",
    icon: "SkillIconKubernetes",
  },
  skillIconKotlin: { name: "Kotlin", icon: "SkillIconKotlin" },
  skillIconLaravel: { name: "Laravel", icon: "SkillIconLaravel" },
  skillIconLinkedIn: { name: "Linked In", icon: "SkillIconLinkedIn" },
  skillIconKali: { name: "Kali", icon: "SkillIconKali" },
  skillIconKafka: { name: "Kafka", icon: "SkillIconKafka" },
  skillIconLit: { name: "Lit", icon: "SkillIconLit" },
  skillIconMarkdown: { name: "Markdown", icon: "SkillIconMarkdown" },
  skillIconJulia: { name: "Julia", icon: "SkillIconJulia" },
  skillIconLaTeX: { name: "La Te X", icon: "SkillIconLaTeX" },
  skillIconLua: { name: "Lua", icon: "SkillIconLua" },
  skillIconMastodon: { name: "Mastodon", icon: "SkillIconMastodon" },
  skillIconLess: { name: "Less", icon: "SkillIconLess" },
  skillIconMatlab: { name: "Matlab", icon: "SkillIconMatlab" },
  skillIconMisskey: { name: "Misskey", icon: "SkillIconMisskey" },
  skillIconMaterialUI: {
    name: "Material U I",
    icon: "SkillIconMaterialUI",
  },
  skillIconMongoDB: { name: "Mongo D B", icon: "SkillIconMongoDB" },
  skillIconKtor: { name: "Ktor", icon: "SkillIconKtor" },
  skillIconMint: { name: "Mint", icon: "SkillIconMint" },
  skillIconLinux: { name: "Linux", icon: "SkillIconLinux" },
  skillIconMySQL: { name: "My S Q L", icon: "SkillIconMySQL" },
  skillIconMaven: { name: "Maven", icon: "SkillIconMaven" },
  skillIconNeoVim: { name: "Neo Vim", icon: "SkillIconNeoVim" },
  skillIconNim: { name: "Nim", icon: "SkillIconNim" },
  skillIconNextJS: { name: "Next J S", icon: "SkillIconNextJS" },
  skillIconNix: { name: "Nix", icon: "SkillIconNix" },
  skillIconNginx: { name: "Nginx", icon: "SkillIconNginx" },
  skillIconNestJS: { name: "Nest J S", icon: "SkillIconNestJS" },
  skillIconNpm: { name: "Npm", icon: "SkillIconNpm" },
  skillIconNetlify: { name: "Netlify", icon: "SkillIconNetlify" },
  skillIconNuxtJS: { name: "Nuxt J S", icon: "SkillIconNuxtJS" },
  skillIconNodeJS: { name: "Node J S", icon: "SkillIconNodeJS" },
  skillIconNotion: { name: "Notion", icon: "SkillIconNotion" },
  skillIconOpenCV: { name: "Open C V", icon: "SkillIconOpenCV" },
  skillIconOctave: { name: "Octave", icon: "SkillIconOctave" },
  skillIconPHP: { name: "P H P", icon: "SkillIconPHP" },
  skillIconOpenStack: { name: "Open Stack", icon: "SkillIconOpenStack" },
  skillIconPhotoshop: { name: "Photoshop", icon: "SkillIconPhotoshop" },
  skillIconOpenShift: { name: "Open Shift", icon: "SkillIconOpenShift" },
  skillIconPhpStorm: { name: "Php Storm", icon: "SkillIconPhpStorm" },
  skillIconPkl: { name: "Pkl", icon: "SkillIconPkl" },
  skillIconObsidian: { name: "Obsidian", icon: "SkillIconObsidian" },
  skillIconPinia: { name: "Pinia", icon: "SkillIconPinia" },
  skillIconPnpm: { name: "Pnpm", icon: "SkillIconPnpm" },
  skillIconPostgreSQL: {
    name: "Postgre S Q L",
    icon: "SkillIconPostgreSQL",
  },
  skillIconPerl: { name: "Perl", icon: "SkillIconPerl" },
  skillIconPlan9: { name: "Plan9", icon: "SkillIconPlan9" },
  skillIconPowershell: {
    name: "Powershell",
    icon: "SkillIconPowershell",
  },
  skillIconOCaml: { name: "O Caml", icon: "SkillIconOCaml" },
  skillIconPrisma: { name: "Prisma", icon: "SkillIconPrisma" },
  skillIconPremiere: { name: "Premiere", icon: "SkillIconPremiere" },
  skillIconPyCharm: { name: "Py Charm", icon: "SkillIconPyCharm" },
  skillIconProcessing: {
    name: "Processing",
    icon: "SkillIconProcessing",
  },
  skillIconPlanetScale: {
    name: "Planet Scale",
    icon: "SkillIconPlanetScale",
  },
  skillIconR: { name: "R", icon: "SkillIconR" },
  skillIconPrometheus: {
    name: "Prometheus",
    icon: "SkillIconPrometheus",
  },
  skillIconPostman: { name: "Postman", icon: "SkillIconPostman" },
  skillIconPyTorch: { name: "Py Torch", icon: "SkillIconPyTorch" },
  skillIconRails: { name: "Rails", icon: "SkillIconRails" },
  skillIconPug: { name: "Pug", icon: "SkillIconPug" },
  skillIconPython: { name: "Python", icon: "SkillIconPython" },
  skillIconROS: { name: "R O S", icon: "SkillIconROS" },
  skillIconQT: { name: "Q T", icon: "SkillIconQT" },
  skillIconRedis: { name: "Redis", icon: "SkillIconRedis" },
  skillIconRabbitMQ: { name: "Rabbit M Q", icon: "SkillIconRabbitMQ" },
  skillIconReactiveX: { name: "Reactive X", icon: "SkillIconReactiveX" },
  skillIconRaspberryPi: {
    name: "Raspberry Pi",
    icon: "SkillIconRaspberryPi",
  },
  skillIconReact: { name: "React", icon: "SkillIconReact" },
  skillIconReplit: { name: "Replit", icon: "SkillIconReplit" },
  skillIconRemix: { name: "Remix", icon: "SkillIconRemix" },
  skillIconRedHat: { name: "Red Hat", icon: "SkillIconRedHat" },
  skillIconRust: { name: "Rust", icon: "SkillIconRust" },
  skillIconRocket: { name: "Rocket", icon: "SkillIconRocket" },
  skillIconRider: { name: "Rider", icon: "SkillIconRider" },
  skillIconRollupJS: { name: "Rollup J S", icon: "SkillIconRollupJS" },
  skillIconSVG: { name: "S V G", icon: "SkillIconSVG" },
  skillIconRegex: { name: "Regex", icon: "SkillIconRegex" },
  skillIconSQLite: { name: "S Q Lite", icon: "SkillIconSQLite" },
  skillIconRuby: { name: "Ruby", icon: "SkillIconRuby" },
  skillIconSentry: { name: "Sentry", icon: "SkillIconSentry" },
  skillIconSketchup: { name: "Sketchup", icon: "SkillIconSketchup" },
  skillIconSciKitLearn: {
    name: "Sci Kit Learn",
    icon: "SkillIconSciKitLearn",
  },
  skillIconSass: { name: "Sass", icon: "SkillIconSass" },
  skillIconSolidJS: { name: "Solid J S", icon: "SkillIconSolidJS" },
  skillIconSelenium: { name: "Selenium", icon: "SkillIconSelenium" },
  skillIconRobloxStudio: {
    name: "Roblox Studio",
    icon: "SkillIconRobloxStudio",
  },
  skillIconSequelize: { name: "Sequelize", icon: "SkillIconSequelize" },
  skillIconStackOverflow: {
    name: "Stack Overflow",
    icon: "SkillIconStackOverflow",
  },
  skillIconScala: { name: "Scala", icon: "SkillIconScala" },
  skillIconSolidity: { name: "Solidity", icon: "SkillIconSolidity" },
  skillIconRedux: { name: "Redux", icon: "SkillIconRedux" },
  skillIconSupabase: { name: "Supabase", icon: "SkillIconSupabase" },
  skillIconSpring: { name: "Spring", icon: "SkillIconSpring" },
  skillIconSwift: { name: "Swift", icon: "SkillIconSwift" },
  skillIconTauri: { name: "Tauri", icon: "SkillIconTauri" },
  skillIconTerraform: { name: "Terraform", icon: "SkillIconTerraform" },
  skillIconSublime: { name: "Sublime", icon: "SkillIconSublime" },
  skillIconSvelte: { name: "Svelte", icon: "SkillIconSvelte" },
  skillIconTailwindCSS: {
    name: "Tailwind C S S",
    icon: "SkillIconTailwindCSS",
  },
  skillIconThreeJS: { name: "Three J S", icon: "SkillIconThreeJS" },
  skillIconSymfony: { name: "Symfony", icon: "SkillIconSymfony" },
  skillIconTypeScript: {
    name: "Type Script",
    icon: "SkillIconTypeScript",
  },
  skillIconTwitter: { name: "Twitter", icon: "SkillIconTwitter" },
  skillIconUbuntu: { name: "Ubuntu", icon: "SkillIconUbuntu" },
  skillIconStyledComponents: {
    name: "Styled Components",
    icon: "SkillIconStyledComponents",
  },
  skillIconVSCode: { name: "V S Code", icon: "SkillIconVSCode" },
  skillIconVSCodium: { name: "V S Codium", icon: "SkillIconVSCodium" },
  skillIconVIM: { name: "V I M", icon: "SkillIconVIM" },
  skillIconUnrealEngine: {
    name: "Unreal Engine",
    icon: "SkillIconUnrealEngine",
  },
  skillIconVala: { name: "Vala", icon: "SkillIconVala" },
  skillIconV: { name: "V", icon: "SkillIconV" },
  skillIconVitest: { name: "Vitest", icon: "SkillIconVitest" },
  skillIconVercel: { name: "Vercel", icon: "SkillIconVercel" },
  skillIconVueJS: { name: "Vue J S", icon: "SkillIconVueJS" },
  skillIconWebAssembly: {
    name: "Web Assembly",
    icon: "SkillIconWebAssembly",
  },
  skillIconWebStorm: { name: "Web Storm", icon: "SkillIconWebStorm" },
  skillIconWindiCSS: { name: "Windi C S S", icon: "SkillIconWindiCSS" },
  skillIconWebpack: { name: "Webpack", icon: "SkillIconWebpack" },
  skillIconWindows: { name: "Windows", icon: "SkillIconWindows" },
  skillIconVisualStudio: {
    name: "Visual Studio",
    icon: "SkillIconVisualStudio",
  },
  skillIconWordpress: { name: "Wordpress", icon: "SkillIconWordpress" },
  skillIconTensorFlow: {
    name: "Tensor Flow",
    icon: "SkillIconTensorFlow",
  },
  skillIconWorkers: { name: "Workers", icon: "SkillIconWorkers" },
  skillIconYarn: { name: "Yarn", icon: "SkillIconYarn" },
  skillIconWebflow: { name: "Webflow", icon: "SkillIconWebflow" },
  skillIconUnity: { name: "Unity", icon: "SkillIconUnity" },
  skillIconXD: { name: "X D", icon: "SkillIconXD" },
  skillIconVite: { name: "Vite", icon: "SkillIconVite" },
  skillIconZig: { name: "Zig", icon: "SkillIconZig" },
  skillIconVuetify: { name: "Vuetify", icon: "SkillIconVuetify" },
  skillIconYew: { name: "Yew", icon: "SkillIconYew" },
  skillIconp5js: { name: "P5js", icon: "SkillIconp5js" },
};
