interface IconNames {
  [key: string]: string;
}

export const IconNames: IconNames = {
  // Skill Icons
  skillIconAbleton: "SkillIconAbleton",
  skillIconActivityPub: "SkillIconActivityPub",
  skillIconAWS: "SkillIconAWS",
  skillIconAdonis: "SkillIconAdonis",
  skillIconAfterEffects: "SkillIconAfterEffects",
  skillIconAlpineJS: "SkillIconAlpineJS",
  skillIconAndroidStudio: "SkillIconAndroidStudio",
  skillIconAngular: "SkillIconAngular",
  skillIconAnsible: "SkillIconAnsible",
  skillIconApollo: "SkillIconApollo",
  skillIconAppwrite: "SkillIconAppwrite",
  skillIconAnaconda: "SkillIconAnaconda",
  skillIconAiScript: "SkillIconAiScript",
  skillIconActix: "SkillIconActix",
  skillIconArch: "SkillIconArch",
  skillIconArduino: "SkillIconArduino",
  skillIconApple: "SkillIconApple",
  skillIconAtom: "SkillIconAtom",
  skillIconAudition: "SkillIconAudition",
  skillIconAstro: "SkillIconAstro",
  skillIconAutoCAD: "SkillIconAutoCAD",
  skillIconAzul: "SkillIconAzul",
  skillIconAzure: "SkillIconAzure",
  skillIconBitBucket: "SkillIconBitBucket",
  skillIconBash: "SkillIconBash",
  skillIconBSD: "SkillIconBSD",
  skillIconC: "SkillIconC",
  skillIconBevy: "SkillIconBevy",
  skillIconCPP: "SkillIconCPP",
  skillIconCMake: "SkillIconCMake",
  skillIconCLion: "SkillIconCLion",
  skillIconBun: "SkillIconBun",
  skillIconBabel: "SkillIconBabel",
  skillIconBlender: "SkillIconBlender",
  skillIconCSS: "SkillIconCSS",
  skillIconCloudflare: "SkillIconCloudflare",
  skillIconClojure: "SkillIconClojure",
  skillIconCoffeeScript: "SkillIconCoffeeScript",
  skillIconCodePen: "SkillIconCodePen",
  skillIconCrystal: "SkillIconCrystal",
  skillIconD3: "SkillIconD3",
  skillIconBootstrap: "SkillIconBootstrap",
  skillIconCS: "SkillIconCS",
  skillIconCypress: "SkillIconCypress",
  skillIconDiscord: "SkillIconDiscord",
  skillIconDevTo: "SkillIconDevTo",
  skillIconCassandra: "SkillIconCassandra",
  skillIconDiscordBots: "SkillIconDiscordBots",
  skillIconDENO: "SkillIconDENO",
  skillIconDart: "SkillIconDart",
  skillIconDebian: "SkillIconDebian",
  skillIconDjango: "SkillIconDjango",
  skillIconDiscordJS: "SkillIconDiscordJS",
  skillIconDotNet: "SkillIconDotNet",
  skillIconDocker: "SkillIconDocker",
  skillIconEclipse: "SkillIconEclipse",
  skillIconElectron: "SkillIconElectron",
  skillIconElixir: "SkillIconElixir",
  skillIconEmacs: "SkillIconEmacs",
  skillIconElysia: "SkillIconElysia",
  skillIconEmber: "SkillIconEmber",
  skillIconExpressJS: "SkillIconExpressJS",
  skillIconElasticsearch: "SkillIconElasticsearch",
  skillIconFediverse: "SkillIconFediverse",
  skillIconDynamoDB: "SkillIconDynamoDB",
  skillIconFlutter: "SkillIconFlutter",
  skillIconFigma: "SkillIconFigma",
  skillIconGTK: "SkillIconGTK",
  skillIconFortran: "SkillIconFortran",
  skillIconEmotion: "SkillIconEmotion",
  skillIconForth: "SkillIconForth",
  skillIconFirebase: "SkillIconFirebase",
  skillIconFlask: "SkillIconFlask",
  skillIconGCP: "SkillIconGCP",
  skillIconFastAPI: "SkillIconFastAPI",
  skillIconGherkin: "SkillIconGherkin",
  skillIconGit: "SkillIconGit",
  skillIconGameMakerStudio: "SkillIconGameMakerStudio",
  skillIconGatsby: "SkillIconGatsby",
  skillIconGoLang: "SkillIconGoLang",
  skillIconGithub: "SkillIconGithub",
  skillIconGitLab: "SkillIconGitLab",
  skillIconGmail: "SkillIconGmail",
  skillIconHTML: "SkillIconHTML",
  skillIconGodot: "SkillIconGodot",
  skillIconGraphQL: "SkillIconGraphQL",
  skillIconHaskell: "SkillIconHaskell",
  skillIconHaxe: "SkillIconHaxe",
  skillIconGithubActions: "SkillIconGithubActions",
  skillIconGulp: "SkillIconGulp",
  skillIconHeroku: "SkillIconHeroku",
  skillIconGradle: "SkillIconGradle",
  skillIconHibernate: "SkillIconHibernate",
  skillIconHtmx: "SkillIconHtmx",
  skillIconIPFS: "SkillIconIPFS",
  skillIconIdea: "SkillIconIdea",
  skillIconIllustrator: "SkillIconIllustrator",
  skillIconHaxeFlixel: "SkillIconHaxeFlixel",
  skillIconJava: "SkillIconJava",
  skillIconGrafana: "SkillIconGrafana",
  skillIconInstagram: "SkillIconInstagram",
  skillIconJenkins: "SkillIconJenkins",
  skillIconJavaScript: "SkillIconJavaScript",
  skillIconJest: "SkillIconJest",
  skillIconKtor: "SkillIconKtor",
  skillIconJQuery: "SkillIconJQuery",
  skillIconKafka: "SkillIconKafka",
  skillIconKubernetes: "SkillIconKubernetes",
  skillIconKali: "SkillIconKali",
  skillIconKotlin: "SkillIconKotlin",
  skillIconJulia: "SkillIconJulia",
  skillIconLaravel: "SkillIconLaravel",
  skillIconLinkedIn: "SkillIconLinkedIn",
  skillIconLit: "SkillIconLit",
  skillIconMatlab: "SkillIconMatlab",
  skillIconMarkdown: "SkillIconMarkdown",
  skillIconLaTeX: "SkillIconLaTeX",
  skillIconMaterialUI: "SkillIconMaterialUI",
  skillIconMastodon: "SkillIconMastodon",
  skillIconMisskey: "SkillIconMisskey",
  skillIconLinux: "SkillIconLinux",
  skillIconMongoDB: "SkillIconMongoDB",
  skillIconLess: "SkillIconLess",
  skillIconMySQL: "SkillIconMySQL",
  skillIconNeoVim: "SkillIconNeoVim",
  skillIconMint: "SkillIconMint",
  skillIconLua: "SkillIconLua",
  skillIconNginx: "SkillIconNginx",
  skillIconNim: "SkillIconNim",
  skillIconNix: "SkillIconNix",
  skillIconNotion: "SkillIconNotion",
  skillIconNetlify: "SkillIconNetlify",
  skillIconMaven: "SkillIconMaven",
  skillIconNuxtJS: "SkillIconNuxtJS",
  skillIconOCaml: "SkillIconOCaml",
  skillIconNestJS: "SkillIconNestJS",
  skillIconOpenCV: "SkillIconOpenCV",
  skillIconOctave: "SkillIconOctave",
  skillIconObsidian: "SkillIconObsidian",
  skillIconNodeJS: "SkillIconNodeJS",
  skillIconOpenShift: "SkillIconOpenShift",
  skillIconOpenStack: "SkillIconOpenStack",
  skillIconNpm: "SkillIconNpm",
  skillIconPHP: "SkillIconPHP",
  skillIconPkl: "SkillIconPkl",
  skillIconPnpm: "SkillIconPnpm",
  skillIconPinia: "SkillIconPinia",
  skillIconPhpStorm: "SkillIconPhpStorm",
  skillIconPostgreSQL: "SkillIconPostgreSQL",
  skillIconPlanetScale: "SkillIconPlanetScale",
  skillIconPhotoshop: "SkillIconPhotoshop",
  skillIconPrisma: "SkillIconPrisma",
  skillIconPowershell: "SkillIconPowershell",
  skillIconPerl: "SkillIconPerl",
  skillIconPrometheus: "SkillIconPrometheus",
  skillIconPyCharm: "SkillIconPyCharm",
  skillIconPyTorch: "SkillIconPyTorch",
  skillIconPug: "SkillIconPug",
  skillIconPostman: "SkillIconPostman",
  skillIconNextJS: "SkillIconNextJS",
  skillIconPremiere: "SkillIconPremiere",
  skillIconPlan9: "SkillIconPlan9",
  skillIconProcessing: "SkillIconProcessing",
  skillIconQT: "SkillIconQT",
  skillIconROS: "SkillIconROS",
  skillIconRails: "SkillIconRails",
  skillIconR: "SkillIconR",
  skillIconRaspberryPi: "SkillIconRaspberryPi",
  skillIconRabbitMQ: "SkillIconRabbitMQ",
  skillIconPython: "SkillIconPython",
  skillIconReactiveX: "SkillIconReactiveX",
  skillIconReact: "SkillIconReact",
  skillIconRedis: "SkillIconRedis",
  skillIconRedHat: "SkillIconRedHat",
  skillIconRemix: "SkillIconRemix",
  skillIconRegex: "SkillIconRegex",
  skillIconReplit: "SkillIconReplit",
  skillIconRider: "SkillIconRider",
  skillIconRocket: "SkillIconRocket",
  skillIconSVG: "SkillIconSVG",
  skillIconSass: "SkillIconSass",
  skillIconRobloxStudio: "SkillIconRobloxStudio",
  skillIconRuby: "SkillIconRuby",
  skillIconScala: "SkillIconScala",
  skillIconRust: "SkillIconRust",
  skillIconRollupJS: "SkillIconRollupJS",
  skillIconSentry: "SkillIconSentry",
  skillIconSequelize: "SkillIconSequelize",
  skillIconSciKitLearn: "SkillIconSciKitLearn",
  skillIconSolidity: "SkillIconSolidity",
  skillIconSelenium: "SkillIconSelenium",
  skillIconStackOverflow: "SkillIconStackOverflow",
  skillIconStyledComponents: "SkillIconStyledComponents",
  skillIconSpring: "SkillIconSpring",
  skillIconSublime: "SkillIconSublime",
  skillIconSQLite: "SkillIconSQLite",
  skillIconSwift: "SkillIconSwift",
  skillIconSvelte: "SkillIconSvelte",
  skillIconSupabase: "SkillIconSupabase",
  skillIconSketchup: "SkillIconSketchup",
  skillIconRedux: "SkillIconRedux",
  skillIconTailwindCSS: "SkillIconTailwindCSS",
  skillIconSolidJS: "SkillIconSolidJS",
  skillIconTerraform: "SkillIconTerraform",
  skillIconSymfony: "SkillIconSymfony",
  skillIconTauri: "SkillIconTauri",
  skillIconUnrealEngine: "SkillIconUnrealEngine",
  skillIconTwitter: "SkillIconTwitter",
  skillIconUnity: "SkillIconUnity",
  skillIconTensorFlow: "SkillIconTensorFlow",
  skillIconVIM: "SkillIconVIM",
  skillIconVSCodium: "SkillIconVSCodium",
  skillIconUbuntu: "SkillIconUbuntu",
  skillIconVSCode: "SkillIconVSCode",
  skillIconVercel: "SkillIconVercel",
  skillIconThreeJS: "SkillIconThreeJS",
  skillIconVite: "SkillIconVite",
  skillIconTypeScript: "SkillIconTypeScript",
  skillIconVala: "SkillIconVala",
  skillIconV: "SkillIconV",
  skillIconVitest: "SkillIconVitest",
  skillIconWebAssembly: "SkillIconWebAssembly",
  skillIconVisualStudio: "SkillIconVisualStudio",
  skillIconVueJS: "SkillIconVueJS",
  skillIconWebflow: "SkillIconWebflow",
  skillIconWindiCSS: "SkillIconWindiCSS",
  skillIconWindows: "SkillIconWindows",
  skillIconWebpack: "SkillIconWebpack",
  skillIconVuetify: "SkillIconVuetify",
  skillIconXD: "SkillIconXD",
  skillIconWordpress: "SkillIconWordpress",
  skillIconWorkers: "SkillIconWorkers",
  skillIconYarn: "SkillIconYarn",
  skillIconWebStorm: "SkillIconWebStorm",
  skillIconYew: "SkillIconYew",
  skillIconZig: "SkillIconZig",
  skillIconp5js: "SkillIconp5js",

  // AWS Icons
  aWSAnalyticsCleanRooms: "AWSAnalyticsCleanRooms",
  aWSAnalyticsDataExchange: "AWSAnalyticsDataExchange",
  aWSAnalyticsAthena: "AWSAnalyticsAthena",
  aWSAnalyticsCloudSearch: "AWSAnalyticsCloudSearch",
  aWSAnalyticsDataZone: "AWSAnalyticsDataZone",
  aWSAnalyticsEMR: "AWSAnalyticsEMR",
  aWSAnalyticsGlueDataBrew: "AWSAnalyticsGlueDataBrew",
  aWSAnalyticsFinSpace: "AWSAnalyticsFinSpace",
  aWSAnalyticsGlueElasticViews: "AWSAnalyticsGlueElasticViews",
  aWSAnalyticsKinesisDataStreams: "AWSAnalyticsKinesisDataStreams",
  aWSAnalyticsGlue: "AWSAnalyticsGlue",
  aWSAnalyticsKinesisDataAnalytics: "AWSAnalyticsKinesisDataAnalytics",
  aWSAnalyticsDataPipeline: "AWSAnalyticsDataPipeline",
  aWSAnalyticsKinesisVideoStreams: "AWSAnalyticsKinesisVideoStreams",
  aWSAnalyticsKinesisFirehose: "AWSAnalyticsKinesisFirehose",
  aWSAnalyticsKinesis: "AWSAnalyticsKinesis",
  aWSAnalyticsLakeFormation: "AWSAnalyticsLakeFormation",
  aWSAnalyticsManagedStreamingforApacheKafka:
    "AWSAnalyticsManagedStreamingforApacheKafka",
  aWSAnalyticsQuickSight: "AWSAnalyticsQuickSight",
  aWSAnalyticsOpenSearchService: "AWSAnalyticsOpenSearchService",
  aWSAnalyticsRedshift: "AWSAnalyticsRedshift",
  aWSAppIntegrationAPIGateway: "AWSAppIntegrationAPIGateway",
  aWSAppIntegrationAppFlow: "AWSAppIntegrationAppFlow",
  aWSAppIntegrationEventBridge: "AWSAppIntegrationEventBridge",
  aWSBlockchainQuantumLedgerDatabase: "AWSBlockchainQuantumLedgerDatabase",
  aWSBlockchainManagedBlockchain: "AWSBlockchainManagedBlockchain",
  aWSAppIntegrationAppSync: "AWSAppIntegrationAppSync",
  aWSAppIntegrationSimpleNotificationService:
    "AWSAppIntegrationSimpleNotificationService",
  aWSAppIntegrationStepFunctions: "AWSAppIntegrationStepFunctions",
  aWSAppIntegrationManagedWorkflowsforApacheAirflow:
    "AWSAppIntegrationManagedWorkflowsforApacheAirflow",
  aWSBusinessApplicationsAlexaForBusiness:
    "AWSBusinessApplicationsAlexaForBusiness",
  aWSBusinessApplicationsChimeSDK: "AWSBusinessApplicationsChimeSDK",
  aWSAppIntegrationExpressWorkflows: "AWSAppIntegrationExpressWorkflows",
  aWSAppIntegrationConsoleMobileApplication:
    "AWSAppIntegrationConsoleMobileApplication",
  aWSAppIntegrationSimpleQueueService: "AWSAppIntegrationSimpleQueueService",
  aWSBusinessApplicationsChime: "AWSBusinessApplicationsChime",
  aWSBusinessApplicationsHoneycode: "AWSBusinessApplicationsHoneycode",
  aWSAppIntegrationMQ: "AWSAppIntegrationMQ",
  aWSBusinessApplicationsConnect: "AWSBusinessApplicationsConnect",
  aWSBusinessApplicationsPinpoint: "AWSBusinessApplicationsPinpoint",
  aWSBusinessApplicationsChimeVoiceConnector:
    "AWSBusinessApplicationsChimeVoiceConnector",
  aWSBusinessApplicationsSimpleEmailService:
    "AWSBusinessApplicationsSimpleEmailService",
  aWSBusinessApplicationsWickr: "AWSBusinessApplicationsWickr",
  aWSBusinessApplicationsWorkDocsSDK: "AWSBusinessApplicationsWorkDocsSDK",
  aWSCloudFinancialManagementApplicationCostProfiler:
    "AWSCloudFinancialManagementApplicationCostProfiler",
  aWSCloudFinancialManagementBillingConductor:
    "AWSCloudFinancialManagementBillingConductor",
  aWSBusinessApplicationsWorkMail: "AWSBusinessApplicationsWorkMail",
  aWSBusinessApplicationsWorkDocs: "AWSBusinessApplicationsWorkDocs",
  aWSBusinessApplicationsSupplyChain: "AWSBusinessApplicationsSupplyChain",
  aWSBusinessApplicationsPinpointAPIs: "AWSBusinessApplicationsPinpointAPIs",
  aWSCloudFinancialManagementBudgets: "AWSCloudFinancialManagementBudgets",
  aWSCloudFinancialManagementCostandUsageReport:
    "AWSCloudFinancialManagementCostandUsageReport",
  aWSCloudFinancialManagementCostExplorer:
    "AWSCloudFinancialManagementCostExplorer",
  aWSCloudFinancialManagementReservedInstanceReporting:
    "AWSCloudFinancialManagementReservedInstanceReporting",
  aWSCloudFinancialManagementSavingsPlans:
    "AWSCloudFinancialManagementSavingsPlans",
  aWSCustomerEnablementTrainingCertification:
    "AWSCustomerEnablementTrainingCertification",
  aWSCustomerEnablementActivate: "AWSCustomerEnablementActivate",
  aWSCustomerEnablementIQ: "AWSCustomerEnablementIQ",
  aWSCustomerEnablementManagedServices: "AWSCustomerEnablementManagedServices",
  aWSComputeApplicationAutoScaling: "AWSComputeApplicationAutoScaling",
  aWSCustomerEnablementRePost: "AWSCustomerEnablementRePost",
  aWSComputeEC2AutoScaling: "AWSComputeEC2AutoScaling",
  aWSCustomerEnablementSupport: "AWSCustomerEnablementSupport",
  aWSComputeBottlerocket: "AWSComputeBottlerocket",
  aWSCustomerEnablementProfessionalServices:
    "AWSCustomerEnablementProfessionalServices",
  aWSComputeEC2ImageBuilder: "AWSComputeEC2ImageBuilder",
  aWSComputeComputeOptimizer: "AWSComputeComputeOptimizer",
  aWSComputeEC2: "AWSComputeEC2",
  aWSComputeElasticFabricAdapter: "AWSComputeElasticFabricAdapter",
  aWSComputeAppRunner: "AWSComputeAppRunner",
  aWSComputeBatch: "AWSComputeBatch",
  aWSComputeElasticBeanstalk: "AWSComputeElasticBeanstalk",
  aWSComputeLambda: "AWSComputeLambda",
  aWSComputeNICEDCV: "AWSComputeNICEDCV",
  aWSComputeNICEEnginFrame: "AWSComputeNICEEnginFrame",
  aWSComputeLocalZones: "AWSComputeLocalZones",
  aWSComputeNitroEnclaves: "AWSComputeNitroEnclaves",
  aWSComputeGenomicsCLI: "AWSComputeGenomicsCLI",
  aWSComputeFargate: "AWSComputeFargate",
  aWSComputeOutpostsfamily: "AWSComputeOutpostsfamily",
  aWSComputeSail: "AWSComputeSail",
  aWSComputeOutpostsrack: "AWSComputeOutpostsrack",
  aWSComputeOutpostsservers: "AWSComputeOutpostsservers",
  aWSComputeServerlessApplicationRepository:
    "AWSComputeServerlessApplicationRepository",
  aWSComputeThinkboxKrakatoa: "AWSComputeThinkboxKrakatoa",
  aWSComputeThinkboxDeadline: "AWSComputeThinkboxDeadline",
  aWSComputeSimSpaceWeaver: "AWSComputeSimSpaceWeaver",
  aWSComputeThinkboxStoke: "AWSComputeThinkboxStoke",
  aWSComputeThinkboxXMesh: "AWSComputeThinkboxXMesh",
  aWSComputeThinkboxSequoia: "AWSComputeThinkboxSequoia",
  aWSComputeThinkboxFrost: "AWSComputeThinkboxFrost",
  aWSComputeParallelCluster: "AWSComputeParallelCluster",
  aWSContainersEKSAnywhere: "AWSContainersEKSAnywhere",
  aWSComputeWavelength: "AWSComputeWavelength",
  aWSContainersEKSDistro: "AWSContainersEKSDistro",
  aWSContainersElasticKubernetesService:
    "AWSContainersElasticKubernetesService",
  aWSContainersFargate: "AWSContainersFargate",
  aWSComputeVMwareCloudonAWS: "AWSComputeVMwareCloudonAWS",
  aWSContainersElasticContainerRegistry:
    "AWSContainersElasticContainerRegistry",
  aWSContainersECSAnywhere: "AWSContainersECSAnywhere",
  aWSContainersEKSCloud: "AWSContainersEKSCloud",
  aWSDatabaseAurora: "AWSDatabaseAurora",
  aWSContainersRedHatOpenShiftServiceonAWS:
    "AWSContainersRedHatOpenShiftServiceonAWS",
  aWSDatabaseElastiCache: "AWSDatabaseElastiCache",
  aWSDatabaseNeptune: "AWSDatabaseNeptune",
  aWSDatabaseKeyspaces: "AWSDatabaseKeyspaces",
  aWSDatabaseDynamoDB: "AWSDatabaseDynamoDB",
  aWSDatabaseMemoryDBforRedis: "AWSDatabaseMemoryDBforRedis",
  aWSDatabaseDatabaseMigrationService: "AWSDatabaseDatabaseMigrationService",
  aWSDatabaseDocumentDB: "AWSDatabaseDocumentDB",
  aWSDatabaseRDSonVMware: "AWSDatabaseRDSonVMware",
  aWSDatabaseRDS: "AWSDatabaseRDS",
  aWSContainersElasticContainerService: "AWSContainersElasticContainerService",
  aWSFrontEndWebMobileDeviceFarm: "AWSFrontEndWebMobileDeviceFarm",
  aWSEndUserComputingAppStream: "AWSEndUserComputingAppStream",
  aWSFrontEndWebMobileAmplify: "AWSFrontEndWebMobileAmplify",
  aWSEndUserComputingWorkLink: "AWSEndUserComputingWorkLink",
  aWSDeveloperToolsApplicationComposer: "AWSDeveloperToolsApplicationComposer",
  aWSFrontEndWebMobileLocationService: "AWSFrontEndWebMobileLocationService",
  aWSDeveloperToolsCloudControlAPI: "AWSDeveloperToolsCloudControlAPI",
  aWSEndUserComputingWorkSpacesFamily: "AWSEndUserComputingWorkSpacesFamily",
  aWSDeveloperToolsCloudDevelopmentKit: "AWSDeveloperToolsCloudDevelopmentKit",
  aWSDeveloperToolsCodeArtifact: "AWSDeveloperToolsCodeArtifact",
  aWSDeveloperToolsCodeDeploy: "AWSDeveloperToolsCodeDeploy",
  aWSDeveloperToolsCloud9: "AWSDeveloperToolsCloud9",
  aWSDatabaseTimestream: "AWSDatabaseTimestream",
  aWSDeveloperToolsCodePipeline: "AWSDeveloperToolsCodePipeline",
  aWSDeveloperToolsCommandLineInterface:
    "AWSDeveloperToolsCommandLineInterface",
  aWSDeveloperToolsCodeCatalyst: "AWSDeveloperToolsCodeCatalyst",
  aWSDeveloperToolsCodeStar: "AWSDeveloperToolsCodeStar",
  aWSDeveloperToolsCloudShell: "AWSDeveloperToolsCloudShell",
  aWSDeveloperToolsCodeCommit: "AWSDeveloperToolsCodeCommit",
  aWSDeveloperToolsCorretto: "AWSDeveloperToolsCorretto",
  aWSDeveloperToolsCodeBuild: "AWSDeveloperToolsCodeBuild",
  aWSGamesGameSparks: "AWSGamesGameSparks",
  aWSGamesGameKit: "AWSGamesGameKit",
  aWSGamesGameLift: "AWSGamesGameLift",
  aWSDeveloperToolsToolsandSDKs: "AWSDeveloperToolsToolsandSDKs",
  aWSGamesOpen3DEngine: "AWSGamesOpen3DEngine",
  aWSGeneralIconsMarketplace_Dark: "AWSGeneralIconsMarketplace_Dark",
  aWSDeveloperToolsXRay: "AWSDeveloperToolsXRay",
  aWSGeneralIconsMarketplace_: "AWSGeneralIconsMarketplace_",
  aWSGamesLumberyard: "AWSGamesLumberyard",
  aWSInternetofThingsFreeRTOS: "AWSInternetofThingsFreeRTOS",
  aWSInternetofThingsIoT1Click: "AWSInternetofThingsIoT1Click",
  aWSInternetofThingsIoTEduKit: "AWSInternetofThingsIoTEduKit",
  aWSInternetofThingsIoTCore: "AWSInternetofThingsIoTCore",
  aWSInternetofThingsIoTEvents: "AWSInternetofThingsIoTEvents",
  aWSInternetofThingsIoTDeviceDefender: "AWSInternetofThingsIoTDeviceDefender",
  aWSInternetofThingsIoTFleetWise: "AWSInternetofThingsIoTFleetWise",
  aWSInternetofThingsIoTGreengrass: "AWSInternetofThingsIoTGreengrass",
  aWSInternetofThingsIoTExpressLink: "AWSInternetofThingsIoTExpressLink",
  aWSInternetofThingsIoTDeviceManagement:
    "AWSInternetofThingsIoTDeviceManagement",
  aWSInternetofThingsIoTAnalytics: "AWSInternetofThingsIoTAnalytics",
  aWSInternetofThingsIoTSiteWise: "AWSInternetofThingsIoTSiteWise",
  aWSInternetofThingsIoTButton: "AWSInternetofThingsIoTButton",
  aWSInternetofThingsIoTTwinMaker: "AWSInternetofThingsIoTTwinMaker",
  aWSMachineLearningAugmentedAIA2I: "AWSMachineLearningAugmentedAIA2I",
  aWSInternetofThingsIoTRoboRunner: "AWSInternetofThingsIoTRoboRunner",
  aWSInternetofThingsIoTThingsGraph: "AWSInternetofThingsIoTThingsGraph",
  aWSMachineLearningCodeGuru: "AWSMachineLearningCodeGuru",
  aWSMachineLearningDeepLearningAMIs: "AWSMachineLearningDeepLearningAMIs",
  aWSMachineLearningDeepLearningContainers:
    "AWSMachineLearningDeepLearningContainers",
  aWSMachineLearningComprehend: "AWSMachineLearningComprehend",
  aWSMachineLearningDeepLens: "AWSMachineLearningDeepLens",
  aWSMachineLearningDeepComposer: "AWSMachineLearningDeepComposer",
  aWSMachineLearningComprehendMedical: "AWSMachineLearningComprehendMedical",
  aWSMachineLearningCodeWhisperer: "AWSMachineLearningCodeWhisperer",
  aWSMachineLearningApacheMXNetonAWS: "AWSMachineLearningApacheMXNetonAWS",
  aWSMachineLearningDevOpsGuru: "AWSMachineLearningDevOpsGuru",
  aWSMachineLearningHealthLake: "AWSMachineLearningHealthLake",
  aWSMachineLearningLex: "AWSMachineLearningLex",
  aWSMachineLearningElasticInference: "AWSMachineLearningElasticInference",
  aWSMachineLearningLookoutforEquipment:
    "AWSMachineLearningLookoutforEquipment",
  aWSMachineLearningKendra: "AWSMachineLearningKendra",
  aWSMachineLearningLookoutforMetrics: "AWSMachineLearningLookoutforMetrics",
  aWSMachineLearningDeepRacer: "AWSMachineLearningDeepRacer",
  aWSMachineLearningFraudDetector: "AWSMachineLearningFraudDetector",
  aWSMachineLearningNeuron: "AWSMachineLearningNeuron",
  aWSMachineLearningPanorama: "AWSMachineLearningPanorama",
  aWSMachineLearningLookoutforVision: "AWSMachineLearningLookoutforVision",
  aWSMachineLearningOmics: "AWSMachineLearningOmics",
  aWSMachineLearningMonitron: "AWSMachineLearningMonitron",
  aWSMachineLearningSageMaker: "AWSMachineLearningSageMaker",
  aWSMachineLearningForecast: "AWSMachineLearningForecast",
  aWSMachineLearningPersonalize: "AWSMachineLearningPersonalize",
  aWSMachineLearningSageMakerGroundTruth:
    "AWSMachineLearningSageMakerGroundTruth",
  aWSMachineLearningTensorFlowonAWS: "AWSMachineLearningTensorFlowonAWS",
  aWSMachineLearningTranscribe: "AWSMachineLearningTranscribe",
  aWSMachineLearningTextract: "AWSMachineLearningTextract",
  aWSMachineLearningTranslate: "AWSMachineLearningTranslate",
  aWSMachineLearningPolly: "AWSMachineLearningPolly",
  aWSMachineLearningTorchServe: "AWSMachineLearningTorchServe",
  aWSMachineLearningSageMakerStudioLab: "AWSMachineLearningSageMakerStudioLab",
  aWSMigrationTransferApplicationDiscoveryService:
    "AWSMigrationTransferApplicationDiscoveryService",
  aWSMigrationTransferMigrationEvaluator:
    "AWSMigrationTransferMigrationEvaluator",
  aWSMigrationTransferDataSync: "AWSMigrationTransferDataSync",
  aWSMachineLearningRekognition: "AWSMachineLearningRekognition",
  aWSMigrationTransferMigrationHub: "AWSMigrationTransferMigrationHub",
  aWSMigrationTransferTransferFamily: "AWSMigrationTransferTransferFamily",
  aWSMigrationTransferMainframeModernization:
    "AWSMigrationTransferMainframeModernization",
  aWSMediaServicesElasticTranscoder: "AWSMediaServicesElasticTranscoder",
  aWSMediaServicesElementalAppliancesSoftware:
    "AWSMediaServicesElementalAppliancesSoftware",
  aWSMigrationTransferServerMigrationService:
    "AWSMigrationTransferServerMigrationService",
  aWSMediaServicesElementalLink: "AWSMediaServicesElementalLink",
  aWSMigrationTransferApplicationMigrationService:
    "AWSMigrationTransferApplicationMigrationService",
  aWSMediaServicesElementalDelta: "AWSMediaServicesElementalDelta",
  aWSMediaServicesElementalLive: "AWSMediaServicesElementalLive",
  aWSMediaServicesElementalMediaLive: "AWSMediaServicesElementalMediaLive",
  aWSMediaServicesElementalMediaConnect:
    "AWSMediaServicesElementalMediaConnect",
  aWSMediaServicesElementalMediaPackage:
    "AWSMediaServicesElementalMediaPackage",
  aWSMediaServicesElementalMediaTailor: "AWSMediaServicesElementalMediaTailor",
  aWSMediaServicesElementalServer: "AWSMediaServicesElementalServer",
  aWSMediaServicesElementalMediaStore: "AWSMediaServicesElementalMediaStore",
  aWSMediaServicesElementalConductor: "AWSMediaServicesElementalConductor",
  aWSMediaServicesInteractiveVideoService:
    "AWSMediaServicesInteractiveVideoService",
  aWSMediaServicesKinesisVideoStreams: "AWSMediaServicesKinesisVideoStreams",
  aWSMediaServicesElementalMediaConvert:
    "AWSMediaServicesElementalMediaConvert",
  aWSMediaServicesNimbleStudio: "AWSMediaServicesNimbleStudio",
  aWSNetworkingContentDeliveryClientVPN:
    "AWSNetworkingContentDeliveryClientVPN",
  aWSNetworkingContentDeliveryCloudDirectory:
    "AWSNetworkingContentDeliveryCloudDirectory",
  aWSQuantumTechnologiesBraket: "AWSQuantumTechnologiesBraket",
  aWSRoboticsRoboMaker: "AWSRoboticsRoboMaker",
  aWSNetworkingContentDeliveryElasticLoadBalancing:
    "AWSNetworkingContentDeliveryElasticLoadBalancing",
  aWSNetworkingContentDeliveryCloudMap: "AWSNetworkingContentDeliveryCloudMap",
  aWSNetworkingContentDeliveryCloudFront:
    "AWSNetworkingContentDeliveryCloudFront",
  aWSNetworkingContentDeliveryGlobalAccelerator:
    "AWSNetworkingContentDeliveryGlobalAccelerator",
  aWSNetworkingContentDeliveryDirectConnect:
    "AWSNetworkingContentDeliveryDirectConnect",
  aWSSatelliteGroundStation: "AWSSatelliteGroundStation",
  aWSNetworkingContentDeliveryAppMesh: "AWSNetworkingContentDeliveryAppMesh",
  aWSNetworkingContentDeliveryPrivateLink:
    "AWSNetworkingContentDeliveryPrivateLink",
  aWSNetworkingContentDeliverySitetoSiteVPN:
    "AWSNetworkingContentDeliverySitetoSiteVPN",
  aWSNetworkingContentDeliveryCloudWAN: "AWSNetworkingContentDeliveryCloudWAN",
  aWSNetworkingContentDeliveryRoute53: "AWSNetworkingContentDeliveryRoute53",
  aWSNetworkingContentDeliveryVPCLattice:
    "AWSNetworkingContentDeliveryVPCLattice",
  aWSNetworkingContentDeliveryPrivate5G:
    "AWSNetworkingContentDeliveryPrivate5G",
  aWSNetworkingContentDeliveryVerifiedAccess:
    "AWSNetworkingContentDeliveryVerifiedAccess",
  aWSNetworkingContentDeliveryTransitGateway:
    "AWSNetworkingContentDeliveryTransitGateway",
  aWSNetworkingContentDeliveryVirtualPrivateCloud:
    "AWSNetworkingContentDeliveryVirtualPrivateCloud",
  aWSManagementGovernanceAutoScaling: "AWSManagementGovernanceAutoScaling",
  aWSManagementGovernanceAppConfig: "AWSManagementGovernanceAppConfig",
  aWSManagementGovernanceBackintAgent: "AWSManagementGovernanceBackintAgent",
  aWSManagementGovernanceCloudWatch: "AWSManagementGovernanceCloudWatch",
  aWSManagementGovernanceControlTower: "AWSManagementGovernanceControlTower",
  aWSManagementGovernanceCloudFormation:
    "AWSManagementGovernanceCloudFormation",
  aWSManagementGovernanceCloudTrail: "AWSManagementGovernanceCloudTrail",
  aWSManagementGovernanceApplicationAutoScaling:
    "AWSManagementGovernanceApplicationAutoScaling",
  aWSManagementGovernanceChatbot: "AWSManagementGovernanceChatbot",
  aWSManagementGovernanceDistroforOpenTelemetry:
    "AWSManagementGovernanceDistroforOpenTelemetry",
  aWSManagementGovernanceManagedGrafana:
    "AWSManagementGovernanceManagedGrafana",
  aWSManagementGovernanceLicenseManager:
    "AWSManagementGovernanceLicenseManager",
  aWSManagementGovernanceFaultInjectionSimulator:
    "AWSManagementGovernanceFaultInjectionSimulator",
  aWSManagementGovernanceLaunchWizard: "AWSManagementGovernanceLaunchWizard",
  aWSManagementGovernanceManagedServiceforPrometheus:
    "AWSManagementGovernanceManagedServiceforPrometheus",
  aWSManagementGovernanceProton: "AWSManagementGovernanceProton",
  aWSManagementGovernanceOrganizations: "AWSManagementGovernanceOrganizations",
  aWSManagementGovernanceOpsWorks: "AWSManagementGovernanceOpsWorks",
  aWSManagementGovernanceResilienceHub: "AWSManagementGovernanceResilienceHub",
  aWSManagementGovernanceConfig: "AWSManagementGovernanceConfig",
  aWSManagementGovernanceSystemsManager:
    "AWSManagementGovernanceSystemsManager",
  aWSManagementGovernancePersonalHealthDashboard:
    "AWSManagementGovernancePersonalHealthDashboard",
  aWSManagementGovernanceServiceCatalog:
    "AWSManagementGovernanceServiceCatalog",
  aWSManagementGovernanceResourceExplorer:
    "AWSManagementGovernanceResourceExplorer",
  aWSManagementGovernanceServiceManagementConnector:
    "AWSManagementGovernanceServiceManagementConnector",
  aWSManagementGovernanceWellArchitectedTool:
    "AWSManagementGovernanceWellArchitectedTool",
  aWSManagementGovernanceTrustedAdvisor:
    "AWSManagementGovernanceTrustedAdvisor",
  aWSStorageBackup: "AWSStorageBackup",
  aWSVRARSumerian: "AWSVRARSumerian",
  aWSManagementGovernanceManagementConsole:
    "AWSManagementGovernanceManagementConsole",
  aWSStorageEFS: "AWSStorageEFS",
  aWSStorageElasticDisasterRecovery: "AWSStorageElasticDisasterRecovery",
  aWSStorageFSxforLustre: "AWSStorageFSxforLustre",
  aWSStorageFSxforNetAppONTAP: "AWSStorageFSxforNetAppONTAP",
  aWSStorageElasticBlockStore: "AWSStorageElasticBlockStore",
  aWSStorageFSxforOpenZFS: "AWSStorageFSxforOpenZFS",
  aWSStorageFileCache: "AWSStorageFileCache",
  aWSStorageS3onOutposts: "AWSStorageS3onOutposts",
  aWSStorageFSxforWFS: "AWSStorageFSxforWFS",
  aWSStorageFSx: "AWSStorageFSx",
  aWSStorageSnowballEdge: "AWSStorageSnowballEdge",
  aWSStorageStorageGateway: "AWSStorageStorageGateway",
  aWSStorageSnowmobile: "AWSStorageSnowmobile",
  aWSStorageSnowcone: "AWSStorageSnowcone",
  aWSSecurityIdentityComplianceCloudDirectory:
    "AWSSecurityIdentityComplianceCloudDirectory",
  aWSStorageSnowball: "AWSStorageSnowball",
  aWSSecurityIdentityComplianceCertificateManager:
    "AWSSecurityIdentityComplianceCertificateManager",
  aWSSecurityIdentityComplianceCognito: "AWSSecurityIdentityComplianceCognito",
  aWSStorageSimpleStorageService: "AWSStorageSimpleStorageService",
  aWSSecurityIdentityComplianceAuditManager:
    "AWSSecurityIdentityComplianceAuditManager",
  aWSStorageSimpleStorageServiceGlacier:
    "AWSStorageSimpleStorageServiceGlacier",
  aWSSecurityIdentityComplianceDetective:
    "AWSSecurityIdentityComplianceDetective",
  aWSSecurityIdentityComplianceArtifact:
    "AWSSecurityIdentityComplianceArtifact",
  aWSSecurityIdentityComplianceDirectoryService:
    "AWSSecurityIdentityComplianceDirectoryService",
  aWSSecurityIdentityComplianceIAMIdentityCenter:
    "AWSSecurityIdentityComplianceIAMIdentityCenter",
  aWSSecurityIdentityComplianceFirewallManager:
    "AWSSecurityIdentityComplianceFirewallManager",
  aWSSecurityIdentityComplianceIdentityandAccessManagement:
    "AWSSecurityIdentityComplianceIdentityandAccessManagement",
  aWSSecurityIdentityComplianceGuardDuty:
    "AWSSecurityIdentityComplianceGuardDuty",
  aWSSecurityIdentityComplianceInspector:
    "AWSSecurityIdentityComplianceInspector",
  aWSSecurityIdentityComplianceCloudHSM:
    "AWSSecurityIdentityComplianceCloudHSM",
  aWSSecurityIdentityComplianceResourceAccessManager:
    "AWSSecurityIdentityComplianceResourceAccessManager",
  aWSSecurityIdentityComplianceNetworkFirewall:
    "AWSSecurityIdentityComplianceNetworkFirewall",
  aWSSecurityIdentityComplianceSecretsManager:
    "AWSSecurityIdentityComplianceSecretsManager",
  aWSSecurityIdentityComplianceKeyManagementService:
    "AWSSecurityIdentityComplianceKeyManagementService",
  aWSSecurityIdentityComplianceMacie: "AWSSecurityIdentityComplianceMacie",
  aWSSecurityIdentityComplianceSecurityHub:
    "AWSSecurityIdentityComplianceSecurityHub",
  aWSSecurityIdentityComplianceShield: "AWSSecurityIdentityComplianceShield",
  aWSSecurityIdentityCompliancePrivateCertificateAuthority:
    "AWSSecurityIdentityCompliancePrivateCertificateAuthority",
  aWSSecurityIdentityComplianceSecurityLake:
    "AWSSecurityIdentityComplianceSecurityLake",
  aWSSecurityIdentityComplianceSigner: "AWSSecurityIdentityComplianceSigner",
  aWSSecurityIdentityComplianceVerifiedPermissions:
    "AWSSecurityIdentityComplianceVerifiedPermissions",
  aWSSecurityIdentityComplianceWAF: "AWSSecurityIdentityComplianceWAF",
};
