export const SkillIcons = {
  skillIconActivityPub: {
    name: "Activity Pub",
    icon: "SkillIconActivityPub",
  },
  skillIconAbleton: { name: "Ableton", icon: "SkillIconAbleton" },
  skillIconAWS: { name: "AWS", icon: "SkillIconAWS" },
  skillIconAfterEffects: {
    name: "After Effects",
    icon: "SkillIconAfterEffects",
  },
  skillIconAndroidStudio: {
    name: "Android Studio",
    icon: "SkillIconAndroidStudio",
  },
  skillIconAlpineJS: { name: "Alpine JS", icon: "SkillIconAlpineJS" },
  skillIconAngular: { name: "Angular", icon: "SkillIconAngular" },
  skillIconAnaconda: { name: "Anaconda", icon: "SkillIconAnaconda" },
  skillIconAiScript: { name: "Ai Script", icon: "SkillIconAiScript" },
  skillIconAnsible: { name: "Ansible", icon: "SkillIconAnsible" },
  skillIconAppwrite: { name: "Appwrite", icon: "SkillIconAppwrite" },
  skillIconActix: { name: "Actix", icon: "SkillIconActix" },
  skillIconAstro: { name: "Astro", icon: "SkillIconAstro" },
  skillIconApple: { name: "Apple", icon: "SkillIconApple" },
  skillIconArduino: { name: "Arduino", icon: "SkillIconArduino" },
  skillIconApollo: { name: "Apollo", icon: "SkillIconApollo" },
  skillIconAzul: { name: "Azul", icon: "SkillIconAzul" },
  skillIconAudition: { name: "Audition", icon: "SkillIconAudition" },
  skillIconAdonis: { name: "Adonis", icon: "SkillIconAdonis" },
  skillIconAzure: { name: "Azure", icon: "SkillIconAzure" },
  skillIconAutoCAD: { name: "Auto CAD", icon: "SkillIconAutoCAD" },
  skillIconBlender: { name: "Blender", icon: "SkillIconBlender" },
  skillIconArch: { name: "Arch", icon: "SkillIconArch" },
  skillIconBash: { name: "Bash", icon: "SkillIconBash" },
  skillIconBevy: { name: "Bevy", icon: "SkillIconBevy" },
  skillIconBootstrap: { name: "Bootstrap", icon: "SkillIconBootstrap" },
  skillIconBSD: { name: "BSD", icon: "SkillIconBSD" },
  skillIconCLion: { name: "CLion", icon: "SkillIconCLion" },
  skillIconBun: { name: "Bun", icon: "SkillIconBun" },
  skillIconC: { name: "C", icon: "SkillIconC" },
  skillIconBitBucket: { name: "Bit Bucket", icon: "SkillIconBitBucket" },
  skillIconCMake: { name: "CMake", icon: "SkillIconCMake" },
  skillIconAtom: { name: "Atom", icon: "SkillIconAtom" },
  skillIconCSS: { name: "CSS", icon: "SkillIconCSS" },
  skillIconCPP: { name: "CPP", icon: "SkillIconCPP" },
  skillIconCS: { name: "CS", icon: "SkillIconCS" },
  skillIconCloudflare: {
    name: "Cloudflare",
    icon: "SkillIconCloudflare",
  },
  skillIconClojure: { name: "Clojure", icon: "SkillIconClojure" },
  skillIconCodePen: { name: "Code Pen", icon: "SkillIconCodePen" },
  skillIconCassandra: { name: "Cassandra", icon: "SkillIconCassandra" },
  skillIconCrystal: { name: "Crystal", icon: "SkillIconCrystal" },
  skillIconDart: { name: "Dart", icon: "SkillIconDart" },
  skillIconCypress: { name: "Cypress", icon: "SkillIconCypress" },
  skillIconDENO: { name: "DENO", icon: "SkillIconDENO" },
  skillIconCoffeeScript: {
    name: "Coffee Script",
    icon: "SkillIconCoffeeScript",
  },
  skillIconD3: { name: "D3", icon: "SkillIconD3" },
  skillIconDevTo: { name: "Dev To", icon: "SkillIconDevTo" },
  skillIconDiscord: { name: "Discord", icon: "SkillIconDiscord" },
  skillIconDiscordJS: { name: "Discord JS", icon: "SkillIconDiscordJS" },
  skillIconDjango: { name: "Django", icon: "SkillIconDjango" },
  skillIconBabel: { name: "Babel", icon: "SkillIconBabel" },
  skillIconDiscordBots: {
    name: "Discord Bots",
    icon: "SkillIconDiscordBots",
  },
  skillIconDotNet: { name: "Dot Net", icon: "SkillIconDotNet" },
  skillIconDynamoDB: { name: "Dynamo DB", icon: "SkillIconDynamoDB" },
  skillIconDocker: { name: "Docker", icon: "SkillIconDocker" },
  skillIconElixir: { name: "Elixir", icon: "SkillIconElixir" },
  skillIconDebian: { name: "Debian", icon: "SkillIconDebian" },
  skillIconElasticsearch: {
    name: "Elasticsearch",
    icon: "SkillIconElasticsearch",
  },
  skillIconEmacs: { name: "Emacs", icon: "SkillIconEmacs" },
  skillIconElysia: { name: "Elysia", icon: "SkillIconElysia" },
  skillIconFastAPI: { name: "Fast API", icon: "SkillIconFastAPI" },
  skillIconElectron: { name: "Electron", icon: "SkillIconElectron" },
  skillIconEclipse: { name: "Eclipse", icon: "SkillIconEclipse" },
  skillIconEmber: { name: "Ember", icon: "SkillIconEmber" },
  skillIconFlutter: { name: "Flutter", icon: "SkillIconFlutter" },
  skillIconFediverse: { name: "Fediverse", icon: "SkillIconFediverse" },
  skillIconFortran: { name: "Fortran", icon: "SkillIconFortran" },
  skillIconExpressJS: { name: "Express JS", icon: "SkillIconExpressJS" },
  skillIconEmotion: { name: "Emotion", icon: "SkillIconEmotion" },
  skillIconGTK: { name: "GTK", icon: "SkillIconGTK" },
  skillIconFirebase: { name: "Firebase", icon: "SkillIconFirebase" },
  skillIconFigma: { name: "Figma", icon: "SkillIconFigma" },
  skillIconGCP: { name: "GCP", icon: "SkillIconGCP" },
  skillIconGherkin: { name: "Gherkin", icon: "SkillIconGherkin" },
  skillIconGit: { name: "Git", icon: "SkillIconGit" },
  skillIconGameMakerStudio: {
    name: "Game Maker Studio",
    icon: "SkillIconGameMakerStudio",
  },
  skillIconGithub: { name: "Github", icon: "SkillIconGithub" },
  skillIconGithubActions: {
    name: "Github Actions",
    icon: "SkillIconGithubActions",
  },
  skillIconFlask: { name: "Flask", icon: "SkillIconFlask" },
  skillIconGoLang: { name: "Go Lang", icon: "SkillIconGoLang" },
  skillIconGmail: { name: "Gmail", icon: "SkillIconGmail" },
  skillIconForth: { name: "Forth", icon: "SkillIconForth" },
  skillIconGraphQL: { name: "Graph QL", icon: "SkillIconGraphQL" },
  skillIconGitLab: { name: "Git Lab", icon: "SkillIconGitLab" },
  skillIconGatsby: { name: "Gatsby", icon: "SkillIconGatsby" },
  skillIconGulp: { name: "Gulp", icon: "SkillIconGulp" },
  skillIconHaxe: { name: "Haxe", icon: "SkillIconHaxe" },
  skillIconHaskell: { name: "Haskell", icon: "SkillIconHaskell" },
  skillIconHTML: { name: "HTML", icon: "SkillIconHTML" },
  skillIconGrafana: { name: "Grafana", icon: "SkillIconGrafana" },
  skillIconHeroku: { name: "Heroku", icon: "SkillIconHeroku" },
  skillIconHaxeFlixel: {
    name: "Haxe Flixel",
    icon: "SkillIconHaxeFlixel",
  },
  skillIconHibernate: { name: "Hibernate", icon: "SkillIconHibernate" },
  skillIconGradle: { name: "Gradle", icon: "SkillIconGradle" },
  skillIconHtmx: { name: "Htmx", icon: "SkillIconHtmx" },
  skillIconGodot: { name: "Godot", icon: "SkillIconGodot" },
  skillIconIPFS: { name: "IPFS", icon: "SkillIconIPFS" },
  skillIconIdea: { name: "Idea", icon: "SkillIconIdea" },
  skillIconInstagram: { name: "Instagram", icon: "SkillIconInstagram" },
  skillIconJava: { name: "Java", icon: "SkillIconJava" },
  skillIconIllustrator: {
    name: "Illustrator",
    icon: "SkillIconIllustrator",
  },
  skillIconJenkins: { name: "Jenkins", icon: "SkillIconJenkins" },
  skillIconJest: { name: "Jest", icon: "SkillIconJest" },
  skillIconJQuery: { name: "JQuery", icon: "SkillIconJQuery" },
  skillIconJavaScript: {
    name: "Java Script",
    icon: "SkillIconJavaScript",
  },
  skillIconKubernetes: {
    name: "Kubernetes",
    icon: "SkillIconKubernetes",
  },
  skillIconKotlin: { name: "Kotlin", icon: "SkillIconKotlin" },
  skillIconLaravel: { name: "Laravel", icon: "SkillIconLaravel" },
  skillIconLinkedIn: { name: "Linked In", icon: "SkillIconLinkedIn" },
  skillIconKali: { name: "Kali", icon: "SkillIconKali" },
  skillIconKafka: { name: "Kafka", icon: "SkillIconKafka" },
  skillIconLit: { name: "Lit", icon: "SkillIconLit" },
  skillIconMarkdown: { name: "Markdown", icon: "SkillIconMarkdown" },
  skillIconJulia: { name: "Julia", icon: "SkillIconJulia" },
  skillIconLaTeX: { name: "LaTeX", icon: "SkillIconLaTeX" },
  skillIconLua: { name: "Lua", icon: "SkillIconLua" },
  skillIconMastodon: { name: "Mastodon", icon: "SkillIconMastodon" },
  skillIconLess: { name: "Less", icon: "SkillIconLess" },
  skillIconMatlab: { name: "Matlab", icon: "SkillIconMatlab" },
  skillIconMisskey: { name: "Misskey", icon: "SkillIconMisskey" },
  skillIconMaterialUI: {
    name: "Material UI",
    icon: "SkillIconMaterialUI",
  },
  skillIconMongoDB: { name: "Mongo DB", icon: "SkillIconMongoDB" },
  skillIconKtor: { name: "Ktor", icon: "SkillIconKtor" },
  skillIconMint: { name: "Mint", icon: "SkillIconMint" },
  skillIconLinux: { name: "Linux", icon: "SkillIconLinux" },
  skillIconMySQL: { name: "My SQL", icon: "SkillIconMySQL" },
  skillIconMaven: { name: "Maven", icon: "SkillIconMaven" },
  skillIconNeoVim: { name: "Neo Vim", icon: "SkillIconNeoVim" },
  skillIconNim: { name: "Nim", icon: "SkillIconNim" },
  skillIconNextJS: { name: "Next JS", icon: "SkillIconNextJS" },
  skillIconNix: { name: "Nix", icon: "SkillIconNix" },
  skillIconNginx: { name: "Nginx", icon: "SkillIconNginx" },
  skillIconNestJS: { name: "Nest JS", icon: "SkillIconNestJS" },
  skillIconNpm: { name: "Npm", icon: "SkillIconNpm" },
  skillIconNetlify: { name: "Netlify", icon: "SkillIconNetlify" },
  skillIconNuxtJS: { name: "Nuxt JS", icon: "SkillIconNuxtJS" },
  skillIconNodeJS: { name: "Node JS", icon: "SkillIconNodeJS" },
  skillIconNotion: { name: "Notion", icon: "SkillIconNotion" },
  skillIconOpenCV: { name: "Open CV", icon: "SkillIconOpenCV" },
  skillIconOctave: { name: "Octave", icon: "SkillIconOctave" },
  skillIconPHP: { name: "PHP", icon: "SkillIconPHP" },
  skillIconOpenStack: { name: "Open Stack", icon: "SkillIconOpenStack" },
  skillIconPhotoshop: { name: "Photoshop", icon: "SkillIconPhotoshop" },
  skillIconOpenShift: { name: "Open Shift", icon: "SkillIconOpenShift" },
  skillIconPhpStorm: { name: "Php Storm", icon: "SkillIconPhpStorm" },
  skillIconPkl: { name: "Pkl", icon: "SkillIconPkl" },
  skillIconObsidian: { name: "Obsidian", icon: "SkillIconObsidian" },
  skillIconPinia: { name: "Pinia", icon: "SkillIconPinia" },
  skillIconPnpm: { name: "Pnpm", icon: "SkillIconPnpm" },
  skillIconPostgreSQL: {
    name: "Postgre SQL",
    icon: "SkillIconPostgreSQL",
  },
  skillIconPerl: { name: "Perl", icon: "SkillIconPerl" },
  skillIconPlan9: { name: "Plan9", icon: "SkillIconPlan9" },
  skillIconPowershell: {
    name: "Powershell",
    icon: "SkillIconPowershell",
  },
  skillIconOCaml: { name: "OCaml", icon: "SkillIconOCaml" },
  skillIconPrisma: { name: "Prisma", icon: "SkillIconPrisma" },
  skillIconPremiere: { name: "Premiere", icon: "SkillIconPremiere" },
  skillIconPyCharm: { name: "Py Charm", icon: "SkillIconPyCharm" },
  skillIconProcessing: {
    name: "Processing",
    icon: "SkillIconProcessing",
  },
  skillIconPlanetScale: {
    name: "Planet Scale",
    icon: "SkillIconPlanetScale",
  },
  skillIconR: { name: "R", icon: "SkillIconR" },
  skillIconPrometheus: {
    name: "Prometheus",
    icon: "SkillIconPrometheus",
  },
  skillIconPostman: { name: "Postman", icon: "SkillIconPostman" },
  skillIconPyTorch: { name: "Py Torch", icon: "SkillIconPyTorch" },
  skillIconRails: { name: "Rails", icon: "SkillIconRails" },
  skillIconPug: { name: "Pug", icon: "SkillIconPug" },
  skillIconPython: { name: "Python", icon: "SkillIconPython" },
  skillIconROS: { name: "ROS", icon: "SkillIconROS" },
  skillIconQT: { name: "QT", icon: "SkillIconQT" },
  skillIconRedis: { name: "Redis", icon: "SkillIconRedis" },
  skillIconRabbitMQ: { name: "Rabbit MQ", icon: "SkillIconRabbitMQ" },
  skillIconReactiveX: { name: "Reactive X", icon: "SkillIconReactiveX" },
  skillIconRaspberryPi: {
    name: "Raspberry Pi",
    icon: "SkillIconRaspberryPi",
  },
  skillIconReact: { name: "React", icon: "SkillIconReact" },
  skillIconReplit: { name: "Replit", icon: "SkillIconReplit" },
  skillIconRemix: { name: "Remix", icon: "SkillIconRemix" },
  skillIconRedHat: { name: "Red Hat", icon: "SkillIconRedHat" },
  skillIconRust: { name: "Rust", icon: "SkillIconRust" },
  skillIconRocket: { name: "Rocket", icon: "SkillIconRocket" },
  skillIconRider: { name: "Rider", icon: "SkillIconRider" },
  skillIconRollupJS: { name: "Rollup JS", icon: "SkillIconRollupJS" },
  skillIconSVG: { name: "SVG", icon: "SkillIconSVG" },
  skillIconRegex: { name: "Regex", icon: "SkillIconRegex" },
  skillIconSQLite: { name: "SQLite", icon: "SkillIconSQLite" },
  skillIconRuby: { name: "Ruby", icon: "SkillIconRuby" },
  skillIconSentry: { name: "Sentry", icon: "SkillIconSentry" },
  skillIconSketchup: { name: "Sketchup", icon: "SkillIconSketchup" },
  skillIconSciKitLearn: {
    name: "Sci Kit Learn",
    icon: "SkillIconSciKitLearn",
  },
  skillIconSass: { name: "Sass", icon: "SkillIconSass" },
  skillIconSolidJS: { name: "Solid JS", icon: "SkillIconSolidJS" },
  skillIconSelenium: { name: "Selenium", icon: "SkillIconSelenium" },
  skillIconRobloxStudio: {
    name: "Roblox Studio",
    icon: "SkillIconRobloxStudio",
  },
  skillIconSequelize: { name: "Sequelize", icon: "SkillIconSequelize" },
  skillIconStackOverflow: {
    name: "Stack Overflow",
    icon: "SkillIconStackOverflow",
  },
  skillIconScala: { name: "Scala", icon: "SkillIconScala" },
  skillIconSolidity: { name: "Solidity", icon: "SkillIconSolidity" },
  skillIconRedux: { name: "Redux", icon: "SkillIconRedux" },
  skillIconSupabase: { name: "Supabase", icon: "SkillIconSupabase" },
  skillIconSpring: { name: "Spring", icon: "SkillIconSpring" },
  skillIconSwift: { name: "Swift", icon: "SkillIconSwift" },
  skillIconTauri: { name: "Tauri", icon: "SkillIconTauri" },
  skillIconTerraform: { name: "Terraform", icon: "SkillIconTerraform" },
  skillIconSublime: { name: "Sublime", icon: "SkillIconSublime" },
  skillIconSvelte: { name: "Svelte", icon: "SkillIconSvelte" },
  skillIconTailwindCSS: {
    name: "Tailwind CSS",
    icon: "SkillIconTailwindCSS",
  },
  skillIconThreeJS: { name: "Three JS", icon: "SkillIconThreeJS" },
  skillIconSymfony: { name: "Symfony", icon: "SkillIconSymfony" },
  skillIconTypeScript: {
    name: "Type Script",
    icon: "SkillIconTypeScript",
  },
  skillIconTwitter: { name: "Twitter", icon: "SkillIconTwitter" },
  skillIconUbuntu: { name: "Ubuntu", icon: "SkillIconUbuntu" },
  skillIconStyledComponents: {
    name: "Styled Components",
    icon: "SkillIconStyledComponents",
  },
  skillIconVSCode: { name: "VS Code", icon: "SkillIconVSCode" },
  skillIconVSCodium: { name: "VS Codium", icon: "SkillIconVSCodium" },
  skillIconVIM: { name: "VIM", icon: "SkillIconVIM" },
  skillIconUnrealEngine: {
    name: "Unreal Engine",
    icon: "SkillIconUnrealEngine",
  },
  skillIconVala: { name: "Vala", icon: "SkillIconVala" },
  skillIconV: { name: "V", icon: "SkillIconV" },
  skillIconVitest: { name: "Vitest", icon: "SkillIconVitest" },
  skillIconVercel: { name: "Vercel", icon: "SkillIconVercel" },
  skillIconVueJS: { name: "Vue JS", icon: "SkillIconVueJS" },
  skillIconWebAssembly: {
    name: "Web Assembly",
    icon: "SkillIconWebAssembly",
  },
  skillIconWebStorm: { name: "Web Storm", icon: "SkillIconWebStorm" },
  skillIconWindiCSS: { name: "Windi CSS", icon: "SkillIconWindiCSS" },
  skillIconWebpack: { name: "Webpack", icon: "SkillIconWebpack" },
  skillIconWindows: { name: "Windows", icon: "SkillIconWindows" },
  skillIconVisualStudio: {
    name: "Visual Studio",
    icon: "SkillIconVisualStudio",
  },
  skillIconWordpress: { name: "Wordpress", icon: "SkillIconWordpress" },
  skillIconTensorFlow: {
    name: "Tensor Flow",
    icon: "SkillIconTensorFlow",
  },
  skillIconWorkers: { name: "Workers", icon: "SkillIconWorkers" },
  skillIconYarn: { name: "Yarn", icon: "SkillIconYarn" },
  skillIconWebflow: { name: "Webflow", icon: "SkillIconWebflow" },
  skillIconUnity: { name: "Unity", icon: "SkillIconUnity" },
  skillIconXD: { name: "XD", icon: "SkillIconXD" },
  skillIconVite: { name: "Vite", icon: "SkillIconVite" },
  skillIconZig: { name: "Zig", icon: "SkillIconZig" },
  skillIconVuetify: { name: "Vuetify", icon: "SkillIconVuetify" },
  skillIconYew: { name: "Yew", icon: "SkillIconYew" },
  skillIconp5js: { name: "P5js", icon: "SkillIconp5js" },
};
