export const UndrawIcons = {
  undrawPhoneCall: { name: "Phone Call", icon: "UndrawPhoneCall" },
  undrawDesigner: { name: "Designer", icon: "UndrawDesigner" },
  undrawVoiceMessages: { name: "Voice Messages", icon: "UndrawVoiceMessages" },
  undrawBooks: { name: "Books", icon: "UndrawBooks" },
  undrawPhotographer: { name: "Photographer", icon: "UndrawPhotographer" },
  undrawBuildingAWebsite: {
    name: "Building A Website",
    icon: "UndrawBuildingAWebsite",
  },
  undrawAlgorithmExecution: {
    name: "Algorithm Execution",
    icon: "UndrawAlgorithmExecution",
  },
  undrawWorkFriends: { name: "Work Friends", icon: "UndrawWorkFriends" },
  undrawMindMap: { name: "Mind Map", icon: "UndrawMindMap" },
  undrawServerError: { name: "Server Error", icon: "UndrawServerError" },
  undrawCompleteForm: { name: "Complete Form", icon: "UndrawCompleteForm" },
  undrawAvatarTraveler: {
    name: "Avatar Traveler",
    icon: "UndrawAvatarTraveler",
  },
  undrawApprovedWireframe: {
    name: "Approved Wireframe",
    icon: "UndrawApprovedWireframe",
  },
  undrawProcessing: { name: "Processing", icon: "UndrawProcessing" },
  undrawPrivateFiles: { name: "Private Files", icon: "UndrawPrivateFiles" },
  undrawConfirmed: { name: "Confirmed", icon: "UndrawConfirmed" },
  undrawCreativeWoman: { name: "Creative Woman", icon: "UndrawCreativeWoman" },
  undrawCreditCardPayments: {
    name: "Credit Card Payments",
    icon: "UndrawCreditCardPayments",
  },
  undrawBentoGrid: { name: "Bento Grid", icon: "UndrawBentoGrid" },
  undrawYoungManAvatar: {
    name: "Young Man Avatar",
    icon: "UndrawYoungManAvatar",
  },
  undrawLogIn: { name: "Log In", icon: "UndrawLogIn" },
  undrawCalendar: { name: "Calendar", icon: "UndrawCalendar" },
  undrawGifts: { name: "Gifts", icon: "UndrawGifts" },
  undrawCorrectAnswer: { name: "Correct Answer", icon: "UndrawCorrectAnswer" },
  undrawPresenting: { name: "Presenting", icon: "UndrawPresenting" },
  undrawVibeCoding: { name: "Vibe Coding", icon: "UndrawVibeCoding" },
  undrawLogOut: { name: "Log Out", icon: "UndrawLogOut" },
  undrawOrganizingData: {
    name: "Organizing Data",
    icon: "UndrawOrganizingData",
  },
  undrawVersionControl: {
    name: "Version Control",
    icon: "UndrawVersionControl",
  },
  undrawOrderFlowers: { name: "Order Flowers", icon: "UndrawOrderFlowers" },
  undrawProfessionalWomanAvatar: {
    name: "Professional Woman Avatar",
    icon: "UndrawProfessionalWomanAvatar",
  },
  undrawFinanceGuyAvatar: {
    name: "Finance Guy Avatar",
    icon: "UndrawFinanceGuyAvatar",
  },
  undrawPreparation: { name: "Preparation", icon: "UndrawPreparation" },
  undrawComputerFiles: { name: "Computer Files", icon: "UndrawComputerFiles" },
  undrawRelaxMode: { name: "Relax Mode", icon: "UndrawRelaxMode" },
  undrawUnreadMessages: {
    name: "Unread Messages",
    icon: "UndrawUnreadMessages",
  },
  undrawFootballWithDad: {
    name: "Football With Dad",
    icon: "UndrawFootballWithDad",
  },
  undrawInTheOffice: { name: "In The Office", icon: "UndrawInTheOffice" },
  undrawWorkingTogether: {
    name: "Working Together",
    icon: "UndrawWorkingTogether",
  },
  undrawSegmentAnalysis: {
    name: "Segment Analysis",
    icon: "UndrawSegmentAnalysis",
  },
  undrawSuccessFactors: {
    name: "Success Factors",
    icon: "UndrawSuccessFactors",
  },
  undrawPushNotifications: {
    name: "Push Notifications",
    icon: "UndrawPushNotifications",
  },
  undrawAvatars: { name: "Avatars", icon: "UndrawAvatars" },
  undrawMobileAnalytics: {
    name: "Mobile Analytics",
    icon: "UndrawMobileAnalytics",
  },
  undrawGoingUpwards: { name: "Going Upwards", icon: "UndrawGoingUpwards" },
  undrawNewMessage: { name: "New Message", icon: "UndrawNewMessage" },
  undrawDocumentAnalysis: {
    name: "Document Analysis",
    icon: "UndrawDocumentAnalysis",
  },
  undrawBikeRide: { name: "Bike Ride", icon: "UndrawBikeRide" },
  undrawTakingSelfie: { name: "Taking Selfie", icon: "UndrawTakingSelfie" },
  undrawMultipleChoice: {
    name: "Multiple Choice",
    icon: "UndrawMultipleChoice",
  },
  undrawShipIt: { name: "Ship It", icon: "UndrawShipIt" },
  undrawEffortlessLove: {
    name: "Effortless Love",
    icon: "UndrawEffortlessLove",
  },
  undrawInLove: { name: "In Love", icon: "UndrawInLove" },
  undrawAtTheAirport: { name: "At The Airport", icon: "UndrawAtTheAirport" },
  undrawAttachedFile: { name: "Attached File", icon: "UndrawAttachedFile" },
  undrawMyWorkspace: { name: "My Workspace", icon: "UndrawMyWorkspace" },
  undrawAICodeGeneration: {
    name: "A I Code Generation",
    icon: "UndrawAICodeGeneration",
  },
  undrawTravelers: { name: "Travelers", icon: "UndrawTravelers" },
  undrawToTheMoon: { name: "To The Moon", icon: "UndrawToTheMoon" },
  undrawGamingController: {
    name: "Gaming Controller",
    icon: "UndrawGamingController",
  },
  undrawWorkingOut: { name: "Working Out", icon: "UndrawWorkingOut" },
  undrawTowing: { name: "Towing", icon: "UndrawTowing" },
  undrawInvest: { name: "Invest", icon: "UndrawInvest" },
  undrawDataTrends: { name: "Data Trends", icon: "UndrawDataTrends" },
  undrawUploading: { name: "Uploading", icon: "UndrawUploading" },
  undrawDevProductivity: {
    name: "Dev Productivity",
    icon: "UndrawDevProductivity",
  },
  undrawFileSearch: { name: "File Search", icon: "UndrawFileSearch" },
  undrawYoga: { name: "Yoga", icon: "UndrawYoga" },
  undrawSettings: { name: "Settings", icon: "UndrawSettings" },
  undrawGoldenGateBridge: {
    name: "Golden Gate Bridge",
    icon: "UndrawGoldenGateBridge",
  },
  undrawOnlineShopping: {
    name: "Online Shopping",
    icon: "UndrawOnlineShopping",
  },
  undrawOnlineCollaboration: {
    name: "Online Collaboration",
    icon: "UndrawOnlineCollaboration",
  },
  undrawHello: { name: "Hello", icon: "UndrawHello" },
  undrawHiking: { name: "Hiking", icon: "UndrawHiking" },
  undrawWritingDownIdeas: {
    name: "Writing Down Ideas",
    icon: "UndrawWritingDownIdeas",
  },
  undrawPieChart: { name: "Pie Chart", icon: "UndrawPieChart" },
  undrawWithLove: { name: "With Love", icon: "UndrawWithLove" },
  undrawPairProgramming: {
    name: "Pair Programming",
    icon: "UndrawPairProgramming",
  },
  undrawCasualCall: { name: "Casual Call", icon: "UndrawCasualCall" },
  undrawRightDirection: {
    name: "Right Direction",
    icon: "UndrawRightDirection",
  },
  undrawModernDesign: { name: "Modern Design", icon: "UndrawModernDesign" },
  undrawDesignFeedback: {
    name: "Design Feedback",
    icon: "UndrawDesignFeedback",
  },
  undrawLocationTracking: {
    name: "Location Tracking",
    icon: "UndrawLocationTracking",
  },
  undrawBookmarks: { name: "Bookmarks", icon: "UndrawBookmarks" },
  undrawFinance: { name: "Finance", icon: "UndrawFinance" },
  undrawLandscapeMode: { name: "Landscape Mode", icon: "UndrawLandscapeMode" },
  undrawMyCurrentLocation: {
    name: "My Current Location",
    icon: "UndrawMyCurrentLocation",
  },
  undrawPlaylist: { name: "Playlist", icon: "UndrawPlaylist" },
  undrawPrioritise: { name: "Prioritise", icon: "UndrawPrioritise" },
  undrawMyUniverse: { name: "My Universe", icon: "UndrawMyUniverse" },
  undrawProgressIndicator: {
    name: "Progress Indicator",
    icon: "UndrawProgressIndicator",
  },
  undrawTraveling: { name: "Traveling", icon: "UndrawTraveling" },
  undrawBarista: { name: "Barista", icon: "UndrawBarista" },
  undrawOnlinePosts: { name: "Online Posts", icon: "UndrawOnlinePosts" },
  undrawCoding: { name: "Coding", icon: "UndrawCoding" },
  undrawSelfie: { name: "Selfie", icon: "UndrawSelfie" },
  undrawProgrammer: { name: "Programmer", icon: "UndrawProgrammer" },
  undrawAccessAccount: { name: "Access Account", icon: "UndrawAccessAccount" },
  undrawBullMarket: { name: "Bull Market", icon: "UndrawBullMarket" },
  undrawOurSolution: { name: "Our Solution", icon: "UndrawOurSolution" },
  undrawPhotograph: { name: "Photograph", icon: "UndrawPhotograph" },
  undrawDigitalArtwork: {
    name: "Digital Artwork",
    icon: "UndrawDigitalArtwork",
  },
  undrawAthletesTraining: {
    name: "Athletes Training",
    icon: "UndrawAthletesTraining",
  },
  undrawRelaxedReading: {
    name: "Relaxed Reading",
    icon: "UndrawRelaxedReading",
  },
  undrawRoadSign: { name: "Road Sign", icon: "UndrawRoadSign" },
  undrawFavoritePost: { name: "Favorite Post", icon: "UndrawFavoritePost" },
  undrawDesign: { name: "Design", icon: "UndrawDesign" },
  undrawProfessor: { name: "Professor", icon: "UndrawProfessor" },
  undrawTreeSwing: { name: "Tree Swing", icon: "UndrawTreeSwing" },
  undrawFoundingTeam: { name: "Founding Team", icon: "UndrawFoundingTeam" },
  undrawMyWebsite: { name: "My Website", icon: "UndrawMyWebsite" },
  undrawPersonalGoals: { name: "Personal Goals", icon: "UndrawPersonalGoals" },
  undrawNewYear2025: { name: "New Year2025", icon: "UndrawNewYear2025" },
  undrawAccessDenied: { name: "Access Denied", icon: "UndrawAccessDenied" },
  undrawMobileSite: { name: "Mobile Site", icon: "UndrawMobileSite" },
  undrawDestination: { name: "Destination", icon: "UndrawDestination" },
  undrawInTheZone: { name: "In The Zone", icon: "UndrawInTheZone" },
  undrawPodcastListener: {
    name: "Podcast Listener",
    icon: "UndrawPodcastListener",
  },
  undrawGroceries: { name: "Groceries", icon: "UndrawGroceries" },
  undrawTestimonials: { name: "Testimonials", icon: "UndrawTestimonials" },
  undrawQuietStreet: { name: "Quiet Street", icon: "UndrawQuietStreet" },
  undrawWellDone: { name: "Well Done", icon: "UndrawWellDone" },
  undrawAIVoiceInterface: {
    name: "A I Voice Interface",
    icon: "UndrawAIVoiceInterface",
  },
  undrawTeamUp: { name: "Team Up", icon: "UndrawTeamUp" },
  undrawVideoTutorial: { name: "Video Tutorial", icon: "UndrawVideoTutorial" },
  undrawElements: { name: "Elements", icon: "UndrawElements" },
  undrawLanding: { name: "Landing", icon: "UndrawLanding" },
  undrawShoppingBags: { name: "Shopping Bags", icon: "UndrawShoppingBags" },
  undrawBlog: { name: "Blog", icon: "UndrawBlog" },
  undrawSmartphone: { name: "Smartphone", icon: "UndrawSmartphone" },
  undrawSocialPost: { name: "Social Post", icon: "UndrawSocialPost" },
  undrawComputerApps: { name: "Computer Apps", icon: "UndrawComputerApps" },
  undrawPost: { name: "Post", icon: "UndrawPost" },
  undrawWalkingTogether: {
    name: "Walking Together",
    icon: "UndrawWalkingTogether",
  },
  undrawPosts: { name: "Posts", icon: "UndrawPosts" },
  undrawLikePost: { name: "Like Post", icon: "UndrawLikePost" },
  undrawHappy: { name: "Happy", icon: "UndrawHappy" },
  undrawReading: { name: "Reading", icon: "UndrawReading" },
  undrawPost: { name: "Post", icon: "UndrawPost" },
  undrawVintage: { name: "Vintage", icon: "UndrawVintage" },
  undrawFlyingDrone: { name: "Flying Drone", icon: "UndrawFlyingDrone" },
  undrawExperienceDesign: {
    name: "Experience Design",
    icon: "UndrawExperienceDesign",
  },
  undrawApplications: { name: "Applications", icon: "UndrawApplications" },
  undrawWalking: { name: "Walking", icon: "UndrawWalking" },
  undrawTakingPhoto: { name: "Taking Photo", icon: "UndrawTakingPhoto" },
  undrawChooseColor: { name: "Choose Color", icon: "UndrawChooseColor" },
  undrawNotifications: { name: "Notifications", icon: "UndrawNotifications" },
  undrawSwing: { name: "Swing", icon: "UndrawSwing" },
  undrawVideoGames: { name: "Video Games", icon: "UndrawVideoGames" },
  undrawChatting: { name: "Chatting", icon: "UndrawChatting" },
  undrawMessaging: { name: "Messaging", icon: "UndrawMessaging" },
  undrawWebsite: { name: "Website", icon: "UndrawWebsite" },
  undrawOpenNotes: { name: "Open Notes", icon: "UndrawOpenNotes" },
  undrawFarming: { name: "Farming", icon: "UndrawFarming" },
  undrawReadNotes: { name: "Read Notes", icon: "UndrawReadNotes" },
  undrawWatchApp: { name: "Watch App", icon: "UndrawWatchApp" },
  undrawFavorite: { name: "Favorite", icon: "UndrawFavorite" },
  undrawApplication: { name: "Application", icon: "UndrawApplication" },
  undrawVideographer: { name: "Videographer", icon: "UndrawVideographer" },
  undrawAppsNotifications: {
    name: "Apps Notifications",
    icon: "UndrawAppsNotifications",
  },
  undrawApps: { name: "Apps", icon: "UndrawApps" },
  undrawChooseCard: { name: "Choose Card", icon: "UndrawChooseCard" },
  undrawLoveIt: { name: "Love It", icon: "UndrawLoveIt" },
  undrawPosts: { name: "Posts", icon: "UndrawPosts" },
  undrawVideoCall: { name: "Video Call", icon: "UndrawVideoCall" },
  undrawSelectOption: { name: "Select Option", icon: "UndrawSelectOption" },
  undrawSelectOption: { name: "Select Option", icon: "UndrawSelectOption" },
  undrawTeamEffort: { name: "Team Effort", icon: "UndrawTeamEffort" },
  undrawCompletionProgress: {
    name: "Completion Progress",
    icon: "UndrawCompletionProgress",
  },
  undrawBusinessman: { name: "Businessman", icon: "UndrawBusinessman" },
  undrawUsersPerMinute: {
    name: "Users Per Minute",
    icon: "UndrawUsersPerMinute",
  },
  undrawSelection: { name: "Selection", icon: "UndrawSelection" },
  undrawFavouriteItem: { name: "Favourite Item", icon: "UndrawFavouriteItem" },
  undrawSignUp: { name: "Sign Up", icon: "UndrawSignUp" },
  undrawMonthlyUsers: { name: "Monthly Users", icon: "UndrawMonthlyUsers" },
  undrawMobileProfile: { name: "Mobile Profile", icon: "UndrawMobileProfile" },
  undrawNotebook: { name: "Notebook", icon: "UndrawNotebook" },
  undrawSelectedBox: { name: "Selected Box", icon: "UndrawSelectedBox" },
  undrawWebsite: { name: "Website", icon: "UndrawWebsite" },
  undrawSearchEngines: { name: "Search Engines", icon: "UndrawSearchEngines" },
  undrawWatchNotification: {
    name: "Watch Notification",
    icon: "UndrawWatchNotification",
  },
  undrawCompleted: { name: "Completed", icon: "UndrawCompleted" },
  undrawWalkingInRain: { name: "Walking In Rain", icon: "UndrawWalkingInRain" },
  undrawMobileContent: { name: "Mobile Content", icon: "UndrawMobileContent" },
  undrawPlayingGolf: { name: "Playing Golf", icon: "UndrawPlayingGolf" },
  undrawCoffeeTime: { name: "Coffee Time", icon: "UndrawCoffeeTime" },
  undrawDrinkCoffee: { name: "Drink Coffee", icon: "UndrawDrinkCoffee" },
  undrawExpecting: { name: "Expecting", icon: "UndrawExpecting" },
  undrawLandscapePhotographer: {
    name: "Landscape Photographer",
    icon: "UndrawLandscapePhotographer",
  },
  undrawPilates: { name: "Pilates", icon: "UndrawPilates" },
  undrawMobileSearch: { name: "Mobile Search", icon: "UndrawMobileSearch" },
  undrawMindfulness: { name: "Mindfulness", icon: "UndrawMindfulness" },
  undrawAnalysis: { name: "Analysis", icon: "UndrawAnalysis" },
  undrawScientist: { name: "Scientist", icon: "UndrawScientist" },
  undrawSignUp: { name: "Sign Up", icon: "UndrawSignUp" },
  undrawHomeRun: { name: "Home Run", icon: "UndrawHomeRun" },
  undrawCat: { name: "Cat", icon: "UndrawCat" },
  undrawHealthyHabit: { name: "Healthy Habit", icon: "UndrawHealthyHabit" },
  undrawSearchApp: { name: "Search App", icon: "UndrawSearchApp" },
  undrawCooking: { name: "Cooking", icon: "UndrawCooking" },
  undrawFunMoments: { name: "Fun Moments", icon: "UndrawFunMoments" },
  undrawWoman: { name: "Woman", icon: "UndrawWoman" },
  undrawDog: { name: "Dog", icon: "UndrawDog" },
  undrawGrandSlam: { name: "Grand Slam", icon: "UndrawGrandSlam" },
  undrawLoveIsInTheAir: {
    name: "Love Is In The Air",
    icon: "UndrawLoveIsInTheAir",
  },
  undrawDoctors: { name: "Doctors", icon: "UndrawDoctors" },
  undrawElectricity: { name: "Electricity", icon: "UndrawElectricity" },
  undrawCarRepair: { name: "Car Repair", icon: "UndrawCarRepair" },
  undrawFemaleAvatar: { name: "Female Avatar", icon: "UndrawFemaleAvatar" },
  undrawHappyNewYear: { name: "Happy New Year", icon: "UndrawHappyNewYear" },
  undrawMaleAvatar: { name: "Male Avatar", icon: "UndrawMaleAvatar" },
  undrawRunningWild: { name: "Running Wild", icon: "UndrawRunningWild" },
  undrawSnowGames: { name: "Snow Games", icon: "UndrawSnowGames" },
  undrawDecorateChristmasTree: {
    name: "Decorate Christmas Tree",
    icon: "UndrawDecorateChristmasTree",
  },
  undrawWinterSkating: { name: "Winter Skating", icon: "UndrawWinterSkating" },
  undrawFingerprintLogin: {
    name: "Fingerprint Login",
    icon: "UndrawFingerprintLogin",
  },
  undrawAppreciateIt: { name: "Appreciate It", icon: "UndrawAppreciateIt" },
  undrawBasketball: { name: "Basketball", icon: "UndrawBasketball" },
  undrawNotFound: { name: "Not Found", icon: "UndrawNotFound" },
  undrawBaby: { name: "Baby", icon: "UndrawBaby" },
  undrawPicProfile: { name: "Pic Profile", icon: "UndrawPicProfile" },
  undrawProfilePic: { name: "Profile Pic", icon: "UndrawProfilePic" },
  undrawHalloween: { name: "Halloween", icon: "UndrawHalloween" },
  undrawPumpkin: { name: "Pumpkin", icon: "UndrawPumpkin" },
  undrawPancakes: { name: "Pancakes", icon: "UndrawPancakes" },
  undrawBuddies: { name: "Buddies", icon: "UndrawBuddies" },
  undrawReadyForWaves: { name: "Ready For Waves", icon: "UndrawReadyForWaves" },
  undrawSummer: { name: "Summer", icon: "UndrawSummer" },
  undrawBeachDay: { name: "Beach Day", icon: "UndrawBeachDay" },
  undrawReminder: { name: "Reminder", icon: "UndrawReminder" },
  undrawFamily: { name: "Family", icon: "UndrawFamily" },
  undrawEngineeringTeam: {
    name: "Engineering Team",
    icon: "UndrawEngineeringTeam",
  },
  undrawCloudHosting: { name: "Cloud Hosting", icon: "UndrawCloudHosting" },
  undrawGifts: { name: "Gifts", icon: "UndrawGifts" },
  undrawPassingBy: { name: "Passing By", icon: "UndrawPassingBy" },
  undrawMakeItRain: { name: "Make It Rain", icon: "UndrawMakeItRain" },
  undrawGoodDoggy: { name: "Good Doggy", icon: "UndrawGoodDoggy" },
  undrawEducator: { name: "Educator", icon: "UndrawEducator" },
  undrawBlooming: { name: "Blooming", icon: "UndrawBlooming" },
  undrawWriter: { name: "Writer", icon: "UndrawWriter" },
  undrawBitcoin: { name: "Bitcoin", icon: "UndrawBitcoin" },
  undrawWedding: { name: "Wedding", icon: "UndrawWedding" },
  undrawProjections: { name: "Projections", icon: "UndrawProjections" },
  undrawRelaxation: { name: "Relaxation", icon: "UndrawRelaxation" },
  undrawAudioConversation: {
    name: "Audio Conversation",
    icon: "UndrawAudioConversation",
  },
  undrawGoodTeam: { name: "Good Team", icon: "UndrawGoodTeam" },
  undrawAircraft: { name: "Aircraft", icon: "UndrawAircraft" },
  undrawContentTeam: { name: "Content Team", icon: "UndrawContentTeam" },
  undrawGameWorld: { name: "Game World", icon: "UndrawGameWorld" },
  undrawJoin: { name: "Join", icon: "UndrawJoin" },
  undrawDesignTeam: { name: "Design Team", icon: "UndrawDesignTeam" },
  undrawEverydayLife: { name: "Everyday Life", icon: "UndrawEverydayLife" },
  undrawConvert: { name: "Convert", icon: "UndrawConvert" },
  undrawOnlineTest: { name: "Online Test", icon: "UndrawOnlineTest" },
  undrawPhotoSession: { name: "Photo Session", icon: "UndrawPhotoSession" },
  undrawButtonStyle: { name: "Button Style", icon: "UndrawButtonStyle" },
  undrawWaitInLine: { name: "Wait In Line", icon: "UndrawWaitInLine" },
  undrawCoffeeWithFriends: {
    name: "Coffee With Friends",
    icon: "UndrawCoffeeWithFriends",
  },
  undrawSharingKnowledge: {
    name: "Sharing Knowledge",
    icon: "UndrawSharingKnowledge",
  },
  undrawMultitasking: { name: "Multitasking", icon: "UndrawMultitasking" },
  undrawArticles: { name: "Articles", icon: "UndrawArticles" },
  undrawDeliveryTruck: { name: "Delivery Truck", icon: "UndrawDeliveryTruck" },
  undrawLearningSketching: {
    name: "Learning Sketching",
    icon: "UndrawLearningSketching",
  },
  undrawOnlineStats: { name: "Online Stats", icon: "UndrawOnlineStats" },
  undrawMobileAnalytics: {
    name: "Mobile Analytics",
    icon: "UndrawMobileAnalytics",
  },
  undrawOfficeSnack: { name: "Office Snack", icon: "UndrawOfficeSnack" },
  undrawPersonalTrainer: {
    name: "Personal Trainer",
    icon: "UndrawPersonalTrainer",
  },
  undrawQuittingTime: { name: "Quitting Time", icon: "UndrawQuittingTime" },
  undrawOffRoad: { name: "Off Road", icon: "UndrawOffRoad" },
  undrawColorPalette: { name: "Color Palette", icon: "UndrawColorPalette" },
  undrawUpgrade: { name: "Upgrade", icon: "UndrawUpgrade" },
  undrawFinancialData: { name: "Financial Data", icon: "UndrawFinancialData" },
  undrawNatureFun: { name: "Nature Fun", icon: "UndrawNatureFun" },
  undrawRelaxingWalk: { name: "Relaxing Walk", icon: "UndrawRelaxingWalk" },
  undrawWineTasting: { name: "Wine Tasting", icon: "UndrawWineTasting" },
  undrawBusinessChat: { name: "Business Chat", icon: "UndrawBusinessChat" },
  undrawProjectComplete: {
    name: "Project Complete",
    icon: "UndrawProjectComplete",
  },
  undrawEmptyStreet: { name: "Empty Street", icon: "UndrawEmptyStreet" },
  undrawUpdatedResume: { name: "Updated Resume", icon: "UndrawUpdatedResume" },
  undrawJobOffers: { name: "Job Offers", icon: "UndrawJobOffers" },
  undrawStatisticChart: {
    name: "Statistic Chart",
    icon: "UndrawStatisticChart",
  },
  undrawExams: { name: "Exams", icon: "UndrawExams" },
  undrawSmallTown: { name: "Small Town", icon: "UndrawSmallTown" },
  undrawSkateboard: { name: "Skateboard", icon: "UndrawSkateboard" },
  undraw3dModeling: { name: "3d Modeling", icon: "Undraw3dModeling" },
  undrawCreativeThinking: {
    name: "Creative Thinking",
    icon: "UndrawCreativeThinking",
  },
  undrawReact: { name: "React", icon: "UndrawReact" },
  undrawComposeMusic: { name: "Compose Music", icon: "UndrawComposeMusic" },
  undrawTrip: { name: "Trip", icon: "UndrawTrip" },
  undrawAMomentToRelax: {
    name: "A Moment To Relax",
    icon: "UndrawAMomentToRelax",
  },
  undrawMobileEncryption: {
    name: "Mobile Encryption",
    icon: "UndrawMobileEncryption",
  },
  undrawDesignInspiration: {
    name: "Design Inspiration",
    icon: "UndrawDesignInspiration",
  },
  undrawTermSheet: { name: "Term Sheet", icon: "UndrawTermSheet" },
  undrawWarning: { name: "Warning", icon: "UndrawWarning" },
  undrawInvestorUpdate: {
    name: "Investor Update",
    icon: "UndrawInvestorUpdate",
  },
  undrawMovingForward: { name: "Moving Forward", icon: "UndrawMovingForward" },
  undrawFinishLine: { name: "Finish Line", icon: "UndrawFinishLine" },
  undrawWorkingRemotely: {
    name: "Working Remotely",
    icon: "UndrawWorkingRemotely",
  },
  undrawHamburger: { name: "Hamburger", icon: "UndrawHamburger" },
  undrawFashionBlogging: {
    name: "Fashion Blogging",
    icon: "UndrawFashionBlogging",
  },
  undrawJourney: { name: "Journey", icon: "UndrawJourney" },
  undrawCreativeTeam: { name: "Creative Team", icon: "UndrawCreativeTeam" },
  undrawShowingSupport: {
    name: "Showing Support",
    icon: "UndrawShowingSupport",
  },
  undrawCreationProcess: {
    name: "Creation Process",
    icon: "UndrawCreationProcess",
  },
  undrawCreation: { name: "Creation", icon: "UndrawCreation" },
  undrawLearning: { name: "Learning", icon: "UndrawLearning" },
  undrawSolutionMindset: {
    name: "Solution Mindset",
    icon: "UndrawSolutionMindset",
  },
  undrawAbsorbedIn: { name: "Absorbed In", icon: "UndrawAbsorbedIn" },
  undrawPredictiveAnalytics: {
    name: "Predictive Analytics",
    icon: "UndrawPredictiveAnalytics",
  },
  undrawSpeedTest: { name: "Speed Test", icon: "UndrawSpeedTest" },
  undrawCookieLove: { name: "Cookie Love", icon: "UndrawCookieLove" },
  undrawEditable: { name: "Editable", icon: "UndrawEditable" },
  undrawProductExplainer: {
    name: "Product Explainer",
    icon: "UndrawProductExplainer",
  },
  undrawSocialThinking: {
    name: "Social Thinking",
    icon: "UndrawSocialThinking",
  },
  undrawCoolness: { name: "Coolness", icon: "UndrawCoolness" },
  undrawCalculator: { name: "Calculator", icon: "UndrawCalculator" },
  undrawFireworks: { name: "Fireworks", icon: "UndrawFireworks" },
  undrawTransferMoney: { name: "Transfer Money", icon: "UndrawTransferMoney" },
  undrawHappyFeeling: { name: "Happy Feeling", icon: "UndrawHappyFeeling" },
  undrawCleanUp: { name: "Clean Up", icon: "UndrawCleanUp" },
  undrawMobileApplication: {
    name: "Mobile Application",
    icon: "UndrawMobileApplication",
  },
  undrawSpreadLove: { name: "Spread Love", icon: "UndrawSpreadLove" },
  undrawCharacterDrawing: {
    name: "Character Drawing",
    icon: "UndrawCharacterDrawing",
  },
  undrawEverywhereTogether: {
    name: "Everywhere Together",
    icon: "UndrawEverywhereTogether",
  },
  undrawSuburbs: { name: "Suburbs", icon: "UndrawSuburbs" },
  undrawVideoInfluencer: {
    name: "Video Influencer",
    icon: "UndrawVideoInfluencer",
  },
  undrawSlider: { name: "Slider", icon: "UndrawSlider" },
  undrawWanderingMind: { name: "Wandering Mind", icon: "UndrawWanderingMind" },
  undrawEiffelTower: { name: "Eiffel Tower", icon: "UndrawEiffelTower" },
  undrawTravelPlans: { name: "Travel Plans", icon: "UndrawTravelPlans" },
  undrawInnovative: { name: "Innovative", icon: "UndrawInnovative" },
  undrawHooked: { name: "Hooked", icon: "UndrawHooked" },
  undrawOnlineBanking: { name: "Online Banking", icon: "UndrawOnlineBanking" },
  undrawSunlight: { name: "Sunlight", icon: "UndrawSunlight" },
  undrawHealthyLifestyle: {
    name: "Healthy Lifestyle",
    icon: "UndrawHealthyLifestyle",
  },
  undrawNewspaper: { name: "Newspaper", icon: "UndrawNewspaper" },
  undrawHologram: { name: "Hologram", icon: "UndrawHologram" },
  undrawPersonalDocuments: {
    name: "Personal Documents",
    icon: "UndrawPersonalDocuments",
  },
  undrawBusinessShop: { name: "Business Shop", icon: "UndrawBusinessShop" },
  undrawStartBuilding: { name: "Start Building", icon: "UndrawStartBuilding" },
  undrawNewIdeas: { name: "New Ideas", icon: "UndrawNewIdeas" },
  undrawAnimating: { name: "Animating", icon: "UndrawAnimating" },
  undrawVisionaryTechnology: {
    name: "Visionary Technology",
    icon: "UndrawVisionaryTechnology",
  },
  undrawSmartResize: { name: "Smart Resize", icon: "UndrawSmartResize" },
  undrawFuturisticInterface: {
    name: "Futuristic Interface",
    icon: "UndrawFuturisticInterface",
  },
  undrawSignalSearching: {
    name: "Signal Searching",
    icon: "UndrawSignalSearching",
  },
  undrawCircuitBoard: { name: "Circuit Board", icon: "UndrawCircuitBoard" },
  undrawOnlineArt: { name: "Online Art", icon: "UndrawOnlineArt" },
  undrawDrag: { name: "Drag", icon: "UndrawDrag" },
  undrawSearching: { name: "Searching", icon: "UndrawSearching" },
  undrawFunctions: { name: "Functions", icon: "UndrawFunctions" },
  undrawDreamWorld: { name: "Dream World", icon: "UndrawDreamWorld" },
  undrawEnergizer: { name: "Energizer", icon: "UndrawEnergizer" },
  undrawVisualization: { name: "Visualization", icon: "UndrawVisualization" },
  undrawBookReading: { name: "Book Reading", icon: "UndrawBookReading" },
  undrawServices: { name: "Services", icon: "UndrawServices" },
  undrawHealthyOptions: {
    name: "Healthy Options",
    icon: "UndrawHealthyOptions",
  },
  undrawIconDesign: { name: "Icon Design", icon: "UndrawIconDesign" },
  undrawADayOff: { name: "A Day Off", icon: "UndrawADayOff" },
  undrawSocialSharing: { name: "Social Sharing", icon: "UndrawSocialSharing" },
  undrawWorkInProgress: {
    name: "Work In Progress",
    icon: "UndrawWorkInProgress",
  },
  undrawFittingPieces: { name: "Fitting Pieces", icon: "UndrawFittingPieces" },
  undrawMobileInterface: {
    name: "Mobile Interface",
    icon: "UndrawMobileInterface",
  },
  undrawInteriorDesign: {
    name: "Interior Design",
    icon: "UndrawInteriorDesign",
  },
  undrawPersonalFinance: {
    name: "Personal Finance",
    icon: "UndrawPersonalFinance",
  },
  undrawWallet: { name: "Wallet", icon: "UndrawWallet" },
  undrawThingsToSay: { name: "Things To Say", icon: "UndrawThingsToSay" },
  undrawOSUpgrade: { name: "O S Upgrade", icon: "UndrawOSUpgrade" },
  undrawFittingPiece: { name: "Fitting Piece", icon: "UndrawFittingPiece" },
  undrawPositiveAttitude: {
    name: "Positive Attitude",
    icon: "UndrawPositiveAttitude",
  },
  undrawExcitingNews: { name: "Exciting News", icon: "UndrawExcitingNews" },
  undrawAugmentedReality: {
    name: "Augmented Reality",
    icon: "UndrawAugmentedReality",
  },
  undrawNoted: { name: "Noted", icon: "UndrawNoted" },
  undrawOnlineDiscussion: {
    name: "Online Discussion",
    icon: "UndrawOnlineDiscussion",
  },
  undrawTutor: { name: "Tutor", icon: "UndrawTutor" },
  undrawCertification: { name: "Certification", icon: "UndrawCertification" },
  undrawPayOnline: { name: "Pay Online", icon: "UndrawPayOnline" },
  undrawStaticWebsite: { name: "Static Website", icon: "UndrawStaticWebsite" },
  undrawShareLink: { name: "Share Link", icon: "UndrawShareLink" },
  undrawCoupleLove: { name: "Couple Love", icon: "UndrawCoupleLove" },
  undrawPullRequest: { name: "Pull Request", icon: "UndrawPullRequest" },
  undrawQuiz: { name: "Quiz", icon: "UndrawQuiz" },
  undrawFillIn: { name: "Fill In", icon: "UndrawFillIn" },
  undrawAgree: { name: "Agree", icon: "UndrawAgree" },
  undrawTutorialVideo: { name: "Tutorial Video", icon: "UndrawTutorialVideo" },
  undrawFileManager: { name: "File Manager", icon: "UndrawFileManager" },
  undrawMyPassword: { name: "My Password", icon: "UndrawMyPassword" },
  undrawCompleteDesign: {
    name: "Complete Design",
    icon: "UndrawCompleteDesign",
  },
  undrawCloseTab: { name: "Close Tab", icon: "UndrawCloseTab" },
  undrawUnlock: { name: "Unlock", icon: "UndrawUnlock" },
  undrawPeople: { name: "People", icon: "UndrawPeople" },
  undrawDesignData: { name: "Design Data", icon: "UndrawDesignData" },
  undrawMobileUser: { name: "Mobile User", icon: "UndrawMobileUser" },
  undrawInvestment: { name: "Investment", icon: "UndrawInvestment" },
  undrawPortfolioWebsite: {
    name: "Portfolio Website",
    icon: "UndrawPortfolioWebsite",
  },
  undrawDiary: { name: "Diary", icon: "UndrawDiary" },
  undrawInstantAnalysis: {
    name: "Instant Analysis",
    icon: "UndrawInstantAnalysis",
  },
  undrawGroupHangout: { name: "Group Hangout", icon: "UndrawGroupHangout" },
  undrawIdeasFlow: { name: "Ideas Flow", icon: "UndrawIdeasFlow" },
  undrawLovingStory: { name: "Loving Story", icon: "UndrawLovingStory" },
  undrawGardening: { name: "Gardening", icon: "UndrawGardening" },
  undrawIdeas: { name: "Ideas", icon: "UndrawIdeas" },
  undrawReview: { name: "Review", icon: "UndrawReview" },
  undrawRightPlaces: { name: "Right Places", icon: "UndrawRightPlaces" },
  undrawPicture: { name: "Picture", icon: "UndrawPicture" },
  undrawInspiration: { name: "Inspiration", icon: "UndrawInspiration" },
  undrawTrendyInterface: {
    name: "Trendy Interface",
    icon: "UndrawTrendyInterface",
  },
  undrawPersonalInfo: { name: "Personal Info", icon: "UndrawPersonalInfo" },
  undrawBodyText: { name: "Body Text", icon: "UndrawBodyText" },
  undrawProfileDetails: {
    name: "Profile Details",
    icon: "UndrawProfileDetails",
  },
  undrawOnlineDating: { name: "Online Dating", icon: "UndrawOnlineDating" },
  undrawGoingUp: { name: "Going Up", icon: "UndrawGoingUp" },
  undrawVoiceInterface: {
    name: "Voice Interface",
    icon: "UndrawVoiceInterface",
  },
  undrawRealTimeAnalytics: {
    name: "Real Time Analytics",
    icon: "UndrawRealTimeAnalytics",
  },
  undrawCompleting: { name: "Completing", icon: "UndrawCompleting" },
  undrawWelcoming: { name: "Welcoming", icon: "UndrawWelcoming" },
  undrawProudCoder: { name: "Proud Coder", icon: "UndrawProudCoder" },
  undrawReferral: { name: "Referral", icon: "UndrawReferral" },
  undrawKeyPoints: { name: "Key Points", icon: "UndrawKeyPoints" },
  undrawStripePayments: {
    name: "Stripe Payments",
    icon: "UndrawStripePayments",
  },
  undrawStarlink: { name: "Starlink", icon: "UndrawStarlink" },
  undrawResearching: { name: "Researching", icon: "UndrawResearching" },
  undrawAskMeAnything: { name: "Ask Me Anything", icon: "UndrawAskMeAnything" },
  undrawReadingTime: { name: "Reading Time", icon: "UndrawReadingTime" },
  undrawCountingStars: { name: "Counting Stars", icon: "UndrawCountingStars" },
  undrawFont: { name: "Font", icon: "UndrawFont" },
  undrawPreferencesPopup: {
    name: "Preferences Popup",
    icon: "UndrawPreferencesPopup",
  },
  undrawPersonalFile: { name: "Personal File", icon: "UndrawPersonalFile" },
  undrawPerformanceOverview: {
    name: "Performance Overview",
    icon: "UndrawPerformanceOverview",
  },
  undrawJustBrowsing: { name: "Just Browsing", icon: "UndrawJustBrowsing" },
  undrawMobileDevelopment: {
    name: "Mobile Development",
    icon: "UndrawMobileDevelopment",
  },
  undrawAcceptTasks: { name: "Accept Tasks", icon: "UndrawAcceptTasks" },
  undrawStarryWindow: { name: "Starry Window", icon: "UndrawStarryWindow" },
  undrawHomeScreen: { name: "Home Screen", icon: "UndrawHomeScreen" },
  undrawGoneShopping: { name: "Gone Shopping", icon: "UndrawGoneShopping" },
  undrawDatePicker: { name: "Date Picker", icon: "UndrawDatePicker" },
  undrawImageViewer: { name: "Image Viewer", icon: "UndrawImageViewer" },
  undrawMyPersonalFiles: {
    name: "My Personal Files",
    icon: "UndrawMyPersonalFiles",
  },
  undrawMyCodeSnippets: {
    name: "My Code Snippets",
    icon: "UndrawMyCodeSnippets",
  },
  undrawInformationTab: {
    name: "Information Tab",
    icon: "UndrawInformationTab",
  },
  undrawAdvancedCustomization: {
    name: "Advanced Customization",
    icon: "UndrawAdvancedCustomization",
  },
  undrawAuthentication: {
    name: "Authentication",
    icon: "UndrawAuthentication",
  },
  undrawTeaching: { name: "Teaching", icon: "UndrawTeaching" },
  undrawScooter: { name: "Scooter", icon: "UndrawScooter" },
  undrawJogging: { name: "Jogging", icon: "UndrawJogging" },
  undrawDestinations: { name: "Destinations", icon: "UndrawDestinations" },
  undrawPenTool: { name: "Pen Tool", icon: "UndrawPenTool" },
  undrawSpeechToText: { name: "Speech To Text", icon: "UndrawSpeechToText" },
  undrawCoffee: { name: "Coffee", icon: "UndrawCoffee" },
  undrawMovieNight: { name: "Movie Night", icon: "UndrawMovieNight" },
  undrawPersonalData: { name: "Personal Data", icon: "UndrawPersonalData" },
  undrawKnowledge: { name: "Knowledge", icon: "UndrawKnowledge" },
  undrawCancel: { name: "Cancel", icon: "UndrawCancel" },
  undrawPieGraph: { name: "Pie Graph", icon: "UndrawPieGraph" },
  undrawSmartwatch: { name: "Smartwatch", icon: "UndrawSmartwatch" },
  undrawResult: { name: "Result", icon: "UndrawResult" },
  undrawHappyNews: { name: "Happy News", icon: "UndrawHappyNews" },
  undrawPercentages: { name: "Percentages", icon: "UndrawPercentages" },
  undrawTeacher: { name: "Teacher", icon: "UndrawTeacher" },
  undrawAirSupport: { name: "Air Support", icon: "UndrawAirSupport" },
  undrawYear2022: { name: "Year2022", icon: "UndrawYear2022" },
  undrawFolder: { name: "Folder", icon: "UndrawFolder" },
  undrawServerStatus: { name: "Server Status", icon: "UndrawServerStatus" },
  undrawTasting: { name: "Tasting", icon: "UndrawTasting" },
  undrawProductTeardown: {
    name: "Product Teardown",
    icon: "UndrawProductTeardown",
  },
  undrawBuildingBlocks: {
    name: "Building Blocks",
    icon: "UndrawBuildingBlocks",
  },
  undrawNewYear2022: { name: "New Year2022", icon: "UndrawNewYear2022" },
  undrawInstantSupport: {
    name: "Instant Support",
    icon: "UndrawInstantSupport",
  },
  undrawWorld: { name: "World", icon: "UndrawWorld" },
  undrawEther: { name: "Ether", icon: "UndrawEther" },
  undrawDeliveries: { name: "Deliveries", icon: "UndrawDeliveries" },
  undrawSnowman: { name: "Snowman", icon: "UndrawSnowman" },
  undrawContactUs: { name: "Contact Us", icon: "UndrawContactUs" },
  undrawConferenceSpeaker: {
    name: "Conference Speaker",
    icon: "UndrawConferenceSpeaker",
  },
  undrawWinterWalk: { name: "Winter Walk", icon: "UndrawWinterWalk" },
  undrawShopping: { name: "Shopping", icon: "UndrawShopping" },
  undrawSocialUpdate: { name: "Social Update", icon: "UndrawSocialUpdate" },
  undrawSoftwareEngineer: {
    name: "Software Engineer",
    icon: "UndrawSoftwareEngineer",
  },
  undrawOnlineOrganizer: {
    name: "Online Organizer",
    icon: "UndrawOnlineOrganizer",
  },
  undrawConnection: { name: "Connection", icon: "UndrawConnection" },
  undrawTeamCollaboration: {
    name: "Team Collaboration",
    icon: "UndrawTeamCollaboration",
  },
  undrawSocialGirl: { name: "Social Girl", icon: "UndrawSocialGirl" },
  undrawTypewriter: { name: "Typewriter", icon: "UndrawTypewriter" },
  undrawDreamer: { name: "Dreamer", icon: "UndrawDreamer" },
  undrawTrends: { name: "Trends", icon: "UndrawTrends" },
  undrawInsert: { name: "Insert", icon: "UndrawInsert" },
  undrawCertificate: { name: "Certificate", icon: "UndrawCertificate" },
  undrawWinners: { name: "Winners", icon: "UndrawWinners" },
  undrawMakerLaunch: { name: "Maker Launch", icon: "UndrawMakerLaunch" },
  undrawApps: { name: "Apps", icon: "UndrawApps" },
  undrawCollaborating: { name: "Collaborating", icon: "UndrawCollaborating" },
  undrawGettingCoffee: { name: "Getting Coffee", icon: "UndrawGettingCoffee" },
  undrawPodcast: { name: "Podcast", icon: "UndrawPodcast" },
  undrawSocialDashboard: {
    name: "Social Dashboard",
    icon: "UndrawSocialDashboard",
  },
  undrawMobileBrowsers: {
    name: "Mobile Browsers",
    icon: "UndrawMobileBrowsers",
  },
  undrawMessenger: { name: "Messenger", icon: "UndrawMessenger" },
  undrawSurfer: { name: "Surfer", icon: "UndrawSurfer" },
  undrawPhotocopy: { name: "Photocopy", icon: "UndrawPhotocopy" },
  undrawFeaturesOverview: {
    name: "Features Overview",
    icon: "UndrawFeaturesOverview",
  },
  undrawInterview: { name: "Interview", icon: "UndrawInterview" },
  undrawStudying: { name: "Studying", icon: "UndrawStudying" },
  undrawFans: { name: "Fans", icon: "UndrawFans" },
  undrawCreativity: { name: "Creativity", icon: "UndrawCreativity" },
  undrawCampfire: { name: "Campfire", icon: "UndrawCampfire" },
  undrawTarget: { name: "Target", icon: "UndrawTarget" },
  undrawStartupLife: { name: "Startup Life", icon: "UndrawStartupLife" },
  undrawBlankCanvas: { name: "Blank Canvas", icon: "UndrawBlankCanvas" },
  undrawPrototypingProcess: {
    name: "Prototyping Process",
    icon: "UndrawPrototypingProcess",
  },
  undrawOpinion: { name: "Opinion", icon: "UndrawOpinion" },
  undrawSecurity: { name: "Security", icon: "UndrawSecurity" },
  undrawProgramming: { name: "Programming", icon: "UndrawProgramming" },
  undrawConversation: { name: "Conversation", icon: "UndrawConversation" },
  undrawRideABicycle: { name: "Ride A Bicycle", icon: "UndrawRideABicycle" },
  undrawInTheOffice: { name: "In The Office", icon: "UndrawInTheOffice" },
  undrawThoughts: { name: "Thoughts", icon: "UndrawThoughts" },
  undrawDesignerGirl: { name: "Designer Girl", icon: "UndrawDesignerGirl" },
  undrawOnlineMedia: { name: "Online Media", icon: "UndrawOnlineMedia" },
  undrawAddColor: { name: "Add Color", icon: "UndrawAddColor" },
  undrawChristmasMode: { name: "Christmas Mode", icon: "UndrawChristmasMode" },
  undrawDigitalNomad: { name: "Digital Nomad", icon: "UndrawDigitalNomad" },
  undrawConference: { name: "Conference", icon: "UndrawConference" },
  undrawLaunching: { name: "Launching", icon: "UndrawLaunching" },
  undrawScience: { name: "Science", icon: "UndrawScience" },
  undrawBookLover: { name: "Book Lover", icon: "UndrawBookLover" },
  undrawBirthdayCake: { name: "Birthday Cake", icon: "UndrawBirthdayCake" },
  undrawMap: { name: "Map", icon: "UndrawMap" },
  undrawArtLover: { name: "Art Lover", icon: "UndrawArtLover" },
  undrawCryptoFlowers: { name: "Crypto Flowers", icon: "UndrawCryptoFlowers" },
  undrawPersonalization: {
    name: "Personalization",
    icon: "UndrawPersonalization",
  },
  undrawFirmware: { name: "Firmware", icon: "UndrawFirmware" },
  undrawReminders: { name: "Reminders", icon: "UndrawReminders" },
  undrawBusinessMan: { name: "Business Man", icon: "UndrawBusinessMan" },
  undrawModernWoman: { name: "Modern Woman", icon: "UndrawModernWoman" },
  undrawManageChats: { name: "Manage Chats", icon: "UndrawManageChats" },
  undrawDetails: { name: "Details", icon: "UndrawDetails" },
  undrawAddInformation: {
    name: "Add Information",
    icon: "UndrawAddInformation",
  },
  undrawMediaPlayer: { name: "Media Player", icon: "UndrawMediaPlayer" },
  undrawPageNotFound: { name: "Page Not Found", icon: "UndrawPageNotFound" },
  undrawWebDevelopment: {
    name: "Web Development",
    icon: "UndrawWebDevelopment",
  },
  undrawLateAtNight: { name: "Late At Night", icon: "UndrawLateAtNight" },
  undrawSelecting: { name: "Selecting", icon: "UndrawSelecting" },
  undrawSocialInteraction: {
    name: "Social Interaction",
    icon: "UndrawSocialInteraction",
  },
  undrawRevenue: { name: "Revenue", icon: "UndrawRevenue" },
  undrawMobileTesting: { name: "Mobile Testing", icon: "UndrawMobileTesting" },
  undrawHappyAnnouncement: {
    name: "Happy Announcement",
    icon: "UndrawHappyAnnouncement",
  },
  undrawExploring: { name: "Exploring", icon: "UndrawExploring" },
  undrawWebDevices: { name: "Web Devices", icon: "UndrawWebDevices" },
  undrawFilter: { name: "Filter", icon: "UndrawFilter" },
  undrawWorkingFromAnywhere: {
    name: "Working From Anywhere",
    icon: "UndrawWorkingFromAnywhere",
  },
  undrawFeedback: { name: "Feedback", icon: "UndrawFeedback" },
  undrawDesignerLife: { name: "Designer Life", icon: "UndrawDesignerLife" },
  undrawSaveToBookmarks: {
    name: "Save To Bookmarks",
    icon: "UndrawSaveToBookmarks",
  },
  undrawRespond: { name: "Respond", icon: "UndrawRespond" },
  undrawMyNotifications: {
    name: "My Notifications",
    icon: "UndrawMyNotifications",
  },
  undrawTimeManagement: {
    name: "Time Management",
    icon: "UndrawTimeManagement",
  },
  undrawWorkTogether: { name: "Work Together", icon: "UndrawWorkTogether" },
  undrawFolderFiles: { name: "Folder Files", icon: "UndrawFolderFiles" },
  undrawMessageSent: { name: "Message Sent", icon: "UndrawMessageSent" },
  undrawFollowing: { name: "Following", icon: "UndrawFollowing" },
  undrawImagePost: { name: "Image Post", icon: "UndrawImagePost" },
  undrawControlPanel: { name: "Control Panel", icon: "UndrawControlPanel" },
  undrawCheckingBoxes: { name: "Checking Boxes", icon: "UndrawCheckingBoxes" },
  undrawMakingArt: { name: "Making Art", icon: "UndrawMakingArt" },
  undrawPressPlay: { name: "Press Play", icon: "UndrawPressPlay" },
  undrawOrganizingProjects: {
    name: "Organizing Projects",
    icon: "UndrawOrganizingProjects",
  },
  undrawInboxCleanup: { name: "Inbox Cleanup", icon: "UndrawInboxCleanup" },
  undrawWindowShopping: {
    name: "Window Shopping",
    icon: "UndrawWindowShopping",
  },
  undrawVRChat: { name: "V R Chat", icon: "UndrawVRChat" },
  undrawLoadMore: { name: "Load More", icon: "UndrawLoadMore" },
  undrawDeliveryAddress: {
    name: "Delivery Address",
    icon: "UndrawDeliveryAddress",
  },
  undrawMeetTheTeam: { name: "Meet The Team", icon: "UndrawMeetTheTeam" },
  undrawBusinessDeal: { name: "Business Deal", icon: "UndrawBusinessDeal" },
  undrawConnectingTeams: {
    name: "Connecting Teams",
    icon: "UndrawConnectingTeams",
  },
  undrawPublishPost: { name: "Publish Post", icon: "UndrawPublishPost" },
  undrawSharedGoals: { name: "Shared Goals", icon: "UndrawSharedGoals" },
  undrawCurrentLocation: {
    name: "Current Location",
    icon: "UndrawCurrentLocation",
  },
  undrawWorkingLate: { name: "Working Late", icon: "UndrawWorkingLate" },
  undrawGrades: { name: "Grades", icon: "UndrawGrades" },
  undrawCollaborators: { name: "Collaborators", icon: "UndrawCollaborators" },
  undrawThoughtProcess: {
    name: "Thought Process",
    icon: "UndrawThoughtProcess",
  },
  undrawFileBundle: { name: "File Bundle", icon: "UndrawFileBundle" },
  undrawAboutMe: { name: "About Me", icon: "UndrawAboutMe" },
  undrawNextTasks: { name: "Next Tasks", icon: "UndrawNextTasks" },
  undrawOnlineVideo: { name: "Online Video", icon: "UndrawOnlineVideo" },
  undrawCountrySide: { name: "Country Side", icon: "UndrawCountrySide" },
  undrawDetailedExamination: {
    name: "Detailed Examination",
    icon: "UndrawDetailedExamination",
  },
  undrawBeginChat: { name: "Begin Chat", icon: "UndrawBeginChat" },
  undrawTweetstorm: { name: "Tweetstorm", icon: "UndrawTweetstorm" },
  undrawCommunity: { name: "Community", icon: "UndrawCommunity" },
  undrawDroneDelivery: { name: "Drone Delivery", icon: "UndrawDroneDelivery" },
  undrawEmailCapture: { name: "Email Capture", icon: "UndrawEmailCapture" },
  undrawCoWorking: { name: "Co Working", icon: "UndrawCo-Working" },
  undrawAnnotation: { name: "Annotation", icon: "UndrawAnnotation" },
  undrawSocialFriends: { name: "Social Friends", icon: "UndrawSocialFriends" },
  undrawSynchronize: { name: "Synchronize", icon: "UndrawSynchronize" },
  undrawAutumn: { name: "Autumn", icon: "UndrawAutumn" },
  undrawPolaroid: { name: "Polaroid", icon: "UndrawPolaroid" },
  undrawGroupVideo: { name: "Group Video", icon: "UndrawGroupVideo" },
  undrawWelcome: { name: "Welcome", icon: "UndrawWelcome" },
  undrawAddToCart: { name: "Add To Cart", icon: "UndrawAddToCart" },
  undrawBeforeDawn: { name: "Before Dawn", icon: "UndrawBeforeDawn" },
  undrawForgotPassword: {
    name: "Forgot Password",
    icon: "UndrawForgotPassword",
  },
  undrawMomentToRemember: {
    name: "Moment To Remember",
    icon: "UndrawMomentToRemember",
  },
  undrawTeam: { name: "Team", icon: "UndrawTeam" },
  undrawExplore: { name: "Explore", icon: "UndrawExplore" },
  undrawMoving: { name: "Moving", icon: "UndrawMoving" },
  undrawOnlinePayments: {
    name: "Online Payments",
    icon: "UndrawOnlinePayments",
  },
  undrawInSync: { name: "In Sync", icon: "UndrawInSync" },
  undrawGaming: { name: "Gaming", icon: "UndrawGaming" },
  undrawAnalyze: { name: "Analyze", icon: "UndrawAnalyze" },
  undrawRomanticGetaway: {
    name: "Romantic Getaway",
    icon: "UndrawRomanticGetaway",
  },
  undrawBibliophile: { name: "Bibliophile", icon: "UndrawBibliophile" },
  undrawCollecting: { name: "Collecting", icon: "UndrawCollecting" },
  undrawHighFive: { name: "High Five", icon: "UndrawHighFive" },
  undrawSpreadsheets: { name: "Spreadsheets", icon: "UndrawSpreadsheets" },
  undrawOnline: { name: "Online", icon: "UndrawOnline" },
  undrawOuterSpace: { name: "Outer Space", icon: "UndrawOuterSpace" },
  undrawDeveloperActivity: {
    name: "Developer Activity",
    icon: "UndrawDeveloperActivity",
  },
  undrawInfluencer: { name: "Influencer", icon: "UndrawInfluencer" },
  undrawEmpty: { name: "Empty", icon: "UndrawEmpty" },
  undrawTeamSpirit: { name: "Team Spirit", icon: "UndrawTeamSpirit" },
  undrawHappyBirthday: { name: "Happy Birthday", icon: "UndrawHappyBirthday" },
  undrawStars: { name: "Stars", icon: "UndrawStars" },
  undrawBusinesswoman: { name: "Businesswoman", icon: "UndrawBusinesswoman" },
  undrawCouple: { name: "Couple", icon: "UndrawCouple" },
  undrawPersonalWebsite: {
    name: "Personal Website",
    icon: "UndrawPersonalWebsite",
  },
  undrawOrderDelivered: {
    name: "Order Delivered",
    icon: "UndrawOrderDelivered",
  },
  undrawClickHere: { name: "Click Here", icon: "UndrawClickHere" },
  undrawContract: { name: "Contract", icon: "UndrawContract" },
  undrawSetupAnalytics: {
    name: "Setup Analytics",
    icon: "UndrawSetupAnalytics",
  },
  undrawResponsive: { name: "Responsive", icon: "UndrawResponsive" },
  undrawWalkInTheCity: {
    name: "Walk In The City",
    icon: "UndrawWalkInTheCity",
  },
  undrawRealTimeSync: { name: "Real Time Sync", icon: "UndrawReal-TimeSync" },
  undrawEvents: { name: "Events", icon: "UndrawEvents" },
  undrawSunnyDay: { name: "Sunny Day", icon: "UndrawSunnyDay" },
  // undrawNewMessage: {"name":"New Message","icon":"UndrawNewMessage"} ,
  undrawJobHunt: { name: "Job Hunt", icon: "UndrawJobHunt" },
  undrawFreshNotification: {
    name: "Fresh Notification",
    icon: "UndrawFreshNotification",
  },
  undrawEatingTogether: {
    name: "Eating Together",
    icon: "UndrawEatingTogether",
  },
  undrawDetailedAnalysis: {
    name: "Detailed Analysis",
    icon: "UndrawDetailedAnalysis",
  },
  undrawBeer: { name: "Beer", icon: "UndrawBeer" },
  undrawCalling: { name: "Calling", icon: "UndrawCalling" },
  undrawSuperThankYou: { name: "Super Thank You", icon: "UndrawSuperThankYou" },
  undrawInThought: { name: "In Thought", icon: "UndrawInThought" },
  undrawShareOnline: { name: "Share Online", icon: "UndrawShareOnline" },
  undrawDeparting: { name: "Departing", icon: "UndrawDeparting" },
  undrawDesignProcess: { name: "Design Process", icon: "UndrawDesignProcess" },
  undrawImageFocus: { name: "Image Focus", icon: "UndrawImageFocus" },
  undrawAddPost: { name: "Add Post", icon: "UndrawAddPost" },
  undrawEmails: { name: "Emails", icon: "UndrawEmails" },
  undrawFastLoading: { name: "Fast Loading", icon: "UndrawFastLoading" },
  undrawArt: { name: "Art", icon: "UndrawArt" },
  undrawChasingLove: { name: "Chasing Love", icon: "UndrawChasingLove" },
  undrawActiveSupport: { name: "Active Support", icon: "UndrawActiveSupport" },
  undrawVirtualReality: {
    name: "Virtual Reality",
    icon: "UndrawVirtualReality",
  },
  undrawChilling: { name: "Chilling", icon: "UndrawChilling" },
  undrawOnlineCv: { name: "Online Cv", icon: "UndrawOnlineCv" },
  undrawDesignNotes: { name: "Design Notes", icon: "UndrawDesignNotes" },
  undrawSpecs: { name: "Specs", icon: "UndrawSpecs" },
  undrawWorking: { name: "Working", icon: "UndrawWorking" },
  undrawMobilePosts: { name: "Mobile Posts", icon: "UndrawMobilePosts" },
  undrawRandomThoughts: {
    name: "Random Thoughts",
    icon: "UndrawRandomThoughts",
  },
  undrawAlert: { name: "Alert", icon: "UndrawAlert" },
  undrawOurNeighborhood: {
    name: "Our Neighborhood",
    icon: "UndrawOurNeighborhood",
  },
  undrawListening: { name: "Listening", icon: "UndrawListening" },
  undrawNewEntries: { name: "New Entries", icon: "UndrawNewEntries" },
  undrawWebShopping: { name: "Web Shopping", icon: "UndrawWebShopping" },
  undrawRemoteMeeting: { name: "Remote Meeting", icon: "UndrawRemoteMeeting" },
  undrawThroughTheDesert: {
    name: "Through The Desert",
    icon: "UndrawThroughTheDesert",
  },
  undrawVault: { name: "Vault", icon: "UndrawVault" },
  undrawSelectedOptions: {
    name: "Selected Options",
    icon: "UndrawSelectedOptions",
  },
  undrawDesignObjectives: {
    name: "Design Objectives",
    icon: "UndrawDesignObjectives",
  },
  undrawUsabilityTesting: {
    name: "Usability Testing",
    icon: "UndrawUsabilityTesting",
  },
  undrawSiteStats: { name: "Site Stats", icon: "UndrawSiteStats" },
  undrawPartying: { name: "Partying", icon: "UndrawPartying" },
  undrawWorkFromAnywhere: {
    name: "Work From Anywhere",
    icon: "UndrawWorkFromAnywhere",
  },
  undrawAddDocument: { name: "Add Document", icon: "UndrawAddDocument" },
  undrawGrowthCurve: { name: "Growth Curve", icon: "UndrawGrowthCurve" },
  undrawPortfolioFeedback: {
    name: "Portfolio Feedback",
    icon: "UndrawPortfolioFeedback",
  },
  undrawArrived: { name: "Arrived", icon: "UndrawArrived" },
  undrawDecide: { name: "Decide", icon: "UndrawDecide" },
  undrawSiteContent: { name: "Site Content", icon: "UndrawSiteContent" },
  undrawNewNotifications: {
    name: "New Notifications",
    icon: "UndrawNewNotifications",
  },
  undrawOnlineGallery: { name: "Online Gallery", icon: "UndrawOnlineGallery" },
  undrawOnlineChat: { name: "Online Chat", icon: "UndrawOnlineChat" },
  undrawAssetSelection: {
    name: "Asset Selection",
    icon: "UndrawAssetSelection",
  },
  undrawPublicDiscussion: {
    name: "Public Discussion",
    icon: "UndrawPublicDiscussion",
  },
  undrawActiveOptions: { name: "Active Options", icon: "UndrawActiveOptions" },
  undrawBrowsing: { name: "Browsing", icon: "UndrawBrowsing" },
  undrawAnonymousFeedback: {
    name: "Anonymous Feedback",
    icon: "UndrawAnonymousFeedback",
  },
  undrawSharedWorkspace: {
    name: "Shared Workspace",
    icon: "UndrawSharedWorkspace",
  },
  undrawDataExtraction: {
    name: "Data Extraction",
    icon: "UndrawDataExtraction",
  },
  undrawAddTasks: { name: "Add Tasks", icon: "UndrawAddTasks" },
  undrawAddFile: { name: "Add File", icon: "UndrawAddFile" },
  undrawWebsiteBuilder: {
    name: "Website Builder",
    icon: "UndrawWebsiteBuilder",
  },
  undrawBlogging: { name: "Blogging", icon: "UndrawBlogging" },
  undrawOutdoorAdventure: {
    name: "Outdoor Adventure",
    icon: "UndrawOutdoorAdventure",
  },
  undrawOnlineArticles: {
    name: "Online Articles",
    icon: "UndrawOnlineArticles",
  },
  undrawSync: { name: "Sync", icon: "UndrawSync" },
  undrawSchedule: { name: "Schedule", icon: "UndrawSchedule" },
  undrawCompletedSteps: {
    name: "Completed Steps",
    icon: "UndrawCompletedSteps",
  },
  undrawSyncFiles: { name: "Sync Files", icon: "UndrawSyncFiles" },
  undrawInvestmentData: {
    name: "Investment Data",
    icon: "UndrawInvestmentData",
  },
  undrawCustomerSurvey: {
    name: "Customer Survey",
    icon: "UndrawCustomerSurvey",
  },
  undrawMeditation: { name: "Meditation", icon: "UndrawMeditation" },
  undrawWeatherNotification: {
    name: "Weather Notification",
    icon: "UndrawWeatherNotification",
  },
  undrawMyAnswer: { name: "My Answer", icon: "UndrawMyAnswer" },
  undrawYoutubeTutorial: {
    name: "Youtube Tutorial",
    icon: "UndrawYoutubeTutorial",
  },
  undrawMobilePayments: {
    name: "Mobile Payments",
    icon: "UndrawMobilePayments",
  },
  undrawJoyride: { name: "Joyride", icon: "UndrawJoyride" },
  // undrawTakingSelfie: {"name":"Taking Selfie","icon":"UndrawTakingSelfie"} ,
};
